### ISSUE TITLE
OmniSharp stop works when I try Format file on a large project.

### ISSUE THREAD

**Issue by bernardbr** [OmniSharp/omnisharp-vscode#1647]
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

VS Code version: 1.14.1
C# Extension version: 1.11.0

## Steps to reproduce

I have a large project with more than 2k *.cs files, and sometimes when I press CTRL + ALT + F to format a file, the OmniSharp stop works, the shortcuts stops works too and when I close the VsCode the process still running with OmniSharp (Image above). I've tried to catch the error from OmniSharp logs but it doesn't appear.

![image](https://user-images.githubusercontent.com/4705034/28329775-6edc1458-6bc1-11e7-8137-b42fdd4987fb.png)

## Expected  behavior

The file format must work fine and OmniSharp didn't stop.

## Actual behavior

All functionalities of OmniSharp and VsCode stops.

**Comment by DustinCampbell** [comment]
@bernardbr: Is there anything in your OmniSharp Log when this occurs? Note that the number of files in your project shouldn't affect formatting, since it only requires the current file to operate.

**Comment by bernardbr** [comment]
Hi, @DustinCampbell I attached the OmniSharp.log. I did this: Opened the project folder, waited the OmniSharp ran the "project load", after that, I cleared the log.

I pressed CTRL + ALT + F and copied the log.  

Note: I omitted the "Buffer" property because unfortunately, I can't share my source code.

[omnisharp.txt](https://github.com/OmniSharp/omnisharp-vscode/files/1157078/omnisharp.txt)

**Comment by DustinCampbell** [comment]
Hmmm... it doesn't like OmniSharp didn't stop -- at least, not from the format itself. From your log, it appears that the formatting response came back successfully (at the top of the log) and then other requests were sent and returns (e.g. find usages).

**Comment by bernardbr** [comment]
Yes, the Code Format works in the first time, but after that, for example, the method reference indicator disappears and the Code Format stops works. If I try to build using Shortcut (CTRL + SHIFT + B) won't work too.

And nothing new appears at Log...

**Comment by DustinCampbell** [comment]
Could you try turning on the Developer Tools in VS Code (Help->Toggle Developer Tools) and see if there's anything in the Console when this happens?

**Comment by bernardbr** [comment]
Off course!

Appears only this error:

Illegal argument: line must be positive: Error: Illegal argument: line must be positive
    at Object.t.illegalArgument (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:54351)
    at new e (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:228872)
    at CodeActionProvider.getInitializeFromCtorCommand (C:\Users\bernardo.dsn.erp\.vscode\extensions\jchannon.csharpextensions-1.3.0\out\src\codeActionProvider.js:166:61)
    at addInitalizeFromCtor (C:\Users\bernardo.dsn.erp\.vscode\extensions\jchannon.csharpextensions-1.3.0\out\src\codeActionProvider.js:15:28)
    at CodeActionProvider.provideCodeActions (C:\Users\bernardo.dsn.erp\.vscode\extensions\jchannon.csharpextensions-1.3.0\out\src\codeActionProvider.js:19:9)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:352616
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:63826
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:49058)
    at Object.t.asWinJsPromise (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:63789)
    at e.provideCodeActions (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:352570)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:362438
    at t._withAdapter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:359002)
    at t.$provideCodeActions (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:362400)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308956)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189275)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189930)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

e.onUnexpectedError @ shell.ts:443
(anonymous) @ shell.ts:403
e.onUnexpectedExternalError @ errors.ts:125
t.onUnexpectedExternalError @ errors.ts:147
(anonymous) @ quickFix.ts:26
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
(anonymous) @ async.ts:360
done @ winjs.base.raw.js:1378
v @ winjs.base.raw.js:1224
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
e.resolveErr @ ipcRemoteCom.ts:111
f @ ipcRemoteCom.ts:203
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

**Comment by DustinCampbell** [comment]
It looks like that error is in jchannon.csharpextensions-1.3.0. Could you uninstall that extension and see if it fixes the C# for VS Code problem?

pinging @jchannon: do you know if this is a known issue?

**Comment by bernardbr** [comment]
Thank you @DustinCampbell 
I use only 3 extensions (OmniSharp, jchannon.csharpextensions, and Leopotam.csharpfixformat)
The console error is caused by jchannon.csharpextensions, but the format still "stop" the OmniSharp. I stopped the Leopotam.csharpfixformat extension and apparently the problem as gone.

Thanks for your quick answers and attention!

I'll report @Leopotam about this!

**Comment by DustinCampbell** [comment]
Cool! Thanks for getting to the bottom of this, @bernardbr.
