### ISSUE TITLE
Failed to load omnisharp.json

### ISSUE THREAD

**Issue by troydai** [OmniSharp/omnisharp-vscode#180]
Install the March Insider Build and install `csharp-1.0.0-rc2` extension. Open `omnisharp-roslyn` repo. Got following error messages in OmniSharp output:

```
[INFO] Starting OmniSharp at '/Users/troydai/Code/omnisharp-roslyn'...
[INFO] Started OmniSharp from '/Users/troydai/.vscode-insiders/extensions/ms-vscode.csharp-1.0.1-rc2/.omnisharp/OmniSharp' with process id 53125...
OmniSharp: -s /Users/troydai/Code/omnisharp-roslyn --hostPID 53084 dnx:enablePackageRestore=false --stdio

Unhandled Exception: System.IO.FileNotFoundException: The configuration file '/Users/troydai/Code/omnisharp-roslyn/omnisharp.json' was not found and is not optional.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at OmniSharp.Startup..ctor(IApplicationEnvironment applicationEnvironment)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Startup.StartupLoader.LoadMethods(Type startupType, IList`1 diagnosticMessages)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at OmniSharp.Program.Main(String[] args)
   at Program.Main(String[] args)
[ERROR] Error: Failed to start OmniSharp
```

It was fixed in this commit: https://github.com/OmniSharp/omnisharp-roslyn/commit/0b2666c476452d945b0f2619ce75ac4ea8b87bde. So the extension can pick up a later OmniSharp-roslyn build to fix this one.

**Comment by DustinCampbell** [comment]
This was addressed a long time ago. Sorry I missed the issue!
