### ISSUE TITLE
Error while installing .NET Core Debugger (VSC 0.10.11)

### ISSUE THREAD

**Issue by egamma** [OmniSharp/omnisharp-vscode#183]
_From @maxonico on April 13, 2016 15:7_

- VSCode Version: 0.10.11
- OS Version: Windows 8.1 x64

Can't install the C# debugger.

Steps to Reproduce:

1. Install .NET Core SDK
- 1.1. dotnet --version =  **_1.0.0-rc2-002349_**
2. Create a new dummy project (dotnet new)
3. Restore (dotnet restore)
4. Check build is working, and works (dotnet build)
5. Install VS Code (**_0.10.11_**)
6. Install C# extensions for VSC (open VSC, press F1, type: **_ext install c#,_** press Enter and wait the installer to finish)
7. Restart VSC after C# extensions have been installed
8. In VSC, open a CS file, and check the output window
9. After installing dependencies, you eventually get to the debugger installation, and get a: 

> Error: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win81-x64, win8-x64, win7-x64' in the 'runtimes' section.

This is my project.json file:

`{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002349"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+wp80+win8+win81-x64+win8-x64+wpa81+dnxcore50"
      ]
    }  
  }
}`

and NuGet.config file (root of the project):

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
</configuration>`

And this is my NuGet.config file inside of "Users\%USER%\\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug":

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    
    <clear />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="coreclr-debug" value="https://www.myget.org/F/coreclr-debug/api/v3/index.json" />
  </packageSources>
</configuration>`

Thanks.

_Copied from original issue: Microsoft/vscode#5227_

**Comment by egamma** [comment]
Moving to  omnisharp-vscode for investigation.

**Comment by abrodersen** [comment]
I'm also seeing this issue. My `dotnet --info`:
````
.NET Command Line Tools (1.0.0-rc2-002320)

Product Information:
 Version:     1.0.0-rc2-002320
 Commit Sha:  eb793c5cf8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
````

 Here is my VS Code output:
````
Downloading and configuring the .NET Core Debugger...
log  : Restoring packages for C:\Users\Aaron\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\project.json...
info : Committing restore...
log  : Lock file has not changed. Skipping lock file write. Path: C:\Users\Aaron\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\project.lock.json
log  : C:\Users\Aaron\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\project.json
log  : Restore completed in 3039ms.

NuGet Config files used:
    C:\Users\Aaron\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug\NuGet.config

Feeds used:
    https://www.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/coreclr-debug/api/v3/index.json
Error: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.

System.InvalidOperationException: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
   at Microsoft.DotNet.ProjectModel.ProjectContext.CreateRuntimeContext(IEnumerable`1 runtimeIdentifiers)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.TryPrepareForPublish()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
dotnet exited with error code 1
Error while installing .NET Core Debugger.
````

**Comment by gregg-miskelly** [comment]
The C# extension in the store is not compatible with recent builds of the .NET CLI. See http://aka.ms/vscclrdogfood for instructions.

**Comment by maxonico** [comment]
Indeed, i downloaded the latest from https://github.com/OmniSharp/omnisharp-vscode/releases and it's working like a charm. Thanks.

**Comment by Souk21** [comment]
I'm having the same problem. (MacOS 10.9.5)
I just updated to vsc1.1.1 (from the app itself), also updated C# extension.

I have installed .Net Core and openssl as required.

Since then, at every restart I get this error message and this log :

```
Telemetry is: Enabled
log  : Restoring packages for /Users/username/.vscode/extensions/ms-vscode.csharp-1.0.10/coreclr-debug/project.json...
error: System.IO.Compression 4.1.0-rc2-24027 provides a compile-time reference assembly for System.IO.Compression on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.IO 4.1.0-rc2-24027 provides a compile-time reference assembly for System.IO on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Globalization.Calendars 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Globalization.Calendars on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Globalization 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Globalization on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Diagnostics.Tracing 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Diagnostics.Tracing on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Diagnostics.Tools 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Diagnostics.Tools on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Diagnostics.Debug 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Diagnostics.Debug on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Console 4.0.0-rc2-24027 provides a compile-time reference assembly for System.Console on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Diagnostics.Process 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Diagnostics.Process on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Security.Cryptography.Algorithms 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Security.Cryptography.Algorithms on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: Microsoft.Win32.Primitives 4.0.1-rc2-24027 provides a compile-time reference assembly for Microsoft.Win32.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.AppContext 4.1.0-rc2-24027 provides a compile-time reference assembly for System.AppContext on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Collections 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Collections on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.IO.FileSystem 4.0.1-rc2-24027 provides a compile-time reference assembly for System.IO.FileSystem on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Net.Primitives 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Net.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Net.Sockets 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Net.Sockets on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Reflection 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Reflection on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Reflection.Extensions 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Reflection.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Reflection.Primitives 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Reflection.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Resources.ResourceManager 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Resources.ResourceManager on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Runtime 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Runtime on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Runtime.Extensions 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Runtime.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Runtime.Handles 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Runtime.Handles on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Runtime.InteropServices 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Runtime.InteropServices on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-24027 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Text.Encoding 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Text.Encoding on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Text.Encoding.Extensions 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Text.Encoding.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Threading.Tasks 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Threading.Tasks on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Threading.Timer 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Threading.Timer on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
error: One or more packages are incompatible with .NETStandardApp,Version=v1.5 (osx.10.9-x64).
info : Committing restore...
log  : Lock file has not changed. Skipping lock file write. Path: /Users/username/.vscode/extensions/ms-vscode.csharp-1.0.10/coreclr-debug/project.lock.json
log  : /Users/username/.vscode/extensions/ms-vscode.csharp-1.0.10/coreclr-debug/project.json
log  : Restore failed in 2162ms.
Error: 

Error: Errors in /Users/username/.vscode/extensions/ms-vscode.csharp-1.0.10/coreclr-debug/project.json

Error:     System.IO.Compression 4.1.0-rc2-24027 provides a compile-time reference assembly for System.IO.Compression on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.

Error:     System.IO 4.1.0-rc2-24027 provides a compile-time reference assembly for System.IO on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.

Error:     System.Globalization.Calendars 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Globalization.Calendars on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Globalization 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Globalization on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Diagnostics.Tracing 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Diagnostics.Tracing on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Diagnostics.Tools 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Diagnostics.Tools on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Diagnostics.Debug 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Diagnostics.Debug on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Console 4.0.0-rc2-24027 provides a compile-time reference assembly for System.Console on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Diagnostics.Process 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Diagnostics.Process on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Security.Cryptography.Algorithms 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Security.Cryptography.Algorithms on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    Microsoft.Win32.Primitives 4.0.1-rc2-24027 provides a compile-time reference assembly for Microsoft.Win32.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.AppContext 4.1.0-rc2-24027 provides a compile-time reference assembly for System.AppContext on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Collections 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Collections on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.IO.FileSystem 4.0.1-rc2-24027 provides a compile-time reference assembly for System.IO.FileSystem on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Net.Primitives 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Net.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Net.Sockets 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Net.Sockets on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Reflection 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Reflection on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Reflection.Extensions 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Reflection.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Reflection.Primitives 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Reflection.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Resources.ResourceManager 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Resources.ResourceManager on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Runtime 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Runtime on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Runtime.Extensions 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Runtime.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Runtime.Handles 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Runtime.Handles on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Runtime.InteropServices 4.1.0-rc2-24027 provides a compile-time reference assembly for System.Runtime.InteropServices on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-24027 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Text.Encoding 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Text.Encoding on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Text.Encoding.Extensions 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Text.Encoding.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Threading.Tasks 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Threading.Tasks on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    System.Threading.Timer 4.0.1-rc2-24027 provides a compile-time reference assembly for System.Threading.Timer on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with osx.10.9-x64.
    One or more packages are incompatible with .NETStandardApp,Version=v1.5 (osx.10.9-x64).


NuGet Config files used:
    /Users/username/.vscode/extensions/ms-vscode.csharp-1.0.10/coreclr-debug/NuGet.config

Feeds used:
    https://api.nuget.org/v3/index.json
dotnet exited with error code 1
```

**Comment by gregg-miskelly** [comment]
@Souk21 we have never tried a version of OSX prior to 10.10. I would suggest upgrading if you can.

**Comment by gregg-miskelly** [comment]
@Souk21 thanks!

OSX 10.9 issue now tracked with https://github.com/OmniSharp/omnisharp-vscode/issues/340
