### ISSUE TITLE
Failed to load project file Assembly-CSharp.csproj

### ISSUE THREAD

**Issue by Draknek** [OmniSharp/omnisharp-vscode#1947]
There are a couple of other (closed) issues for this problem, but they're both Linux rather than Windows, and they report success when updating Mono but that hasn't changed anything here.

I've installed the most recent version of Mono from here: http://www.mono-project.com/download/ (5.4.1, 64 bit)

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
```
VS Code version: 1.19.1
C# Extension version: 1.13.1

## Steps to reproduce

Have an existing Unity project, and open a source file in VSCode.

## Expected  behavior

Project opens in VSCode and autocomplete works.

## Actual behavior

Project opens in VSCode and autocomplete does not work. A message appears saying "Some projects have trouble loading. Please review the output for more details."

Output:
```
Starting OmniSharp server at 2018-1-1 14:29:33
    Target: c:\Users\Alan\Documents\dev\cosmic-express\cosmic-express.sln

OmniSharp server started
    Path: C:\Users\Alan\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\OmniSharp.exe
    PID: 3772

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 0 MSBuild instance(s)
[fail]: OmniSharp.CompositionHostBuilder
        Could not locate MSBuild instance to register with OmniSharp
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Alan\Documents\dev\cosmic-express'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\Users\Alan\Documents\dev\cosmic-express
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in 'c:\Users\Alan\Documents\dev\cosmic-express\cosmic-express.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp-firstpass.csproj
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp-firstpass.csproj'.
c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp-firstpass.csproj(1,1)
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String filePath, String solutionDirectory, ILogger logger, MSBuildInstance msbuildInstance, SdksPathResolver sdksPathResolver, MSBuildOptions options, ICollection`1 diagnostics)
   at OmniSharp.MSBuild.MSBuildProjectSystem.LoadProject(String projectFilePath)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp.csproj
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp.csproj'.
c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp.csproj(1,1)
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String filePath, String solutionDirectory, ILogger logger, MSBuildInstance msbuildInstance, SdksPathResolver sdksPathResolver, MSBuildOptions options, ICollection`1 diagnostics)
   at OmniSharp.MSBuild.MSBuildProjectSystem.LoadProject(String projectFilePath)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp-Editor-firstpass.csproj
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp-Editor-firstpass.csproj'.
c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp-Editor-firstpass.csproj(1,1)
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String filePath, String solutionDirectory, ILogger logger, MSBuildInstance msbuildInstance, SdksPathResolver sdksPathResolver, MSBuildOptions options, ICollection`1 diagnostics)
   at OmniSharp.MSBuild.MSBuildProjectSystem.LoadProject(String projectFilePath)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp-Editor.csproj
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp-Editor.csproj'.
c:\Users\Alan\Documents\dev\cosmic-express\Assembly-CSharp-Editor.csproj(1,1)
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String filePath, String solutionDirectory, ILogger logger, MSBuildInstance msbuildInstance, SdksPathResolver sdksPathResolver, MSBuildOptions options, ICollection`1 diagnostics)
   at OmniSharp.MSBuild.MSBuildProjectSystem.LoadProject(String projectFilePath)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Alan\Documents\dev\cosmic-express'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Alan\Documents\dev\cosmic-express' on host 1220.
```

**Comment by rchande** [comment]
@DustinCampbell Any idea why we would fail to load Microsoft.Build 15.1.0.0?

**Comment by Draknek** [comment]
No, that path doesn't exist - I have no `msbuild` directory in `.omnisharp`.

Should I try uninstalling and reinstalling the C# extension?

**Comment by DustinCampbell** [comment]
Yes, it seems like something is definitely broken. I recommend uninstalling and reinstalling. Let me know if that folder is still missing.

**Comment by Draknek** [comment]
Didn't get around to trying this until today (I only code occasionally). I went to uninstall/reinstall and saw that there was an update, after updating to 1.14.0 everything works again.

Seems very likely that uninstalling/reinstalling would also have worked! Thanks for the assistance.

**Comment by DustinCampbell** [comment]
Glad to hear it -- thanks for the update!
