### ISSUE TITLE
Intellisense not working in web api project

### ISSUE THREAD

**Issue by mmccoy173** [OmniSharp/omnisharp-vscode#1975]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

VS Code version:
Version 1.19.2

C# Extension version: 
1.13.1

## Steps to reproduce
`mkdir my-app`
`cd my-app`
`dotnet new webapi`
`code .`

OmniSharp log says: Omnisharp server running using Stdio at location '(my location)' on host 7432. I've tried re-installing the extension, no luck.

## Expected  behavior
Creating string in any .cs file (Startup.cs for example) should provide intellisense.

## Actual behavior
No intellisense and CTRL-Space displaying Loading... forever.

`string foo = "123";`
`foo.` displays nothing and CTRL-Space gives me Loading... forever.
Opening developer tools I see some errors related to OmniSharp: 
[Extension Host] rejected promise not handled within 1 second
[ms-vscode.csharp]Pending request cancelled: /codecheck

**Comment by rchande** [comment]
@mmccoy173 Could you share your full omnisharp log?

**Comment by mmccoy173** [comment]
@rchande Here you go. Thanks.
````
Starting OmniSharp server at 1/24/2018, 8:41:23 AM
    Target: c:\svn\my-app

OmniSharp server started
    Path: C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\OmniSharp.exe
    PID: 3272

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.1.7601.65536 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2017 15.5.27130.2024 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\.omnisharp\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2017 15.5.27130.2024 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\svn\my-app'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in c:\svn\my-app
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        No solution files found in 'c:\svn\my-app'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project: c:\svn\my-app\my-app.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: my-app
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\svn\my-app'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\svn\my-app' on host 5552.
````

**Comment by mmccoy173** [comment]
Here's some more info from Developer Tools. 

I also cannot start debugging. Pressing F5 gives me a list of templates, when I pick .NET Core from the list, it disappears and nothing happens.

````
 ERR This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:305:12)
	at OmniSharpServer._makeRequest (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\server.js:444:35)
	at RequestQueue.__dirname.constructor.reporter._requestQueue.requestQueue_1.RequestQueueCollection.request [as _makeRequest] (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\server.js:62:99)
	at RequestQueue.processPending (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\requestQueue.js:73:29)
	at RequestQueueCollection.drain (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\requestQueue.js:129:31)
	at RequestQueueCollection.enqueue (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\requestQueue.js:102:14)
	at __dirname.makeRequest.Promise (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\server.js:322:32)
	at Promise (<anonymous>)
	at OmniSharpServer.makeRequest (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\server.js:314:23)
	at Object.typeLookup (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\utils.js:73:19)
console.ts:123 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
mainThreadExtensionService.ts:43 [ms-vscode.csharp]Pending request cancelled: /codecheck
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e.invoke @ abstractThreadService.ts:42
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
mainThreadExtensionService.ts:44 Error: Pending request cancelled: /codecheck
	at RequestQueue.cancelRequest (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\requestQueue.js:44:29)
	at RequestQueueCollection.cancelRequest (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\requestQueue.js:110:15)
	at __dirname.makeRequest.token.onCancellationRequested (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\omnisharp\server.js:326:36)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:218)
	at e.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:92:508)
	at e.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:93:126)
	at DiagnosticsProvider._validateDocument (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\features\diagnosticsProvider.js:147:44)
	at DiagnosticsProvider._onDocumentAddOrChange (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\features\diagnosticsProvider.js:122:18)
	at DiagnosticsProvider.abstractProvider_1.default.constructor.vscode.workspace.onDidChangeTextDocument.event (C:\Users\mmccoy\.vscode\extensions\ms-vscode.csharp-1.13.1\out\src\features\diagnosticsProvider.js:100:73)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:238)
````

**Comment by mmccoy173** [comment]
Turns out it was some privilege management software on my work machine blocking access to omnisharp.

**Comment by rchande** [comment]
Glad you were able to figure it out @mmccoy173.

**Comment by mmccoy173** [comment]
The problem was caused by some third party software installed on my work
machine, was blocking access to OmniSharp. Privilege Guard.
