### ISSUE TITLE
Error: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'osx.10.11-x64'. 

### ISSUE THREAD

**Issue by alexlau811** [OmniSharp/omnisharp-vscode#219]
I have installed C# extension 0.3.7 with VS Code 1.0.0 on my Mac OS X El Capitan with latest .NET Core build (1.0.0-rc2-002426). The debugger cannot be installed.

```
Error: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'osx.10.11-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'osx.10.11-x64' in the 'runtimes' section.
Error: 

System.InvalidOperationException: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'osx.10.11-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'osx.10.11-x64' in the 'runtimes' section.
   at Microsoft.DotNet.ProjectModel.ProjectContext.CreateRuntimeContext(IEnumerable`1 runtimeIdentifiers)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.TryPrepareForPublish()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
dotnet exited with error code 1
Error while installing .NET Core Debugger.
```

I have found a workaround by add below lines in the ~/.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug/project.json

```
    "runtimes": {
      "osx.10.11-x64": { }
    },
```

Not sure if there will be any side effects.

**Comment by BeelzeBu** [comment]
No it doesn't but you need to add this into your own project.json not the omnisharp project.

**Comment by gregg-miskelly** [comment]
The public version of the C# extension doesn't support newer builds of the .NET CLI. For full instruction for working with newer builds of the .NET CLI, see http://aka.ms/vscclrdogfood.
