### ISSUE TITLE
'Comment' in project.json file causes VS Code extension to fail at startup

### ISSUE THREAD

**Issue by jeffschwMSFT** [OmniSharp/omnisharp-vscode#226]
First, yes I know // is not a valid entry for project.json, it is really only there because I was quickly looking for a way to experiment with removing something.  It turns out that dotnet-cli respected the comment (or at least did not die).

project.json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002359"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
  // comment
  "runtimes" : {
    "osx.10.11-x64" : {}
  }
}

Open the folder with this file...

[ERROR:OmniSharp.Startup] The project system 'DotNetProjectSystem' threw exception during initialization.
Illegal character '/' (Unicode hexadecimal 002F).
   at Microsoft.DotNet.ProjectModel.ProjectReader.TryGetProject(String path, Project& project, ICollection`1 diagnostics, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.WorkspaceContext.AddProjectEntry(String projectDirectory, FileModelEntry`1 currentEntry)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Microsoft.DotNet.ProjectModel.WorkspaceContext.Refresh()
   at Microsoft.DotNet.ProjectModel.WorkspaceContext.CreateFrom(String projectPath)
   at OmniSharp.DotNet.DotNetProjectSystem.Initalize(IConfiguration configuration)
   at OmniSharp.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOmnisharpAssemblyLoader loader, IOptions`1 optionsAccessor)

At this point no language services work.  My recommendation is to ensure that this does not cause the language service to die at startup, but rather handle it.  

C# Extension 1.0.3-rc2

**Comment by DustinCampbell** [comment]
@troydai -- this looks like an issue for omnisharp-roslyn.

**Comment by troydai** [comment]
It is actuall

**Comment by troydai** [comment]
@jeffschwMSFT @DustinCampbell  this is actually beyond omnisharp-roslyn. `dotnet-cli` inherits the code for parsing project.json from the original DNX. we (actually

**Comment by troydai** [comment]
Thanks @DustinCampbell 

@jeffschwMSFT yes, omnisharp-roslyn can do a better job to handle this error. I'll open an issue in omnisharp-roslyn repo to track this bug.

Some back ground: this is actually beyond omnisharp-roslyn. `dotnet-cli` inherits the code for parsing project.json from the original `DNX`. We (actually me) wrote a customized json deserializer for `DNX` to replace JSON.NET to achieving greater performance. We made a decision back then that the deserializer will follow strict JSON schema therefore reject comments in JSON. If it does make your work harder, ma

**Comment by troydai** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/issues/535

**Comment by DustinCampbell** [comment]
Bug is refiled over in omnisharp-roslyn repo.
