### ISSUE TITLE
0.3.7 fails to install on Ubuntu 14.04

### ISSUE THREAD

**Issue by andschwa** [OmniSharp/omnisharp-vscode#241]
This is a regression, as it definitely previously worked. I've upgraded to VS Code 1.0 and was reinstalling extensions:

```
Installed:
    84 package(s) to /home/andrew/.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug/project.json
Error: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'ubuntu.14.04-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'ubuntu.14.04-x64' in the 'runtimes' section.
Error: 

System.InvalidOperationException: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'ubuntu.14.04-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'ubuntu.14.04-x64' in the 'runtimes' section.
   at Microsoft.DotNet.ProjectModel.ProjectContext.CreateRuntimeContext(IEnumerable`1 runtimeIdentifiers)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.TryPrepareForPublish()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass71_0.<Run>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)
dotnet exited with error code 1
Error while installing .NET Core Debugger.
```

Using:
```
$ dotnet --info
.NET Command Line Tools (1.0.0-rc2-002439)

Product Information:
 Version:     1.0.0-rc2-002439
 Commit Sha:  ef0c3b2cee

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by andschwa** [comment]
Doesn't repro with 1.0.3-rc2.
