### ISSUE TITLE
command 'csharp.coreclrAdapterExecutableCommand' not found

### ISSUE THREAD

**Issue by sgentile** [OmniSharp/omnisharp-vscode#2437]
When trying to debug inside of Visual Code I get this error:

command 'csharp.coreclrAdapterExecutableCommand' not found

> 
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by gregg-miskelly** [comment]
So what this means is that VS Code is somehow failing to find the command from the C# extension.

If you open a .cs file first, do you still see it?
If you go to the command pallet, do you see other C# extension commands (ex: '.NET: Generate Assets for Build and Debug)

If you don't see any C# extension commands, you might try uninstalling and reinstalling the C# extension. We had one previous customer run into this problem, and that fixed it for them.

**Comment by Excited-ccccly** [comment]
I also have this problem on my Antergos. I have tried to reinstall C# extension, but it still won't download the ominisharp and nearly every command is not found.

Then I reopened vscode with **--inspect-extensions** flag, and in the developer tools, I  found this error.


```
[Extension Host] Activating extension `ms-vscode.csharp` failed:  Cannot find module './symbol/rxSubscriber'
t.log @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:270
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] Here is the error stack:  Error: Cannot find module './symbol/rxSubscriber'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.t._load (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/opt/visual-studio-code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
```

Btw, I am using [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) extension. And all extensions and user settings are synced from another computer. I don't know whether it matters.

**Comment by MaxIakovliev** [comment]
Experiencing  exactly  same issue.
command 'csharp.coreclrAdapterExecutableCommand' not found

here is output of 
`dotnet --info` :
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

I created  .NetCore project using:
`dotnet new console`
`dotnet new restore`

By pressing `Ctrl+Shift+B` it prompts "No build task to run found. Configure Build Task"
 -> "create task.json from template ->.Net Core (Execute .Net Core build command) -> it creates task.json:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet build",
            "type": "shell",
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}
```

However -Debug option still does not work.
When I press `F5`  - no .Net Debugger available in the list 👎 . 
I added launch.json file manually under the .vscode folder.

When I open launch.json file- it shows "Add Configuration" button that  does nothing.
How can I fix it?

**Comment by gregg-miskelly** [comment]
@Excited-ccccly do you still install your extensions to the standard location (~/.vscode/extensions)?
Does `~/.vscode/extensions/ms-vscode.csharp-1.15.2/node_modules/rxjs/symbol/rxSubscriber.js` exist on your computer?

**Comment by gregg-miskelly** [comment]
@MaxIakovliev if you uninstall and reinstall the C# extension, does the problem still happen for you?

**Comment by Excited-ccccly** [comment]
@gregg-miskelly No, it doesn't exsit.

```zsh
➜  ~ ls ~/.vscode/extensions/ms-vscode.csharp-1.15.2/node_modules/rxjs/symbol
iterator.d.ts
```

Then I execute `npm install` in `~/.vscode/extensions/ms-vscode.csharp-1.15.2/node_modules/rxjs` folder. After installation, `rxSubscriber.js` still doesn't exist. 

I have also tried to init another npm project and install rxjs as a dependency. The `rxSubscriber.js` exsits in this newly created project.

**Comment by Excited-ccccly** [comment]
@gregg-miskelly  I have delete `ms-vscode.csharp-1.15.2` manually, and reinstall the c# extension. It works!

**Comment by floreseken** [comment]
Reinstalling the c# extension from the UI fixed it for me..

**Comment by nimrodavid** [comment]
I just got this error, pretty sure after VS Code updated itself. 
After reading the comments here I tried to uninstall and then reinstall the C# extension (In my case it's version 1.16.1), but that didn't help. I then went on to check if I had the file `~/.vscode/extensions/ms-vscode.csharp-1.16.1/node_modules/rxjs/symbol/rxSubscriber.js`, and notices that although the file exists, it is completely empty. Lastly, after trying reinstalling again, I noticed that my `~/.vscode/extensions/ms-vscode.csharp-1.16.1` directory wasn't actually being removed when I uninstalled the extension.

So finally, the solution that worked for me -
* Uninstall C# extnesion
* Manually delete extension directory from `~/.vscode/extensions/`
* Reinstall the extension

Hope this might help someone

**Comment by hnviradiya** [comment]
@nimrodolev I think if this is not added as bug, then you should raise this.
