### ISSUE TITLE
'sourceReference' is missing

### ISSUE THREAD

**Issue by isidorn** [OmniSharp/omnisharp-vscode#248]
* debugged a C# app that uses Tasks
* found exception in the dev tools console
* I believe this error is coming from the C# debug adapter
* the newest vscode should always send a sourceReference when it is available, when do you exactly throw this error? 

```
//Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:117 
source: property 'sourceReference' is missing: Error: source: property 'sourceReference' is missing
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:17181
    at Object.p [as _notify] (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:22802)
    at Object.__dirname.undefined.F.enter (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:26130)
    at __dirname.undefined.t.Class.define._run (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:27451)
    at __dirname.undefined.t.Class.define._error (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:23:26968)
    at file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:12410
    at t.e.dispatch (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:13482)
    at t.e.handleData (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:13006)
    at Socket.<anonymous> (file:////Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:12276)
    at emitOne (events.js:90:13)e.onUnexpectedError @ //Applications/Visual Studio Code - Alpha.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:117
winjs.base.js:47WARNING: Promise with no error callback:undefined
```

**Comment by gregg-miskelly** [comment]
This looks like a problem with VS Code rather that the debug adapter. Here is the code:

        public virtual DebugResult Dispatch(string command, dynamic args)
        {
            int thread;

            switch (command)
            {
   ...
                case "source":
                    int sourceRef = GetInt(args, "sourceReference", -1);
                    if (sourceRef == -1)
                    {
                        return new DebugResult(1010, "source: property 'sourceReference' is missing");
                    }
                    return Source(sourceRef).Result;

Notes:
1. The C# debug adapter never uses source references. So it is probably a bug to ever send us that command.
2. This code came from the VS Code team and we have never touched it.
