### ISSUE TITLE
Red OmniSharp flame icon in status bar with "OmniSharp process errored:" tooltip (1.16.1)

### ISSUE THREAD

**Issue by zvinless** [OmniSharp/omnisharp-vscode#2521]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.402/

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.402 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version: 1.27.1
C# Extension version: 1.16.1

## Steps to reproduce
1. Create a new project: `dotnet new console`
1. Open containing folder with Visual Studio Code
1. Observe that the OmniSharp Log appears in the OUTPUT pane and focuses itself automatically (happens every time I open a C# project since 1.16.0)
1. Observe that the OmniSharp flame icon in the taskbar is red instead of green
1. Mouse over the icon and observe "OmniSharp process errored:" tooltip
1. Observe that there are no errors in the output from step 3

## Expected  behavior
The extension should load normally without opening the OUTPUT pane in VS Code. The OmniSharp flame icon should be green as it was prior to version 1.16.0.

## Actual behavior
<img width="254" alt="statusbar" src="https://user-images.githubusercontent.com/24303763/45467069-98569a80-b6d2-11e8-9be4-76219dca35c8.png">

Upon loading a C# project, the OUTPUT pane opens up with the message (this is with log level set to "debug"; usually I have it set to "critical" and it still focuses itself upon opening a project):
```
Starting OmniSharp server at 9/12/2018, 9:19:49 PM
    Target: /Users/zach/Desktop/OmniTest

OmniSharp server started with Mono 5.14.0.
    Path: /Users/zach/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/OmniSharp.exe
    PID: 62698

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.13.6 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/usr/local/Cellar/mono/5.14.0.177/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/zach/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/usr/local/Cellar/mono/5.14.0.177/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/zach/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/zach/Desktop/OmniTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/zach/Desktop/OmniTest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/zach/Desktop/OmniTest/OmniTest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/zach/Desktop/OmniTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/zach/Desktop/OmniTest' on host 62678.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/zach/Desktop/OmniTest/OmniTest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/zach/Desktop/OmniTest/OmniTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/zach/Desktop/OmniTest/OmniTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: OmniTest
```
and the OmniSharp flame icon in the status bar is red. The plugin features generally seem to work fine, though.

**Comment by rchande** [comment]
@zvinless @ru-ace Thanks for filing this--we believe this is caused by our omnisharp error detector spuriously detecting an error. I suspect omnisharp features are still working for you despite the red flame? 
cc @akshita31

**Comment by zvinless** [comment]
@rchande, yeah, the plugin features are all good!

**Comment by ru-ace** [comment]
@zvinless, yes - plugin works fine.

**Comment by megaDRONe86** [comment]
Yep same to me. I see it under Unity project.

**Comment by CodySchrank** [comment]
Yep same for me.  The plugin still works as expected though.

**Comment by monyarm** [comment]
I have this same issue however, in my case it seems to break omnisharp, it doesn't want to build my project anymore, this is my log:
```
Starting OmniSharp server at 9/18/2018, 1:35:29 AM
    Target: /home/monyarm/Documents/Amicitia/Source/Amicitia.sln

OmniSharp server started with Mono 5.14.0.
    Path: /home/monyarm/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/OmniSharp.exe
    PID: 32579

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 17.10 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/home/monyarm/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            CscToolPath = /home/monyarm/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/monyarm/Documents/Amicitia/Source'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/monyarm/Documents/Amicitia/Source/Amicitia.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/monyarm/Documents/Amicitia/Source/AmicitiaLibrary/AmicitiaLibrary.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/monyarm/Documents/Amicitia/Source/Amicitia/Amicitia.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/monyarm/Documents/Amicitia/Source/Commandline tools/bvptool/bvptool.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/monyarm/Documents/Amicitia/Dependencies/AtlusFileSystemLibrary/Source/AtlusFileSystemLibrary/AtlusFileSystemLibrary.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/monyarm/Documents/Amicitia/Source'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/monyarm/Documents/Amicitia/Source' on host 29054.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/monyarm/Documents/Amicitia/Source/AmicitiaLibrary/AmicitiaLibrary.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/monyarm/Documents/Amicitia/Source/AmicitiaLibrary/AmicitiaLibrary.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/monyarm/Documents/Amicitia/Source/AmicitiaLibrary/AmicitiaLibrary.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/monyarm/Documents/Amicitia/Source/Amicitia/Amicitia.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/monyarm/Documents/Amicitia/Source/Amicitia/Amicitia.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/monyarm/Documents/Amicitia/Source/Amicitia/Amicitia.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/monyarm/Documents/Amicitia/Source/Commandline tools/bvptool/bvptool.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/monyarm/Documents/Amicitia/Source/Commandline tools/bvptool/bvptool.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/monyarm/Documents/Amicitia/Source/Commandline tools/bvptool/bvptool.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/monyarm/Documents/Amicitia/Dependencies/AtlusFileSystemLibrary/Source/AtlusFileSystemLibrary/AtlusFileSystemLibrary.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/monyarm/Documents/Amicitia/Dependencies/AtlusFileSystemLibrary/Source/AtlusFileSystemLibrary/AtlusFileSystemLibrary.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/monyarm/Documents/Amicitia/Dependencies/AtlusFileSystemLibrary/Source/AtlusFileSystemLibrary/AtlusFileSystemLibrary.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: AmicitiaLibrary
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Amicitia
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: bvptool
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: AtlusFileSystemLibrary
```

While if i delete my build folder and try again, then i get it:
```
Starting OmniSharp server at 9/18/2018, 1:38:53 AM
    Target: /home/monyarm/Documents/Amicitia/Source/Amicitia.sln

OmniSharp server started with Mono 5.14.0.
    Path: /home/monyarm/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/OmniSharp.exe
    PID: 1095

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 17.10 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/home/monyarm/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            CscToolPath = /home/monyarm/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/monyarm/Documents/Amicitia/Source'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/monyarm/Documents/Amicitia/Source/Amicitia.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/monyarm/Documents/Amicitia/Source/AmicitiaLibrary/AmicitiaLibrary.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/monyarm/Documents/Amicitia/Source/Amicitia/Amicitia.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/monyarm/Documents/Amicitia/Source/Commandline tools/bvptool/bvptool.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/monyarm/Documents/Amicitia/Dependencies/AtlusFileSystemLibrary/Source/AtlusFileSystemLibrary/AtlusFileSystemLibrary.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/monyarm/Documents/Amicitia/Source'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/monyarm/Documents/Amicitia/Source' on host 29054.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/monyarm/Documents/Amicitia/Source/AmicitiaLibrary/AmicitiaLibrary.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/monyarm/Documents/Amicitia/Source/AmicitiaLibrary/AmicitiaLibrary.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/monyarm/Documents/Amicitia/Source/AmicitiaLibrary/AmicitiaLibrary.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/monyarm/Documents/Amicitia/Source/Amicitia/Amicitia.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/monyarm/Documents/Amicitia/Source/Amicitia/Amicitia.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/monyarm/Documents/Amicitia/Source/Amicitia/Amicitia.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/monyarm/Documents/Amicitia/Source/Commandline tools/bvptool/bvptool.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/monyarm/Documents/Amicitia/Source/Commandline tools/bvptool/bvptool.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/monyarm/Documents/Amicitia/Source/Commandline tools/bvptool/bvptool.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/monyarm/Documents/Amicitia/Dependencies/AtlusFileSystemLibrary/Source/AtlusFileSystemLibrary/AtlusFileSystemLibrary.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/monyarm/Documents/Amicitia/Dependencies/AtlusFileSystemLibrary/Source/AtlusFileSystemLibrary/AtlusFileSystemLibrary.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/monyarm/Documents/Amicitia/Dependencies/AtlusFileSystemLibrary/Source/AtlusFileSystemLibrary/AtlusFileSystemLibrary.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: AmicitiaLibrary
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Amicitia
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/home/monyarm/Documents/Amicitia/Build/Debug/AmicitiaLibrary.dll'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: bvptool
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/home/monyarm/Documents/Amicitia/Build/Debug/AmicitiaLibrary.dll'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: AtlusFileSystemLibrary
```

Right now i'm forced to delete my build folder, then run monodevelop, and have it build my project

**Comment by jtsom** [comment]
I'm seeing the red flame also, but I Cannot launch apps with the VS Code debugger: https://github.com/Microsoft/vscode/issues/58847

Not sure if it's related.

**Comment by gleip** [comment]
Same problem
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19
 OS Platform: Linux
 RID:         linuxmint.19-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.402/

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by akshita31** [comment]
@monyarm  The issue here is just that the OmniSharp flame is red despite of the fact that all IDE features work. Can you file a new issue with specific repro steps ?

**Comment by argentini** [comment]
> @zvinless @ru-ace Thanks for filing this--we believe this is caused by our omnisharp error detector spuriously detecting an error. I suspect omnisharp features are still working for you despite the red flame?
> cc @akshita31

Not for me. On macOS Mojave I get the red flame as well but my Console app project won't debug any more. It starts to run the app and locks up, truncating the console output. I can't pause it but I can stop it. When I run the project on Visual Studio Code for Windows (same version) I get the green flame icon and a functional debugging session. So I think this is more than simply an erroneous alert.

**Comment by akshita31** [comment]
The beta with the fix for the red OmniSharp flame is out: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.17.0-beta1. Please give it a try.

**Comment by jtsom** [comment]
Yeah, that made things worse. The C# extension isn't loading at all now:

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:281 [Extension Host] Activating extension 'ms-vscode.csharp' failed: Cannot find module 'strip-bom'. (at Object.showMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:614:509))
t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:281
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:281 [Extension Host] Activating extension `ms-vscode.csharp` failed:  Cannot find module 'strip-bom' (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:291:583)
t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:281
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:281 [Extension Host] Here is the error stack:  Error: Cannot find module 'strip-bom'
	at Function.Module._resolveFilename (module.js:543:15)
	at Function.Module._load (module.js:473:25)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:648:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:592:300)
	at Module.require (module.js:586:17)
	at Module.require (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:113692)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/Users/johntsombakos/.vscode-insiders/extensions/ms-vscode.csharp-1.16.1/out/src/utils/removeBOM.js:8:25)
	at Object.<anonymous> (/Users/johntsombakos/.vscode-insiders/extensions/ms-vscode.csharp-1.16.1/out/src/utils/removeBOM.js:18:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:648:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:592:300)
	at Module.require (module.js:586:17)
	at Module.require (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:113692)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/Users/johntsombakos/.vscode-insiders/extensions/ms-vscode.csharp-1.16.1/out/src/omnisharp/server.js:33:21)
	at Object.<anonymous> (/Users/johntsombakos/.vscode-insiders/extensions/ms-vscode.csharp-1.16.1/out/src/omnisharp/server.js:519:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:648:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:592:300)
	at Module.require (module.js:586:17)
	at Module.require (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:113692)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/Users/johntsombakos/.vscode-insiders/extensions/ms-vscode.csharp-1.16.1/out/src/omnisharp/extension.js:31:18)
	at Object.<anonymous> (/Users/johntsombakos/.vscode-insiders/extensions/ms-vscode.csharp-1.16.1/out/src/omnisharp/extension.js:164:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:648:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:592:300)
	at Module.require (module.js:586:17)
	at Module.require (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:113692)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (/Users/johntsombakos/.vscode-insiders/extensions/ms-vscode.csharp-1.16.1/out/src/main.js:15:19)
	at Object.<anonymous> (/Users/johntsombakos/.vscode-insiders/extensions/ms-vscode.csharp-1.16.1/out/src/main.js:147:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:648:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:592:300)
	at Module.require (module.js:586:17)
	at Module.require (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:113692)
	at require (internal/module.js:11:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:31:146)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:617:969
	at t._doActivateExtension (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:618:84)
	at t._activateExtension (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:616:854)
	at Object.actualActivateExtension (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:614:641)
	at e._activateExtension (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:291:446)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:291:65
	at Array.map (<anonymous>)
	at e._activateExtensions (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:291:40)
	at e.activateByEvent (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:289:321)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:615:126
	at Object.g [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:78:971)
	at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:277)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:100)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:559)
	at e.open (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:637)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:614:679
	at Object.g [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:78:971)
	at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:277)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:100)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:559)
	at c (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:1011)
	at K.then.o.(anonymous function) (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:87:205)
	at Object.g [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:78:971)
	at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:82:277)
	at n.Class.derive._oncancel._run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:100)
	at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:559)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:114:1006
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:73
	at LOOP (original-fs.js:1757:14)
	at _combinedTickCallback (internal/process/next_tick.js:131:7)
	at process._tickCallback (internal/process/next_tick.js:180:9) (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:291:651)
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3322 Activating extension 'ms-vscode.csharp' failed: Cannot find module 'strip-bom'.
```

**Comment by bjornharrtell** [comment]
@akshita31, the asset on the 1.17.0-beta1 release is https://github.com/OmniSharp/omnisharp-vscode/releases/download/v1.17.0-beta1/csharp-1.16.1.vsix - that doesn't seem right?

**Comment by akshita31** [comment]
@jtsom @bjornharrtell Apologies that didn't work. Seems there is an issue wth missing dependency. I am investigating further.

**Comment by estebanrao** [comment]
![image](https://user-images.githubusercontent.com/601031/45852333-a54c3d00-bd15-11e8-89f9-3edfbe012ba6.png)
<3

**Comment by argentini** [comment]
The flame is indeed green, but I still can't debug my console app any more. It runs and freezes. Cannot pause debugger. When I stop it I can't debug again because the pdb files are in-use and can't be overwritten during the build. This happens in macOS High Sierra and Mojave.

**Comment by akshita31** [comment]
@argentini Can you file a new issue with the relevant information about your system and the project you are working with ?
