### ISSUE TITLE
Omnisharp InvalidProjectFileException not fixed by 1.16.1

### ISSUE THREAD

**Issue by Ghostbird** [OmniSharp/omnisharp-vscode#2529]
**Note:** This is probably related to #2509. I was [asked](https://github.com/OmniSharp/omnisharp-vscode/issues/2509#issuecomment-421052575) by @rchande to report this specific case as a new issue, since the 1.16.1 release did fix the issue for most people, but not for me. Installing version 1.15.2 of the extension does not give the problem.

## Environment data
`uname -a` output:
```
Linux gijsbertdebian 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
```
`dotnet --info` output:.
```
NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.402/

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version:
```
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64
```
C# Extension version: 1.16.1

## Steps to reproduce
Open project folder

## Expected  behavior
Project loads, Omnisharp works

## Actual behavior
Project loads, Omnisharp throws InvalidProjectFileException (for every project file in the project)
Omnisharp functionality does not initialise and cannot be used.

## Omnisharp log
**Note:** This is a slightly sanitised version of the log, I have 5 sub-projects that throw the identical error. I reduced this to just one sub-project `Project.T` in this log.

```
Starting OmniSharp server at 14/09/2018, 10:06:44
    Target: /home/user/workspace/Project/Project.sln

OmniSharp server started.
    Path: /home/user/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/run
    PID: 7928

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on debian 9.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "/home/user/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/user/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "/home/user/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin"
            MSBuildExtensionsPath = /home/user/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild
            BypassFrameworkInstallChecks = true
            CscToolPath = /home/user/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/user/.vscode/extensions/ms-vscode.csharp-1.16.1/.omnisharp/1.32.5/omnisharp/msbuild/15.0/Bin
            TargetFrameworkRootPath = /usr/lib/mono/xbuild-frameworks
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/user/workspace/Project'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/user/workspace/Project/Project.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/user/workspace/Project/Project.T/Project.T.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/user/workspace/Project'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/user/workspace/Project' on host 7621.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/user/workspace/Project/Project.T/Project.T.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/user/workspace/Project/Project.T/Project.T.csproj'.
/home/user/workspace/Project/Project.T/Project.T.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.  /home/user/workspace/Project/Project.T/Project.T.csproj
  at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject (System.String errorSubCategoryResourceName, Microsoft.Build.Shared.IElementLocation elementLocation, System.String resourceName, System.Object[] args) [0x00040] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1] (System.Boolean condition, System.String errorSubCategoryResourceName, Microsoft.Build.Shared.IElementLocation elementLocation, System.String resourceName, T1 arg0) [0x00003] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1] (Microsoft.Build.Shared.IElementLocation elementLocation, System.String resourceName, T1 arg0) [0x00000] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].ExpandAndLoadImportsFromUnescapedImportExpressionConditioned (System.String directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement, System.Collections.Generic.List`1[Microsoft.Build.Construction.ProjectRootElement]& projects, System.Boolean throwOnFileNotExistsError) [0x00254] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].ExpandAndLoadImports (System.String directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement) [0x00024] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].EvaluateImportElement (System.String directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement) [0x0000d] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].PerformDepthFirstPass (Microsoft.Build.Construction.ProjectRootElement currentProjectOrImport) [0x000e6] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].Evaluate (Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Framework.BuildEventContext buildEventContext) [0x00103] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Evaluator`4[P,I,M,D].Evaluate (Microsoft.Build.Evaluation.IEvaluatorData`4[P,I,M,D] data, Microsoft.Build.Construction.ProjectRootElement root, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, System.Int32 maxNodeCount, Microsoft.Build.Collections.PropertyDictionary`1[T] environmentProperties, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Evaluation.IItemFactory`2[S,T] itemFactory, Microsoft.Build.Evaluation.IToolsetProvider toolsetProvider, Microsoft.Build.Evaluation.ProjectRootElementCache projectRootElementCache, Microsoft.Build.Framework.BuildEventContext buildEventContext, Microsoft.Build.Execution.ProjectInstance projectInstanceIfAnyForDebuggerOnly, Microsoft.Build.BackEnd.SdkResolution.ISdkResolverService sdkResolverService, System.Int32 submissionId, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) [0x0001a] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Project.Reevaluate (Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings) [0x0004c] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary (Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings) [0x00034] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary (Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation) [0x00000] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary (Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) [0x00023] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Project.Initialize (System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion, System.String subToolsetVersion, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) [0x00126] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Project..ctor (System.String projectFile, System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion, System.String subToolsetVersion, Microsoft.Build.Evaluation.ProjectCollection projectCollection, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, Microsoft.Build.Evaluation.Context.EvaluationContext evaluationContext) [0x0009e] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Project..ctor (System.String projectFile, System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion, System.String subToolsetVersion, Microsoft.Build.Evaluation.ProjectCollection projectCollection, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings) [0x00000] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Project..ctor (System.String projectFile, System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion, Microsoft.Build.Evaluation.ProjectCollection projectCollection, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings) [0x00000] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.Project..ctor (System.String projectFile, System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion, Microsoft.Build.Evaluation.ProjectCollection projectCollection) [0x00000] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.ProjectCollection.LoadProject (System.String fileName, System.Collections.Generic.IDictionary`2[TKey,TValue] globalProperties, System.String toolsVersion) [0x000f5] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at Microsoft.Build.Evaluation.ProjectCollection.LoadProject (System.String fileName, System.String toolsVersion) [0x00000] in <2338fdb301034c1d9c6b95e564d514b0>:0 
  at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore (System.String filePath) [0x0003e] in <99f3a3b619ce4010a7d6d489ffd5bcf1>:0 
  at OmniSharp.MSBuild.ProjectLoader.BuildProject (System.String filePath) [0x0000d] in <99f3a3b619ce4010a7d6d489ffd5bcf1>:0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load (System.String filePath, OmniSharp.MSBuild.ProjectLoader loader) [0x00015] in <99f3a3b619ce4010a7d6d489ffd5bcf1>:0 
  at OmniSharp.MSBuild.ProjectManager+<>c__DisplayClass25_0.<LoadProject>b__0 () [0x00000] in <99f3a3b619ce4010a7d6d489ffd5bcf1>:0 
  at (wrapper delegate-invoke) System.Func`1[System.ValueTuple`3[OmniSharp.MSBuild.ProjectFile.ProjectFileInfo,System.Collections.Immutable.ImmutableArray`1[OmniSharp.MSBuild.Logging.MSBuildDiagnostic],OmniSharp.MSBuild.Notification.ProjectLoadedEventArgs]].invoke_TResult()
  at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject (System.String projectFilePath, System.Func`1[TResult] loader) [0x0001b] in <99f3a3b619ce4010a7d6d489ffd5bcf1>:0
 
[fail]: OmniSharp.MSBuild.ProjectManager
      Attemped to update project that is not loaded: /home/gijsbert/workspace/Project/Project.T/Project.T.csproj
```

**Comment by anorborg** [comment]
I this this is also related to #2514. I have instructions to downgrading in the Workaround which works for me in the mean time

**Comment by rchande** [comment]
@Ghostbird Thanks for taking the time to file this--I agree with @anorborg that it's related to #2514. I would recommend downgrading to 1.15.2 while we investigate.

**Comment by SebastianPfliegel** [comment]
Got the same issue. I'm running Windows 10 and .Net Core SDK 2.1.402. Downgrading did the trick for me as well 👍

**Comment by rchande** [comment]
@Ghostbird I think installing mono 5.14.0 fixed this for @anorborg. Could you give that a try?

**Comment by Ghostbird** [comment]
@rchande Debian will probably be on Mono 4.6.x for a while still, but I installed the latest stable Mono from their apt repositories (`deb https://download.mono-project.com/repo/debian stable-stretch main`).

With the newer Mono version, the problem is gone. I wonder why the extension only works with the newer Mono.

**Comment by neumartin** [comment]
Hi! 
In Debian 9.5 I remove the official mono repository, remove all mono packages and all fixed after do that!

**Comment by Ghostbird** [comment]
Well, this just took a turn for the worse.
Mono was updated to version 5.16.0.179, and now the bug mentioned here is back with version 1.16.2 of the extension.
A downgrade to version 1.15.2 is no longer a workaround though. In mono 5.16.0.179 that one crashes with:
```
System.TypeLoadException:
Could not load type of field 'OmniSharp.MSBuild.ProjectManager:_queue' (9) due to:
Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.5.24.0,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```
So I guess I'll go back to the Debian default Mono 4.6.x and version 1.15.2 of this extension, since that's the only remaining option that works, without having to do annoying stuff like partially locking down my system packages to specific versions.

**Comment by Ghostbird** [comment]
> Hi!
> In Debian 9.5 I remove the official mono repository, remove all mono packages and all fixed after do that!

If I do that, I'm just lacking essential packages, and nothing works any more, because mono seems required.

**Comment by Ghostbird** [comment]
Maybe unrelated, but since the fix in 1.16.2:
`Fixed a bug where OmniSharp flame was red inspite of OmniSharp loading the projects without any errors.`
If this error occurs, the OmniSharp flame is *green*, though every project load has failed.

**Comment by rchande** [comment]
@Ghostbird That's intentional. The idea is that the flame turns red if there's a problem with the omnisharp process itself. Consider that there are lots of reasons a project could fail to load that might have nothing to do with omnisharp.
Also @Ghostbird I'm not sure what this issue is tracking any more. Are you still having problems?

**Comment by Ghostbird** [comment]
> Also @Ghostbird I'm not sure what this issue is tracking any more. Are you still having problems?
Yes, sorry for the off-topic remark. The problem persists in any version of the extension above 1.15.2 in combination with both system-wide installed Mono 4.6 and 5.16 and the stand-alone Mono that comes with the extension. (I didn't test other versions)

The latest version of the extension that works for me is version 1.15.2 with either Debian's own Mono 4.6 or the stand-alone Mono from the extension.
All higher versions of the extension throw the error reported in this issue: `InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.`*X*`' specified could not be found.` (The error is repeated for every sub-part *X* of the .NET SDK mentioned in the project file)

The combination of version 1.15.2 of this extension with Mono 5.16 threw another – likely unrelated – error.

**Comment by churchs19** [comment]
I'm still seeing this error in 1.17.0 still today.

**Comment by rchande** [comment]
@Ghostbird @churchs19 What you're describing sounds like a duplicate of #2604 . Please take a look at the steps described in https://github.com/OmniSharp/omnisharp-vscode/issues/2604#issuecomment-430330103

**Comment by churchs19** [comment]
@rchande I am seeing this issue on Windows, not Linux with Mono as described in #2604. I did check my path and search for a global.json and did not find one.

`[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Dev\Projects\Sales\SalesPortal\WebUi\WebUi.csproj'.
c:\Dev\Projects\Sales\SalesPortal\WebUi\WebUi.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.  c:\Dev\Projects\Sales\SalesPortal\WebUi\WebUi.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator``4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List``1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator``4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator``4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator``4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator``4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary``2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary``2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary``2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath)
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectLoader loader)
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func``1 loader)`

dotnet info

`
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
`

I'm also stuck with the latest working version being 1.15.2. I do not have the same problem with Visual Studio 15.8.8.

**Comment by Ghostbird** [comment]
@rchande I installed the Mono, 4.6 and ran `COREHOST_TRACE=1 code` and compared the output of version 1.17.0 and 1.15.2 of the extension. Below is an interesting excerpt:



1.17.0 shows this:
```
Terminating global.json search at [/]
Searching SDK directory in [/usr/local/bin]
--- Resolving SDK version from SDK dir [/usr/local/bin/sdk]
Checking if resolved SDK dir [/usr/local/bin/sdk/-1.-1.-1] exists
It was not possible to find any SDK version
```

**Comment by Ghostbird** [comment]
Maybe this can shed some additional light on the situation:

I recently upgraded my system to Debian 10. Some things went wrong, and I had to reinstall stuff. Afterwards my projects would not load using any version of the extension, and I got the error from #2667.

I found that there is no `msbuild` package available in my system repositories (which might mean I'm missing a repository.

After messing a round for a few minutes, I uninstalled `mono-complete` (version 5.18 from the Mono repository, not 4.6 from the Debian repository), and downgraded this extension to version 1.15.2

Everything works again. It seems to me that version 1.15.2 was the last version that automatically pulls in some requirements. Or all later versions have some new dependency that is not installed automatically.

**Comment by Ghostbird** [comment]
Finally managed to finish this, the issue was similar to that mentioned in https://github.com/Microsoft/msbuild/issues/2532#issuecomment-477661382 There was a dead symbolic link `/usr/local/bin/dotnet -> /opt/dotnet/dotnet`. This triggered the issue.
The link was there because the original dotnet Debian package that was not available through repositories, and had to be installed more manually, did not properly unlink `/usr/local/bin/dotnet` when uninstalling, and omnisharp apparently assumes that when the path `/usr/local/bin/dotnet` exists, that is the dotnet install location.
