### ISSUE TITLE
Could not load file or assembly 'OmniSharp.Stdio, Version=1.32.0.0

### ISSUE THREAD

**Issue by svsenthil84** [OmniSharp/omnisharp-vscode#2647]
## Environment data
`dotnet --info` output:
Starting OmniSharp server at 11/2/2018, 12:40:43 PM
    Target: d:\FProjects_WorkSpace\TravelApp\TravelApp.sln

OmniSharp server started.
    Path: C:\Users\SenthilkumarV\.vscode\extensions\ms-vscode.csharp-1.17.0\.omnisharp\1.32.6\OmniSharp.exe
    PID: 9556

System.IO.FileNotFoundException: Could not load file or assembly 'OmniSharp.Stdio, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'OmniSharp.Stdio, Version=1.32.0.0, Culture=neutral, PublicKeyToken=null'
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_0.<Main>b__0()
   at OmniSharp.HostHelpers.Start(Func`1 action)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

VS Code version: 1.28.2
C# Extension version:  1.17.0

**Comment by filipw** [comment]
> Path: C:\Users\SenthilkumarV.vscode\extensions\ms-vscode.csharp-1.17.0.omnisharp\1.32.6\OmniSharp.exe

is this the actual path it prints? there are 2 slashes missing (in front of `.vscode` and `.omnisharp`).
Anyway, looks like the extension download was somehow corrupt. Could you try navigating to `C:\Users\{user}\.vscode\extensions\ms-vscode.csharp-1.17.0`, delete the whole folder, and reinstall the extension again?

**Comment by andyp22** [comment]
I had a similar error and deleting the whole folder then reinstalling worked for me.

**Comment by rchande** [comment]
@svsenthil84 Did reinstalling help?
