### ISSUE TITLE
C# intellisense not working

### ISSUE THREAD

**Issue by otavio-silva** [OmniSharp/omnisharp-vscode#2668]
## Environment data
`dotnet --info` output:
```
SDK do .NET Core (refletindo qualquer global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Ambiente de tempo de execução:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

VS Code version: 1.28.2

C# Extension version: 1.17.0

## Steps to reproduce
Simply create a C# source code file (by using `dotnet new console, dotnet restore` or not, makes no difference)

## Expected  behavior
C# extension should point out errors, warnings and autocompletion

## Actual behavior
Does absolutely nothing
![2018-11-11 3](https://user-images.githubusercontent.com/22914610/48318382-15c15d00-e5e7-11e8-8e3b-3ebc608d804f.png)

**Comment by rchande** [comment]
@otavio-silva Please share your omnisharp log.

**Comment by otavio-silva** [comment]
@rchande ,
Here's the log from Omnisharp (I've configured logging level to "debug" and project load timeout to 120):
```
Starting OmniSharp server at 11/13/2018, 7:59:24 PM
    Target: d:\otavi\Documents\Code\C#\Testing

Razor dev mode active. Suppressing built-in OmniSharp Razor support.

OmniSharp server started.
    Path: C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\.omnisharp\1.32.6\OmniSharp.exe
    PID: 15432

Attach debugger to process 3484 to continue...
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```
Also, here's the log from VSCode (maybe it helps somehow?):
```
[2018-11-13 19:59:21.737] [renderer1] [info] no standard startup: panel is active
[2018-11-13 19:59:24.715] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-11-13 19:59:42.720] [renderer1] [error] Pending request cancelled: /v2/blockstructure: Error: Pending request cancelled: /v2/blockstructure
	at RequestQueue.cancelRequest (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\omnisharp\server.js:413:40)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
	at e.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:112:72)
	at e.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:112:794)
	at Object.c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:607:1017)
	at t._receiveCancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:608:753)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:607:276)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:773
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:886
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:156:881)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:157:95)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-11-13 19:59:42.720] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-11-13 19:59:42.721] [renderer1] [error] Pending request cancelled: /v2/codestructure: Error: Pending request cancelled: /v2/codestructure
	at RequestQueue.cancelRequest (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\omnisharp\server.js:413:40)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
	at e.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:112:72)
	at e.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:112:794)
	at Object.c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:607:1017)
	at t._receiveCancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:608:753)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:607:276)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:773
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:886
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:156:881)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:157:95)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-11-13 19:59:59.292] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2018-11-13 20:00:00.105] [renderer1] [error] Pending request cancelled: /codecheck: Error: Pending request cancelled: /codecheck
	at RequestQueue.cancelRequest (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\omnisharp\requestQueue.js:115:15)
	at token.onCancellationRequested (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\omnisharp\server.js:413:40)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
	at e.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:112:72)
	at e.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:112:794)
	at DiagnosticsProvider._validateDocument (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\features\diagnosticsProvider.js:174:44)
	at DiagnosticsProvider._onDocumentAddOrChange (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\features\diagnosticsProvider.js:150:14)
	at DiagnosticsProvider._onDidChangeActiveTextEditor (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\features\diagnosticsProvider.js:143:18)
	at DiagnosticsProvider.vscode.window.onDidChangeActiveTextEditor.event (C:\Users\otavi\.vscode\extensions\ms-vscode.csharp-1.17.0\out\src\features\diagnosticsProvider.js:113:74)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:364)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:585:804
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:496:483)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:757)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:423)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:608:15)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:606:957)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:773
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:886
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:156:881)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:157:95)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```
Those 2 errors kinda repeat themselves.

**Comment by rchande** [comment]
@otavio-silva It looks like you have the "wait for debugger" option on for omnisharp. It won't start up unless you attach a debugger. Can you unset that option and see if it helps your problem? From your log:

>Attach debugger to process 3484 to continue..

**Comment by otavio-silva** [comment]
@rchande,
I did that, now it seems to be working, thank you very much!

**Comment by rchande** [comment]
@otavio-silva Glad you got it to work!
