### ISSUE TITLE
Attemped to update project that is not loaded 

### ISSUE THREAD

**Issue by sebasijan** [OmniSharp/omnisharp-vscode#2670]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-1-003177 [C:\Program Files\dotnet\sdk]
  1.0.0-preview4-004233 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007517 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version:

```
Version: 1.28.2 (system setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

C# Extension version:

    1.17.0

## Steps to reproduce

 1. `dotnet new console`
 2. First I got the error  **Error occured in loading omnisharp from omnisharp.pathCould not start the server due to Error: The system could not find the specified path**
 3. After updating the path in user settings to reflect the new version, I now get the error **Attemped to update project that is not loaded**
 4. I tried re-installing the extension and also creating a new project after making the change but with the same results

## Expected  behavior

Omnisharp should just work and not give any errors

## Actual behavior

Annoying errors prevent me from working

 > Error occured in loading omnisharp from omnisharp.pathCould not start the server due to Error: The system could not find the specified path

Then after fixing the path

 > Attemped to update project that is not loaded

See the full log below:

```
Starting OmniSharp server at 11/12/2018, 12:50:42 PM
    Target: c:\Users\Bassie\Source\Repos\WeighScanner

OmniSharp server started.
    Path: C:\Users\Bassie\.vscode\extensions\ms-vscode.csharp-1.17.0\.omnisharp\1.32.6\OmniSharp.exe
    PID: 20204

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Build Tools 2017 15.8.28010.2050 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            2: Visual Studio Community 2017 15.8.28010.2046 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            3: StandAlone 15.0 - "C:\Users\Bassie\.vscode\extensions\ms-vscode.csharp-1.17.0\.omnisharp\1.32.6\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2017 15.8.28010.2050 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Bassie\Source\Repos\WeighScanner'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Bassie\Source\Repos\WeighScanner'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Bassie\Source\Repos\WeighScanner\WeighScanner.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Bassie\Source\Repos\WeighScanner'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Bassie\Source\Repos\WeighScanner' on host 4824.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Bassie\Source\Repos\WeighScanner\WeighScanner.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Bassie\Source\Repos\WeighScanner\WeighScanner.csproj'.
c:\Users\Bassie\Source\Repos\WeighScanner\WeighScanner.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: Could not load SDK Resolver. A manifest file exists, but the path to the SDK Resolver DLL file could not be found. Manifest file path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\SdkResolvers\Microsoft.Build.NuGetSdkResolver\Microsoft.Build.NuGetSdkResolver.xml'. SDK resolver path: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\Microsoft.Build.NuGetSdkResolver.dll  c:\Users\Bassie\Source\Repos\WeighScanner\WeighScanner.csproj
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.TryAddAssemblyFromManifest(String pathToManifest, String manifestFolder, List`1 assembliesList, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.FindPotentialSdkResolvers(String rootFolder, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.LoadResolvers(LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.Initialize(LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath)
   at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.<>c__DisplayClass3_0.<ResolveSdk>b__0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath)
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectLoader loader)
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader)

[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: c:\Users\Bassie\Source\Repos\WeighScanner\WeighScanner.csproj

```

**Comment by rchande** [comment]
@sebasijan It sounds like this might be a problem with your build tools. Do you know if your build tools include the .NET core build components?

**Comment by sebasijan** [comment]
@rchande I have no idea - how can I check this?

**Comment by NTaylorMullen** [comment]
Had the same issue after setting up my machine to build/run Microsoft/vscode. @rchande you should be able to reproduce the issue by following the contribution directions for `C/C++ compiler tool chain` in the [Microsoft/vscode contributing how to](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites).

Basically you end up getting a `Microsoft.Build.NuGet.Sdk.Resolver.xml` that looks like:
```XML
<!-- 
  For serialization contract see:
  https://github.com/Microsoft/msbuild/blob/0cbd6daa4346e4109d3b0d7f2ebfabddda0edf5d/src/Build/BackEnd/Components/SdkResolution/SdkResolverManifest.cs
-->

<SdkResolver>
  <Path>..\..\..\..\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\Microsoft.Build.NuGetSdkResolver.dll</Path>
</SdkResolver>
```

And following the path doesn't work because there's no `NuGet` folder where it expects.


@sebasijan I was able to fix the issue by uninstalling the Visual Studio Build Tools.

**Comment by sebasijan** [comment]
@NTaylorMullen I could try that, but I don't want to now also mess up my VS environment as I develop on both...

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen I could try that, but I don't want to now also mess up my VS environment as I develop on both...

Totally understand 😄

**Comment by akshita31** [comment]
@sebasijan Can you try installing the .NET Core Build Tools as stated [here](https://github.com/OmniSharp/omnisharp-roslyn/issues/1311#issuecomment-428361674)?

**Comment by martyrzsd** [comment]
I'm using Mac, and I initialize the project in virtual windows. When I use VSC to edit, problems occurred

**Comment by Moortiii** [comment]
I realize that the origin poster was on Windows, but this problem occured for me on Linux and I couldn't find a solution in any of the top threads. I'm not sure why, but the official mono-documentations says:

> The package mono-complete should be installed to install everything - this should cover most cases of "assembly not found" errors.

At best I feel like this is highly misleading as it does **not** install compile-dependencies. If you're on a linux distribution, follow the instructions at [https://www.mono-project.com/download/stable/](at this link) to install the mono-devel package. At the time of writing this can be done using: `sudo apt install mono-devel` on Ubuntu 18.04.  After that, you may need to install mono-complete as well, but this finally fixed the errors for me.

**Comment by satscape** [comment]
Thanks for the info @Moortiii  I have Ubuntu 19.04. Already had packages installed, but Installing mono-devel and mono-complete from the repo shown in your link, rather than the older default packages solved my issues ("Attempted to update project that is not loaded" as well as several other problems relating to C#/Unity)

**Comment by cartermp** [comment]
This does not repro with the latest plugin based on the steps provided.
