### ISSUE TITLE
OmniSharp extension fails to load due to NRE related to msbuild

### ISSUE THREAD

**Issue by drwill-ms** [OmniSharp/omnisharp-vscode#2787]
## Environment data
`dotnet --info` output:
````
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.102\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
````

VS Code version: 1.30.2
C# Extension version: 1.17.1

## Steps to reproduce
1. Azure VM running Windows 10 Pro, Version 1809.
1. Installed chocolatey, and used that to install VS Code.
1. Installed several VS Code extensions including ms-vscode.csharp.
1. Open code and open folder holding c# project.

> Note: I don't have VS installed on this system, but I do have dotnet package which includes msbuild.

## Expected  behavior
No errors in output

## Actual behavior
Output window shows loading error:
````
Starting OmniSharp server at 1/10/2019, 9:48:06 PM
    Target: c:\source\EdgeAndMl\DeviceHarness

OmniSharp server started.
    Path: C:\Users\mluser\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe
    PID: 4688

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 0 MSBuild instance(s)
[fail]: OmniSharp.CompositionHostBuilder
        Could not locate MSBuild instance to register with OmniSharp
System.NullReferenceException: Object reference not set to an instance of an object.
   at OmniSharp.MSBuild.ProjectSystem..ctor(IOmniSharpEnvironment environment, OmniSharpWorkspace workspace, IMSBuildLocator msbuildLocator, IDotNetCliService dotNetCliService, SdksPathResolver sdksPathResolver, MetadataFileReferenceCache metadataFileReferenceCache, IEventEmitter eventEmitter, IFileSystemWatcher fileSystemWatcher, FileSystemHelper fileSystemHelper, ILoggerFactory loggerFactory, IEnumerable`1 eventSinks)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_2`1.<GetImportManyDescriptor>b__4(ExportDescriptor e)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExports(Type exportType, String contractName)
   at System.Composition.CompositionContext.GetExports[TExport](String contractName)
   at OmniSharp.Stdio.Host.Initialize()
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource)
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at OmniSharp.HostHelpers.Start(Func`1 action)
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
````

**Comment by cartermp** [comment]
This is by design at the moment. For Windows, it requires a system-installed MSBuild, typically installed by Visual Studio.

**Comment by drwill-ms** [comment]
An NRE is by design? What a joke.

**Comment by JoeRobich** [comment]
@drwill-ms The C# extension has shipped with a minimal msbuild on Windows for some time. There are some workloads that do require a full install of Build Tools for VS but .NET Core should be supported. Does this reproduce for you in the latest release?
