### ISSUE TITLE
Unity C#  Intellisense not working, [ms-vscode.csharp] provider FAILED

### ISSUE THREAD

**Issue by xeon321** [OmniSharp/omnisharp-vscode#2891]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84
VS Code version: 1.31.1
C# Extension version: 1.17,.1

## Steps to reproduce
1. Open Unity
2. Create a C# script
3. Open the script using VSCode
4. Wait a few seconds

## Expected  behavior
Intellisense working, no errors

## Actual behavior

OmniSharp server Log

OmniSharp server started.
    Path: C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\.omnisharp\1.32.8\OmniSharp.exe
    PID: 3516

The screen cannot be set to the number of lines and columns specified.

Log (Extension Host)
[2019-03-06 14:33:34.765] [exthost] [error] [ms-vscode.csharp] provider FAILED
[2019-03-06 14:33:34.765] [exthost] [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Pending request cancelled: /v2/getcodeactions
[2019-03-06 14:33:35.171] [exthost] [error] [ms-vscode.csharp] provider FAILED
[2019-03-06 14:33:35.173] [exthost] [error] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:406:19)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at OmniSharpServer._makeRequest (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\server.js:529:35)
	at RequestQueue.constructor._requestQueue.requestQueue_1.RequestQueueCollection.request [as _makeRequest] (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\server.js:96:109)
	at RequestQueue.processPending (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\requestQueue.js:73:29)
	at RequestQueueCollection.drain (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\requestQueue.js:134:31)
	at RequestQueueCollection.enqueue (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\requestQueue.js:107:14)
	at makeRequest.Promise (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\server.js:409:36)
	at new Promise (<anonymous>)
	at OmniSharpServer.<anonymous> (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\server.js:401:27)
	at Generator.next (<anonymous>)
	at __awaiter (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\server.js:11:71)
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\server.js:7:12)
	at OmniSharpServer.makeRequest (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\server.js:395:16)
	at Object.<anonymous> (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\utils.js:120:23)
	at Generator.next (<anonymous>)
	at __awaiter (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\utils.js:11:71)
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\utils.js:7:12)
	at Object.typeLookup (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\utils.js:119:12)
	at OmniSharpHoverProvider.<anonymous> (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\features\hoverProvider.js:25:32)
	at Generator.next (<anonymous>)
	at __awaiter (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\features\hoverProvider.js:11:71)
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\features\hoverProvider.js:7:12)
	at OmniSharpHoverProvider.provideHover (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\features\hoverProvider.js:22:16)
	at c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:539:881
	at t.asPromise (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:385)
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:353)
	at e.provideHover (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:539:841)
	at c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:556:834
	at e._withAdapter (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:553:292)
	at e.$provideHover (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:556:796)
	at t._doInvokeHandler (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:118)
	at t._invokeHandler (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:744)
	at t._receiveRequest (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:256)
	at t._receiveOneMessage (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:155)
	at c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:960
	at c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38:994
	at e.fire (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at a (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-03-06 14:33:36.592] [exthost] [error] [ms-vscode.csharp] provider FAILED
[2019-03-06 14:33:36.592] [exthost] [error] Error: Pending request cancelled: /v2/blockstructure
	at RequestQueue.cancelRequest (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\requestQueue.js:115:15)
	at makeRequest.token.onCancellationRequested (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\server.js:413:40)
	at e.fire (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at e.cancel (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:230)
	at e.cancel (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:952)
	at Object.c (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:300)
	at t._receiveCancel (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:64)
	at t._receiveOneMessage (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:505)
	at c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:960
	at c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38:994
	at e.fire (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at a (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-03-06 14:33:36.822] [exthost] [error] [ms-vscode.csharp] provider FAILED
[2019-03-06 14:33:36.822] [exthost] [error] Error: Pending request cancelled: /v2/codestructure
	at RequestQueue.cancelRequest (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\requestQueue.js:45:29)
	at RequestQueueCollection.cancelRequest (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\requestQueue.js:115:15)
	at makeRequest.token.onCancellationRequested (C:\Users\Wilson\.vscode\extensions\ms-vscode.csharp-1.17.1\out\src\omnisharp\server.js:413:40)
	at e.fire (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at e.cancel (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:230)
	at e.cancel (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:952)
	at Object.c (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:300)
	at t._receiveCancel (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:64)
	at t._receiveOneMessage (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:505)
	at c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:638:960
	at c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38:994
	at e.fire (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:113)
	at a (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (c:\Users\Wilson\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)

**Comment by xeon321** [comment]
I downloaded Insiders version, and tried to open just the C# script, Intellisense works. However, if I were to open the C# project, it will fail & show the same errors again.

**Comment by akshita31** [comment]
@xeon321 I am not too familiar with Unity. Is it possible to share a repro project that would help us understand the issue

**Comment by xeon321** [comment]
Sure, here you go. Just an empty project with 1 script file and that's all. 
To switch Unity's default script editor, you need to open Unity
Edit -> Preferences -> External Tools -> External Script Editor

https://drive.google.com/open?id=1g5gOTOYSE4iM00ZFiI9FTr7AVp-jKyaa

**Comment by akshita31** [comment]
@xeon321 I opened the script as you suggested and the intellisense works for me. In  the log you pasted I only see the first two lines of the OmniSharp log. Could you post the full Omnisharp log from the output window ?

![image](https://user-images.githubusercontent.com/12554141/54059804-52751d80-41af-11e9-990c-499807a0268e.png)

Do you see the green omnisharp flame ?

**Comment by xeon321** [comment]
Interesting... 

This is what I get in the Omnisharp log.

OmniSharp server started.
Path: C:\Users\Wilson.vscode\extensions\ms-vscode.csharp-1.17.1.omnisharp\1.32.8\OmniSharp.exe
PID: 3516

The screen cannot be set to the number of lines and columns specified.


 And yes, I do get the green flame icon until I start to type, then I think everything just goes crazy. 

I do notice that my bottom left corner is different with yours, mine doesn't show the name & live share & the solution name.

I tried reinstalling vscode and removed all extensions, still the same :(

Could it be because I have Visual Studio Community 2017 installed ?

**Comment by xeon321** [comment]
Anyway, the problem solved itself after I reformat my PC and also I downloaded the system version installation instead of user version. 

Thanks for the help.

**Comment by vvdimov** [comment]
My VSCode installation is exhibiting the same exact issues.

**Comment by xeon321** [comment]
> My VSCode installation is exhibiting the same exact issues. Reformatting the machine is not an option though.

I fixed mine after I reformatted my PC and installed VSCode using System Installer instead of User Installer. You can try the latter one, see if that's the solution.

**Comment by banmohan** [comment]
In my case, I solved this by removing "*" from package version on .csproj

**Comment by firezdog** [comment]
"Reformat your PC" is not an acceptable solution to this problem.

**Comment by Venipa** [comment]
Im currently having the same problem tho i dont have any wildcard in my `.csproj` or `packages.config`
