### ISSUE TITLE
Debugger will silently exit on Linux if .NET Core compatible libicu is missing

### ISSUE THREAD

**Issue by seth-seikosoft** [OmniSharp/omnisharp-vscode#2928]
## Environment data
- dotnet:
    .NET Core SDK (reflecting any global.json):
    Version:   2.2.103
    Commit:    8edbc2570a

    Runtime Environment:
    OS Name:     opensuse-tumbleweed
    OS Version:  20190318
    OS Platform: Linux
    RID:         linux-x64
    Base Path:   /usr/share/dotnet/sdk/2.2.103/

    Host (useful for support):
    Version: 2.2.3
    Commit:  6b8ad509b6

    .NET Core SDKs installed:
    2.2.103 [/usr/share/dotnet/sdk]

    .NET Core runtimes installed:
    Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

- VScode: 
    Version: 1.32.3
    Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
    Date: 2019-03-14T23:38:49.842Z
    Electron: 3.1.6
    Chrome: 66.0.3359.181
    Node.js: 10.2.0
    V8: 6.6.346.32
    OS: Linux x64 5.0.2-1-default

- ms-vscode.csharp: v1.17.1
 
## Issues
Note:  with the above information I'm still **not** seeing the `CSharp: Report an issue` option.

I'm trying to attach the debugger to a running process of `dotnet watch run` in an external terminal.  
The processes dropdown does show up with all my running processes and when I choose the correct process the window closes, the debugger panel (stop/start, jump over, jump into, etc) shows up.
but then vscode just shows the blue loading line and no matter how long I wait it does not attach to the process and doesn't start a debug session.  Nothing shows up in the debug console either (yellow ouput) 

I believe I have all the dependencies install.  I don't see any errors when omnisharp starts up.  However I'm not able to attach to the debugger.  If I try to start the Web app
it will build correctly but at the time it tries to attach a debugger it just hangs and doesn't attach to anything. 

I'm really just wanting to attach to the external process as it's more efficient on resources.

I've look at several other issues but it looks like most of them are out of date and I've tried the solutions and they haven't worked.

specifically ones that I've look into are:
https://github.com/OmniSharp/omnisharp-vscode/issues/1631
https://github.com/OmniSharp/omnisharp-vscode/issues/1513

The following are my config files and the output of onmisharp when my project launches is vscode.

If you need any other information please let me know.

Thank you again for all the work you devs have put into this product!

Any help is appriciated

**.vscode/launch.json (I've replaced my actual app name with `<app name>`)**
```
{
   // Use IntelliSense to find out which attributes exist for C# debugging
   // Use hover for the description of the existing attributes
   // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.2/<app name>.dll",
            "args": [],
            "cwd": "${workspaceFolder}/<app name>",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
            "enabled": true,
            "args": "${auto-detect-url}",
            "windows": {
                "command": "cmd.exe",
                "args": "/C start ${auto-detect-url}"
            },
            "osx": {
                "command": "open"
            },
            "linux": {
                "command": "xdg-open"
            }
            },
            "env": {
            "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
            "/Views": "${workspaceFolder}/<app name>/Views"
            }
        },
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/<app name>.Tests/bin/Debug/netcoreapp2.2/<app name>.Tests.dll",
            "args": [],
            "cwd": "${workspaceFolder}/<app name>.Tests",
            // For more information about the 'console' field, see https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ,]
}
```

**.vscode/tasks.json**
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/<app name>.csproj"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}
```

**omnisharp logs (I've replace paths with "path/to/" and change project name to "<app name>")**
```
Starting OmniSharp server at 3/20/2019, 11:13:46 AM
    Target: /path/to/project/<app name>.sln

Razor dev mode active. Suppressing built-in OmniSharp Razor support.

OmniSharp server started with Mono 5.16.0.
    Path: /path/to/home/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/OmniSharp.exe
    PID: 13219

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on opensuse-tumbleweed 20190318.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/path/to/home/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            CscToolPath = /path/to/home/.vscode/extensions/ms-vscode.csharp-1.17.1/.omnisharp/1.32.8/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/path/to/project'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/path/to/project/<app name>.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.Web/<app name>.Web.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.External/<app name>.External.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.Domain/<app name>.Domain.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.Auth/<app name>.Auth.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.Auth.Tests/<app name>.Auth.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.External.Tests/<app name>.External.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.Domain.Tests/<app name>.Domain.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.Import.Console/<app name>.ImportConsole.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/path/to/project'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.Web/<app name>.Web.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/path/to/project' on host 13080.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.Web/<app name>.Web.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/path/to/project/<app name>.Web/<app name>.Web.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.External/<app name>.External.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.External/<app name>.External.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/path/to/project/<app name>.External/<app name>.External.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.Domain/<app name>.Domain.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.Domain/<app name>.Domain.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/path/to/project/<app name>.Domain/<app name>.Domain.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.Auth/<app name>.Auth.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.Auth/<app name>.Auth.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/path/to/project/<app name>.Auth/<app name>.Auth.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.Auth.Tests/<app name>.Auth.Tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.Auth.Tests/<app name>.Auth.Tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/path/to/project/<app name>.Auth.Tests/<app name>.Auth.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.External.Tests/<app name>.External.Tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.External.Tests/<app name>.External.Tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/path/to/project/<app name>.External.Tests/<app name>.External.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.Domain.Tests/<app name>.Domain.Tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.Domain.Tests/<app name>.Domain.Tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/path/to/project/<app name>.Domain.Tests/<app name>.Domain.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.Import.Console/<app name>.ImportConsole.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.Import.Console/<app name>.ImportConsole.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/path/to/project/<app name>.Import.Console/<app name>.ImportConsole.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.Web
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.External
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.Domain
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.Auth
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.Auth.Tests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.External.Tests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.Domain.Tests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.ImportConsole
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        <app name>.External.Tests: Did not find 'FakeItEasy' in lock file.
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        <app name>.ImportConsole: Found package reference 'Dapper', but none of the versions in the lock file ("1.50.5") satisfy [1.60.1, )
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        <app name>.ImportConsole: Found package reference 'FakeItEasy', but none of the versions in the lock file ("5.0.1") satisfy [5.1.0, )
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.Domain.Tests/<app name>.Domain.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.Domain.Tests/<app name>.Domain.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.Domain.Tests/<app name>.Domain.Tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.Domain.Tests/<app name>.Domain.Tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.Domain.Tests
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.External.Tests/<app name>.External.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.External.Tests/<app name>.External.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.External.Tests/<app name>.External.Tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.External.Tests/<app name>.External.Tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.External.Tests
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.Import.Console/<app name>.ImportConsole.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/path/to/project/<app name>.Import.Console/<app name>.ImportConsole.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /path/to/project/<app name>.Import.Console/<app name>.ImportConsole.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/path/to/project/<app name>.Import.Console/<app name>.ImportConsole.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <app name>.ImportConsole
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using System;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using System.Runtime.Serialization;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using <app name>.Web.Models.Solicitation;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using Microsoft.AspNetCore.Mvc.Rendering;
```

Looking at this issue: https://github.com/OmniSharp/omnisharp-vscode/issues/1513
```
$ pgrep dotnet -a 
12551 dotnet watch run
12559 /usr/share/dotnet/dotnet /usr/share/dotnet/sdk/2.2.103/DotnetTools/dotnet-watch/2.2.0/tools/netcoreapp2.2/any/dotnet-watch.dll run
16404 /usr/share/dotnet/dotnet run
16597 dotnet exec /path/to/proejct/<app name>/bin/Debug/netcoreapp2.2/<app name>.Web.dll
```

**Comment by gregg-miskelly** [comment]
To make sure I understand, you are attaching to this process, correct -- 

```
16597 dotnet exec /path/to/proejct/<app name>/bin/Debug/netcoreapp2.2/<app name>.Web.dll
```

If so, can you try [enabling logging](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging) and see what you get?

**Comment by seth-seikosoft** [comment]
Thank you for the very quick reply! 

Sorry I should have specified that.  Yes that is the process that I'm trying to attach to.
I've tried enabling logging from the link you gave me. 

The "Quick Method" results in nothing output to the debug console.

The "Full Method"  I'm able to get to step 3 but when I run 
`./vsdbg-ui --server --consoleLogging`  I get: 
```
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
[1]    4837 abort      sudo ./vsdbg-ui --server --consoleLogging
```
looking through the packages on my system.  I have several packages of ICU packages install.
```
S  | Name                   | Summary                                                        | Type   
---+------------------------+----------------------------------------------------------------+--------
i+ | icu                    | International Components for Unicode                           | package
   | icu4j                  | International Components for Unicode for Java                  | package
   | icu4j-charset          | Charset converter library of icu4j                             | package
   | icu4j-javadoc          | Javadoc for icu4j                                              | package
   | icu4j-localespi        | https://github.com/aspnet/Razor.VSCode/issues/243Locale SPI library of icu4j                                    | package
i+ | libharfbuzz-icu0       | ICU integration into the HarfBuzz OpenType text shaping engine | package
   | libharfbuzz-icu0-32bit | ICU integration into the HarfBuzz OpenType text shaping engine | package
i  | libicu-devel           | Development files for the ICU library                          | package
   | libicu-devel-32bit     | Development files for the ICU library                          | package
   | libicu-doc             | Documentation for the ICU library                              | package
i+ | libicu-suse63_1        | International Components for Unicode                           | package
   | libicu-suse63_1-32bit  | International Components for Unicode                           | package
   | libicu63_1-bedata      | Rule databases and tables for ICU                              | package
i+ | libicu63_1-ledata      | Rule databases and tables for ICU                              | package
   | python2-PyICU          | Python Extension Wrapping the ICU C++ API                      | package
   | python3-PyICU          | Python Extension Wrapping the ICU C++ API                      | package
```
searching around for this issue I found a few articles, 2 of which don't really give a remedy on my end, and another one says that I may be using a version that's too new for dotnet? 

https://github.com/aspnet/Razor.VSCode/issues/243
https://github.com/PowerShell/PowerShell/issues/8198
https://github.com/Microsoft/vscode-python/issues/2967

The current version of ICU (`icu-config --version`) = 63.1

I could try using an older version of ICU if you think that would work.  

What version would you suggest me to use (if I can even use an older version)? 

Thank you again for your quick reply

**Comment by seth-seikosoft** [comment]
looking into this issue a little more about the missing ICU version I found this article: [Problem with ICU Dependency](http://blog.programmableproduction.com/2016/04/29/CoreClr-Problem-With-ICU-Dependency-On-ArchLinux/)

it's for Arch linux and coreClr but I image that the information/problem is the same.  

When running the `strace` program he references I get the following output log (see attached log file) 
` strace -o ~/Downloads/dotnet.log ./vsdbg-ui --server --consoleLogging `
[dotnet.log](https://github.com/OmniSharp/omnisharp-vscode/files/2992929/dotnet.log)

Looking through that it looks like there are several versions of libicuuc that are missing?  You would think that the latest version of ICU would cover those?  I also see several versions that are referenced e.g. 64, 66, 67, 70 that I'm not sure where they are coming from because according to [ICU project website](http://site.icu-project.org/download) their latest version is 63.1?

**Comment by gregg-miskelly** [comment]
Here is the CoreCLR's documentation on their native dependencies -- https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#linux-distribution-dependencies

Unfortunately it isn't precise on their libicu dependencies. Here is the relevant code in CoreCLR -- 
https://github.com/dotnet/coreclr/blob/release/2.2/src/corefx/System.Globalization.Native/icushim.cpp#L171

If you aren't able to install a libicu that coreclr like you can enable [Globalization Invariant Mode](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md) by setting the environment variable `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1`.

**Comment by gregg-miskelly** [comment]
BTW: in case it isn't obvious, the reason you see probes for versions of ICU that don't even exist yet is that it looks like that code will probe up to 20 version numbers ahead of what CoreCLR was built against.

**Comment by seth-seikosoft** [comment]
thank you for that information that was very helpful!  

I was able to find older version of the ICU lib.  
(for anyone looking for those packages here are the links to them)
Note:  I used the official packages where I could, even if it was for an older OS version e.g. LEAP 15.0, LEAP 
https://software.opensuse.org/package/libicu60_2
