### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by jim1019** [OmniSharp/omnisharp-vscode#3008]
System.IO.FileNotFoundException: δ�ܼ����ļ�����򼯡�netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51��������ĳһ�������ϵͳ�Ҳ���ָ�����ļ���
�ļ���:��netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51��
   �� OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   �� OmniSharp.HostHelpers.Start(Func`1 action)

����: ���򼯰���־��¼���رա�
Ҫ���ó��򼯰�ʧ����־��¼���뽫ע���ֵ [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)����Ϊ 1��
ע��: ����һЩ����򼯰�ʧ����־��¼������������ʧ��
Ҫ�رմ˹��ܣ����Ƴ�ע���ֵ [HKLM\Software\Microsoft\Fusion!EnableLog]��

**Comment by arundavidshelly** [comment]
System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at OmniSharp.HostHelpers.Start(Func`1 action)

**Comment by SirIntruder** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Roslyn.Utilities.EventMap.AddEventHandler[TEventHandler](String eventName, TEventHandler eventHandler)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_2`1.<GetImportManyDescriptor>b__4(ExportDescriptor e)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_2`1.<GetImportManyDescriptor>b__4(ExportDescriptor e)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExports(Type exportType, String contractName)
   at System.Composition.CompositionContext.GetExports[TExport](String contractName)
   at OmniSharp.Stdio.Host.Initialize()
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource)
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1()
   at OmniSharp.CommandLineApplication.<>c__DisplayClass11_0.<OnExecute>b__0()
   at OmniSharp.CommandLineApplication.Execute(IEnumerable`1 args)
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_0.<Main>b__0()
   at OmniSharp.HostHelpers.Start(Func`1 action)

**Comment by jwerra** [comment]
Same issue reported here https://github.com/OmniSharp/omnisharp-vscode/issues/3004#issuecomment-484416851

**Comment by filipw** [comment]
This was resolved by https://github.com/OmniSharp/omnisharp-roslyn/pull/1469
Until the next release, the workaround is to install .NET 4.7.2 or use the method described here https://github.com/OmniSharp/omnisharp-vscode/issues/3004#issuecomment-484655065 which will prompt automatically for .NET 4.7.2 installation.
