### ISSUE TITLE
C# Extension not working for VS Code

### ISSUE THREAD

**Issue by haripulaparthi** [OmniSharp/omnisharp-vscode#3029]
## Environment data
`dotnet --info` output:
VS Code version:  1.26.1
C# Extension version:
Starting OmniSharp on Windows 6.2.9200.0 (x64)
## Steps to reproduce
Just Installed C# extension from market place using VS Code

## Expected  behavior
It should install and work as specified.

## Actual behavior
Not able to identify the issue ?

Starting OmniSharp server at 4/27/2019, 2:33:04 AM
    Target: c:\Hari\Projects\Udemy\AngularCore\DatingApp

OmniSharp server started.
    Path: C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\OmniSharp.exe
    PID: 14512

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\msbuild\15.0\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\msbuild\15.0\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\msbuild\15.0\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\msbuild
            MSBuildToolsPath = C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\msbuild\15.0\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Hari\Projects\Udemy\AngularCore\DatingApp'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Hari\Projects\Udemy\AngularCore\DatingApp'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Hari\Projects\Udemy\AngularCore\DatingApp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Hari\Projects\Udemy\AngularCore\DatingApp' on host 7584.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj'.
c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.  c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath)
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectLoader loader)
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader)

[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj

**Comment by filipw** [comment]
According to your log you are on a very old version of VS Code (1.26.1) and - because of that - also on a very old C# extension version (1.16.2).

Please update to latest VS Code (1.33) and then update to latest C# extension (1.19.0).

**Comment by haripulaparthi** [comment]
Hi Filipw,

Thanks for your reply.

After updating the VS Code (1.33) & C# Extension (1.19) the issue is still exists.

Error Details as follows:-

Starting OmniSharp server at 27/4/2019, 3:12:47 AM
    Target: c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API

OmniSharp server started.
    Path: C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.18\OmniSharp.exe
    PID: 10184

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.18\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.18\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.18\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.18\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.18\.msbuild
            MSBuildToolsPath = C:\Users\Hari\.vscode\extensions\ms-vscode.csharp-1.19.0\.omnisharp\1.32.18\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API' on host 12620.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj'.
c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.  c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath) in C:\projects\omnisharp-roslyn\src\OmniSharp.MSBuild\ProjectLoader.cs:line 129
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath) in C:\projects\omnisharp-roslyn\src\OmniSharp.MSBuild\ProjectLoader.cs:line 72
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader) in C:\projects\omnisharp-roslyn\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 94
   at OmniSharp.MSBuild.ProjectManager.<>c__DisplayClass31_0.<LoadProject>b__0() in C:\projects\omnisharp-roslyn\src\OmniSharp.MSBuild\ProjectManager.cs:line 295
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in C:\projects\omnisharp-roslyn\src\OmniSharp.MSBuild\ProjectManager.cs:line 306

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Hari\Projects\Udemy\AngularCore\DatingApp\DatingApp.API\DatingApp.API.csproj

**Comment by filipw** [comment]
What is your `dotnet --info` output?
Also, could you share the project you are trying to load?

**Comment by loflina** [comment]
I was able to solve a very similar issue by following the directions here: https://github.com/OmniSharp/omnisharp-vscode/issues/2509#issuecomment-420318250.

**Comment by cartermp** [comment]
Closing out as no additional info was added.
