### ISSUE TITLE
Omnisharp seems to fail at startup

### ISSUE THREAD

**Issue by Jthomas54** [OmniSharp/omnisharp-vscode#3047]
## Issue Description ##
Omnisharp seems to fail at startup

## Steps to Reproduce ##
Create a new project with `dotnet new` or open an existing project/solution
 
## Expected Behavior ##
Omnisharp starts and intellisense is available.

## Actual Behavior ##
Omnisharp fails to load with a error.

### OmniSharp log ###
<details>Starting OmniSharp server at 5/6/2019, 9:52:30 PM
    Target: /home/justin/dotnet/test.sln

[ERROR] TypeError: Cannot read property 'on' of undefined</details>

### C# log ###
<details>No logging output recorded</details>

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.0

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: TypeError: Cannot read property 'on' of undefined</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.603
 Commit:    ae71c68742

Runtime Environment:
 OS Name:     elementary
 OS Version:  5.0
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.603/

Host (useful for support):
  Version: 2.1.10
  Commit:  9013a2af4b

.NET Core SDKs installed:
  2.1.603 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.19.0|
|csharpextensions|jchannon|1.3.0|
|docomment|k--kato|0.1.6|
|Go|ms-vscode|0.10.2|
|intellij-idea-keybindings|k--kato|0.2.31|
|msbuild-project-tools|tintoy|0.2.54|
|vetur|octref|0.19.5|
|vscode-eslint|dbaeumer|1.8.2|
|vscode-solution-explorer|fernandoescolar|0.3.3|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-yaml|redhat|0.4.0|;

</details>

I noticed the mono message, but I only use dotnet core and have set the `omnisharp.useGlobalMono` to `never`.

### Log (Window) from vscode
```
[2019-05-07 07:58:25.778] [renderer1] [error] Cannot read property 'on' of undefined: TypeError: Cannot read property 'on' of undefined
    at Promise (/home/justin/.vscode/extensions/ms-vscode.csharp-1.14.0/out/src/omnisharp/launcher.js:299:29)
    at new Promise (<anonymous>:null:null)
    at hasMono (/home/justin/.vscode/extensions/ms-vscode.csharp-1.14.0/out/src/omnisharp/launcher.js:287:12)
    at Promise (/home/justin/.vscode/extensions/ms-vscode.csharp-1.14.0/out/src/omnisharp/launcher.js:275:9)
    at new Promise (<anonymous>:null:null)
    at canLaunchMono (/home/justin/.vscode/extensions/ms-vscode.csharp-1.14.0/out/src/omnisharp/launcher.js:274:12)
    at platform_1.PlatformInformation.GetCurrent.then.platformInfo (/home/justin/.vscode/extensions/ms-vscode.csharp-1.14.0/out/src/omnisharp/launcher.js:205:16)
```

**Comment by Jthomas54** [comment]
Not sure the exact reasoning, but installing mono-devel allows omnisharp to start working again.
