### ISSUE TITLE
C# 1.20.0 and Unity Not Working

### ISSUE THREAD

**Issue by rotoCalvin** [OmniSharp/omnisharp-vscode#3114]
## Issue Description ##
The C# extension works for a few minutes, but then stops everything, including error detection and intellisense. This is a Unity project.

### OmniSharp log ###
<details>Starting OmniSharp server at 6/13/2019, 10:42:16 AM
    Target: c:\projects\roto\danville\Yoga\Yoga.sln

OmniSharp server started.
    Path: C:\Users\clevally\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.32.20\OmniSharp.exe
    PID: 113344

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 15.0 - "C:\Users\clevally\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.32.20\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'C:\Users\clevally\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.32.20\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 15.0 - "C:\Users\clevally\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.32.20\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = C:\Users\clevally\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.32.20\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = C:\Users\clevally\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.32.20\.msbuild
            MSBuildToolsPath = C:\Users\clevally\.vscode\extensions\ms-vscode.csharp-1.20.0\.omnisharp\1.32.20\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\projects\roto\danville\Yoga'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\projects\roto\danville\Yoga\Yoga.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\projects\roto\danville\Yoga\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\projects\roto\danville\Yoga\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\projects\roto\danville\Yoga'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\projects\roto\danville\Yoga\Assembly-CSharp.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\projects\roto\danville\Yoga' on host 106788.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\projects\roto\danville\Yoga\Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\projects\roto\danville\Yoga\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\projects\roto\danville\Yoga\Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\projects\roto\danville\Yoga\Assembly-CSharp-Editor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\projects\roto\danville\Yoga\Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly 'c:\projects\roto\danville\Yoga\Assembly-CSharp.dll'
</details>

### C# log ###
<details>The C# log is blank</details>

### Log(Window) ###
<details>Lots of these kinds of things:
[2019-06-13 11:09:32.708] [renderer1] [error] Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
    at DocommentDomainCSharp.IsTriggerDocomment (C:\Users\clevally\.vscode\extensions\k--kato.docomment-0.1.7\out\src\Domain\Lang\DocommentDomainCSharp.js:23:39)
    at DocommentDomainCSharp.Execute (C:\Users\clevally\.vscode\extensions\k--kato.docomment-0.1.7\out\src\Domain\DocommentDomain.js:20:19)
    at DocommentControllerCSharp._onEvent (C:\Users\clevally\.vscode\extensions\k--kato.docomment-0.1.7\out\src\Controller\DocommentController.js:54:31)
    at DocommentControllerCSharp.constructor.vscode_1.workspace.onDidChangeTextDocument.event (C:\Users\clevally\.vscode\extensions\k--kato.docomment-0.1.7\out\src\Controller\DocommentController.js:18:22)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:740)
    at c.$acceptDirtyStateChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:525:705)
    at d._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:1006)
    at d._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:698)
    at d._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:346)
    at d._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:141)
    at define.constructor._protocol.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:640:400)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:766)
    at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:812)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at n.constructor.e.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:748:721)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:766)
    at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:812)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at y._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:185:670)
    at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:981)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at f.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:179:532)
    at define.constructor._register._socket.onData.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:869)
    at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:141)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)</details>

## Environment information ##

**VSCode version**: 1.35.1
**C# Extension**: 1.20.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.203\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.203 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.6|
|auto-rename-tag|formulahendry|0.1.0|
|auto-using|Fudge|0.7.8|
|city-lights-icon-vsc|Yummygum|1.1.3|
|color-highlight|naumovs|2.3.0|
|csharp|ms-vscode|1.20.0|
|csharpextensions|jchannon|1.3.0|
|csharpfixformat|Leopotam|0.0.81|
|debugger-for-chrome|msjsdiag|4.11.3|
|docomment|k--kato|0.1.7|
|henna|httpsterio|0.10.0|
|markdown-all-in-one|yzhang|2.3.1|
|markdown-preview-enhanced|shd101wyy|0.4.1|
|material-color|guobing|1.1.0|
|one-monokai|azemoh|0.3.7|
|sick-code|pablopunk|2.0.0|
|theme-dracula|dracula-theme|2.18.0|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|2.7.2|
|vs-color-picker|lihui|1.0.0|
|vscode-colorize|kamikillerto|0.8.10|
|vscode-nextgenas|bowlerhatllc|0.19.0|;

</details>

**Comment by borup3** [comment]
This happens in pure .NET Core 2.2 as well. downgrading to 1.19.1 makes OmniSharp work again. Sometimes the server fails to launch, other times it launches but does nothing.

**Comment by Hyphena** [comment]
I just saw that there was an update to the extension and hoped this issue would be fixed... I guess not. That sucks, I guess I'll just stick to 1.19.0 for the unforeseeable future.

**Comment by rodrigoruiz** [comment]
I was unable to install a version different from the current one. How should I do that?
I did try the "Install Another Version..." button in VS Code and also tried downloading the csharp-1.19.1.vsix file manually, none worked.

**Comment by cartermp** [comment]
Thanks for the report. Does this reproduce with the latest versions of both plugins? Do you have a sample project or other information to share about this?

**Comment by cartermp** [comment]
Closing out as no additional info was added.
