### ISSUE TITLE
Crashing while editing razor files

### ISSUE THREAD

**Issue by hez2010** [OmniSharp/omnisharp-vscode#3141]
## Environment data
dotnet SDK version: 3.0.100-preview6-012264
VS Code version: 1.35.1
C# Extension version: 1.20.0

## Steps to reproduce
Edit razor files of a blazor client app. it sometimes crash.

## Expected  behavior
Nothing happen

## Actual behavior
```
[Error - 5:01:26 PM] Request textDocument/completion failed.
  Message: Internal Error - System.AggregateException: One or more errors occurred. (Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.) ---> OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDocumentSynchronizationEndpoint.Handle(DidChangeTextDocumentParams notification, CancellationToken token) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentSynchronizationEndpoint.cs:line 79
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.RouteNotification(IHandlerDescriptor descriptor, Notification notification)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.TryGetTextVersion(VersionStamp& result)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.Completion.RazorCompletionEndpoint.Handle(CompletionParams request, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs:line 100
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.RouteRequest(IHandlerDescriptor descriptor, Request request)
---> (Inner Exception #0) OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDocumentSynchronizationEndpoint.Handle(DidChangeTextDocumentParams notification, CancellationToken token) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentSynchronizationEndpoint.cs:line 79
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.RouteNotification(IHandlerDescriptor descriptor, Notification notification)<---

  Code: -32602 
```

**Comment by rchande** [comment]
cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
Hmmm, interesting! @hez2010 can you give some more context on what you were doing when this crash occurred? Also reproducing the crash with razor.trace set to verbose would be highly useful as well.

**Comment by hez2010** [comment]
Maybe you can try editing files in `https://github.com/chanan/BlazorStrap/tree/master/src/Sample` with razor.trace = off.  
I found that if I set razor.trace to verbose, it won't crash anymore.

**Comment by NTaylorMullen** [comment]
Hmm played around with it for 5 minutes or so without any luck crashing it 😢. Could you detail some specific steps as in what file was opened, what you typed etc.?

**Comment by hez2010** [comment]
I opened the project and simply append a `<Card>` in index.razor, and it crash.
![image](https://user-images.githubusercontent.com/14960345/60285607-9cda0000-9940-11e9-9cbc-fbcd49398c33.png)

**Comment by NTaylorMullen** [comment]
Ahh, that helps a lot thanks for investigating further! We're tracking the fix for this issue over here: https://github.com/aspnet/Razor.VSCode/issues/372

**Comment by nkev** [comment]
@NTaylorMullen If it helps, this exact `JsonRpc.Server` crash occurs reproducably, every time on my Macbook (VS Code and with dotnet Core 2.1) right after I press the "dot" in `Orchard.` as shown in this example:
https://www.youtube.com/watch?v=4o9zG17cfa0&feature=youtu.be&t=1391
