### ISSUE TITLE
Extension activation fails due to missing dist folder

### ISSUE THREAD

**Issue by stephtr** [OmniSharp/omnisharp-vscode#3159]
On one of my PCs the `extensions\ms-vscode.csharp-1.20.0\dist` folder somehow went missing (probably during an automatic extension update). Reinstalling the extension within VS Code didn't help, VS Code didn't remove the `extensions\ms-vscode.csharp-1.20.0` folder during uninstall. Instead I had to uninstall it, manually remove the folder and again install the extension. Is that an issue of VS Code?

## Environment data
`dotnet --info` output:
```.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.200-preview-009748 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version: 1.36.0
C# Extension version: 1.20.0

## Steps to reproduce
- Install extension
- Open .NET Core porject

## Expected  behavior
The extension loads

## Actual behavior
```
Error: Cannot find module 'c:\Users\labor\.vscode\extensions\ms-vscode.csharp-1.20.0\dist\extension'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
	at Function.Module._load (internal/modules/cjs/loader.js:510:25)
	at Function.define._installInterceptor.i._load (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:491:111)
	at Function.t._load (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:760:742)
	at Function.t.getExtensionPathIndex.then.i._load (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:685:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:31:381)
	at c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:747:60
	at D._doActivateExtension (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:747:168)
	at D._activateExtension (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:746:6)
	at D.<anonymous> (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:742:827)
	at Generator.next (<anonymous>)
	at n (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:13:621)
	at new Promise (<anonymous>)
	at n (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:13:398)
	at Object.actualActivateExtension (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:742:529)
	at p._activateExtension (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:479:561)
	at define._activateExtensions.r.length.Promise.all.s.map.e (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:479:245)
	at Array.map (<anonymous>)
	at p._activateExtensions (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:479:233)
	at p.activateById (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:477:355)
	at D._activateById (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:744:743)
	at D.<anonymous> (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:753:319)
	at Generator.next (<anonymous>)
	at o (c:\Users\labor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:13:454)
```

**Comment by stephtr** [comment]
It seems like one has to restart, not reload VS Code for removing old extensions' directories.
