### ISSUE TITLE
Razor Language Server crashing

### ISSUE THREAD

**Issue by ltlombardi** [OmniSharp/omnisharp-vscode#3172]
Issue Type: <b>Bug</b>

Editing a Blazor client side project just created from the template, is crashing the Razor Language Server.. No Intelisence..
.NEt core SDK 3.0.100-preview6-012264

Extension version: 1.20.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.89GB free)|
|Process Argv|F:\Leo\Dropbox\Coding\Artigos, tutoriais , livros, anotações\Git commands.txt|
|Screen Reader|no|
|VM|57%|
</details>

I was editing the Index.razor file. Adding the last two lines of the file:
```
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

<Counter IncrementAmount="4"/> 

<h2>Agora é hora @DateTime.Now</h2>

<h2>Agora é hora @(DateTime.Now - TimeSpan)</h2>
```

**Comment by ltlombardi** [comment]
This time, I was just writing code in line 6 as instructed in this [MS tutorial.](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0) 
Picture 
![image](https://user-images.githubusercontent.com/898124/61175836-91b3e080-a58c-11e9-9036-4b48ea3975ec.png)

**Comment by ltlombardi** [comment]
And here is the log
```
--------------------------------------------------------------------------------
Razor.VSCode version 1.0.0-alpha3-20190606.2
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

[Client - 11:19:43] (Error) Failed to read project config at location f:\Leo\Documents\Dev\BlazorServerSideExample\obj\Debug\netcoreapp3.0\project.razor.json.
Unexpected end of JSON input
Stack Trace:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>:null:null)
    at module.exports.t.RazorProjectManager.getProjectConfiguration (C:\Users\leo\.vscode\extensions\ms-vscode.csharp-1.20.0\dist\extension.js:80:167062)
    at module.exports.t.RazorProjectManager.updateProjectConfiguration (C:\Users\leo\.vscode\extensions\ms-vscode.csharp-1.20.0\dist\extension.js:80:165619)
    at module.exports.t.RazorProjectManager.<anonymous> (C:\Users\leo\.vscode\extensions\ms-vscode.csharp-1.20.0\dist\extension.js:80:165505)
    at Generator.next (<anonymous>:null:null)
    at module.exports.r (C:\Users\leo\.vscode\extensions\ms-vscode.csharp-1.20.0\dist\extension.js:80:164279)
    at new Promise (<anonymous>:null:null)
    at module.exports.r (C:\Users\leo\.vscode\extensions\ms-vscode.csharp-1.20.0\dist\extension.js:80:164056)
    at module.exports.t.RazorProjectManager.register.i.onDidChange.e (C:\Users\leo\.vscode\extensions\ms-vscode.csharp-1.20.0\dist\extension.js:80:165460)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at define.constructor.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:534:834)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at u.$onFileEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:535:859)
    at d._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:1006)
    at d._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:698)
    at d._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:346)
    at d._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:141)
    at define.constructor._protocol.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:640:400)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:766)
    at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:812)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at n.constructor.e.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:748:721)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:766)
    at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:812)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at y._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:185:670)
    at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:981)
    at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
    at f.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:179:532)
    at define.constructor._register._socket.onData.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:869)
    at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:141)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)


Unhandled Exception: System.InvalidOperationException: 'StartWorkTimer' must be called on the foreground thread.
   at Microsoft.CodeAnalysis.Razor.ForegroundDispatcher.AssertForegroundThread(String caller)
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.StartWorkTimer() in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 98
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 214
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 16:34:55] Connection to server got closed. Server will restart.
[Error - 16:34:57] Request textDocument/completion failed.
  Message: Internal Error - OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.Completion.RazorCompletionEndpoint.Handle(CompletionParams request, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs:line 100
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.RouteRequest(IHandlerDescriptor descriptor, Request request)
  Code: -32602 
[Error - 16:34:58] Request textDocument/completion failed.
  Message: Internal Error - OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.Completion.RazorCompletionEndpoint.Handle(CompletionParams request, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs:line 100
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.RouteRequest(IHandlerDescriptor descriptor, Request request)
  Code: -32602 
[Error - 16:34:58] Request textDocument/completion failed.
  Message: Internal Error - OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.Completion.RazorCompletionEndpoint.Handle(CompletionParams request, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs:line 100
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.RouteRequest(IHandlerDescriptor descriptor, Request request)
  Code: -32602 
[Error - 16:34:58] Request textDocument/completion failed.
  Message: Internal Error - OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.Completion.RazorCompletionEndpoint.Handle(CompletionParams request, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs:line 100
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.RouteRequest(IHandlerDescriptor descriptor, Request request)
  Code: -32602 

Unhandled Exception: OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 156
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 196
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 16:34:59] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. (Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.) ---> OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.BackgroundDocumentGenerator.Timer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/BackgroundDocumentGenerator.cs:line 212
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.TryGetTextVersion(VersionStamp& result)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 156
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 196
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 16:35:03] Connection to server got closed. Server will restart.

Unhandled Exception: System.AggregateException: One or more errors occurred. (Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.) ---> OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.BackgroundDocumentGenerator.Timer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/BackgroundDocumentGenerator.cs:line 212
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.TryGetTextVersion(VersionStamp& result)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 156
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 196
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 16:35:06] Connection to server got closed. Server will restart.

Unhandled Exception: OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Exception of type 'OmniSharp.Extensions.JsonRpc.Server.JsonRpcException' was thrown.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.SendRequest[T,TResponse](String method, T params)
   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRemoteTextLoaderFactory.cs:line 73
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass19_0.<<DocumentOpened>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync()
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 156
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 196
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Error - 16:35:10] Connection to server got closed. Server will not be restarted.

```

**Comment by ltlombardi** [comment]
when I type http://localhost:5000 it gets redirected to https://localhost:5001/ and it doesn't load giving this error:
```
This site can’t be reached The webpage at https://localhost:5001/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY
```

This tutorial should not let this happen. If open in old IE, the server loads..
