### ISSUE TITLE
.NET and Unity3D Intellisense stopped working. Omnisharp server fails to launch: System.IO.FileNotFoundException.

### ISSUE THREAD

**Issue by jgbijlsma** [OmniSharp/omnisharp-vscode#3215]
## What happens
I have not used VsCode for a month or so. It was working fine then, but now without any changes (as far as I remember) I made intellisense stopped working, and I get an error in the output for omnisharp. I tried reinstalling Code (uninstall.exe, and removing the .vscode and Code folders from my user and appdata folder manually), but the issue still shows up. One thing that I noticed is that when I reinstalled Code, the setup showed a message saying that code was already installed for all users, after I just completely removed it (even checked for registry entries).

## Omnisharp output log
```
Starting OmniSharp server at 8/6/2019, 9:18:33 AM
    Target: f:\Unity\Distant\Distant.sln

OmniSharp server started.
    Path: C:\Users\Joost Bijlsma\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\OmniSharp.exe
    PID: 11704

System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at OmniSharp.MSBuild.Discovery.Interop.GetSetupConfiguration() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\MSBuild\Discovery\Interop.cs:line 20
   at OmniSharp.MSBuild.Discovery.Providers.VisualStudioInstanceProvider.GetInstances() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\MSBuild\Discovery\Providers\VisualStudioInstanceProvider.cs:line 28
   at OmniSharp.MSBuild.Discovery.MSBuildLocator.GetInstances() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\MSBuild\Discovery\MSBuildLocator.cs:line 221
   at OmniSharp.MSBuild.Discovery.Extensions.GetBestInstance(IMSBuildLocator msbuildLocator, Boolean& invalidVSFound) in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\MSBuild\Discovery\Extensions.cs:line 61
   at OmniSharp.MSBuild.Discovery.Extensions.RegisterDefaultInstance(IMSBuildLocator msbuildLocator, ILogger logger) in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\MSBuild\Discovery\Extensions.cs:line 10
   at OmniSharp.CompositionHostBuilder.Build() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\CompositionHostBuilder.cs:line 70
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) in C:\projects\omnisharp-roslyn\src\OmniSharp.Stdio\Host.cs:line 47
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in C:\projects\omnisharp-roslyn\src\OmniSharp.Stdio.Driver\Program.cs:line 66
   at OmniSharp.HostHelpers.Start(Func`1 action) in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\HostHelpers.cs:line 29
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.502
 Commit:    c74ce8f29f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.502\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.502 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```
VS Code version:
`1.36.1`

C# Extension version:
`1.21.1`

## Steps to reproduce
1. Fresh install of VsCode
2. Install C#Extension
3. Open a folder with C# code (I uwant to use Unity3D, but any C# script has this issue for me)
4. Try intellisense (with .   or with crtl + space)
5. Only C# keywords show, no .net or Unity3D classes / methods / etc

## Expected  behavior
.net and Unity3D intellisense

## Actual behavior
Only C# keywords show, no .net or Unity3D classes / methods / etc

**Comment by filipw** [comment]
do you have any Visual Studio installed on that machine?

**Comment by jgbijlsma** [comment]
> do you have any Visual Studio installed on that machine?

Yes I do

**Comment by filipw** [comment]
which versions?

**Comment by jgbijlsma** [comment]
> which versions?

Actually I seem to have have removed it a while ago to clean my pc up. I had a version of VS 2017

**Comment by filipw** [comment]
OmniSharp tries to use VS to locate MSBuild if VS is installed. It sounds like you have a broken/not fully removed installation which is causing this. See https://social.msdn.microsoft.com/Forums/en-US/57839741-ef22-4141-9d14-cface5f8ce96/how-long-vs-2017-setup-wont-work?forum=visualstudiogeneral

You probably need to try to repair it, reinstall it or fully remove it.

**Comment by jgbijlsma** [comment]
I'll run the installer and see what I can do, Thanks for the fast help! I'll report if it worked

**Comment by jgbijlsma** [comment]
> OmniSharp tries to use VS to locate MSBuild if VS is installed. It sounds like you have a broken/not fully removed installation which is causing this. See https://social.msdn.microsoft.com/Forums/en-US/57839741-ef22-4141-9d14-cface5f8ce96/how-long-vs-2017-setup-wont-work?forum=visualstudiogeneral
> 
> You probably need to try to repair it, reinstall it or fully remove it.

I reinstalled VS2019 and intellisense works again in Code. Many thanks!
