### ISSUE TITLE
System.InvalidOperationException: Failed to convert '2.5' to type 'System.Int32'.

### ISSUE THREAD

**Issue by wrkettlitz** [OmniSharp/omnisharp-vscode#3223]
## Expected Behavior ##
It works
## Actual Behavior ##
It does not work
### OmniSharp log ###
<details>
Post the output from Output-->

```

Starting OmniSharp server at 08/08/2019, 15:55:00
    Target: c:\Users\WouterKettlitz\source\repos\Iris Api controller\Iris Online Mobiel.sln

OmniSharp server started.
    Path: C:\Users\WouterKettlitz\.vscode-insiders\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\OmniSharp.exe
    PID: 17336

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: Visual Studio Professional 2019 16.3.29123.89 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
            2: Visual Studio Build Tools 2017 15.9.28307.718 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
            3: StandAlone 16.0 - "c:\Users\WouterKettlitz\.vscode-insiders\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2019 16.3.29123.89 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
System.InvalidOperationException: Failed to convert '2.5' to type 'System.Int32'. ---> System.Exception: 2.5 is not a valid value for Int32. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, Object& result, Exception& error)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at OmniSharp.CompositionHostBuilder.Build() in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\CompositionHostBuilder.cs:line 70
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) in C:\projects\omnisharp-roslyn\src\OmniSharp.Stdio\Host.cs:line 47
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in C:\projects\omnisharp-roslyn\src\OmniSharp.Stdio.Driver\Program.cs:line 66
   at OmniSharp.HostHelpers.Start(Func`1 action) in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\HostHelpers.cs:line 29


```

</details>

### C# log ###
<details>Post the output from Output--></details>

## Environment information ##

**VSCode version**: 1.37.0-insider
**C# Extension**: 1.21.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular-BeastCode|Mikael|8.0.10|
|angular-console|nrwl|8.0.10|
|angular-schematics|cyrilletuzi|1.23.0|
|auto-close-tag|formulahendry|0.5.6|
|auto-rename-tag|formulahendry|0.1.0|
|beautify|HookyQR|1.5.0|
|better-comments|aaron-bond|2.0.5|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|csharp|ms-vscode|1.21.0|
|csharp2ts|rafaelsalguero|0.0.22|
|debugger-for-chrome|msjsdiag|4.11.7|
|docthis|joelday|0.7.1|
|gitlens|eamodio|9.9.3|
|ng-template|Angular|0.801.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|prettier-vscode|esbenp|1.9.0|
|quicktype|quicktype|12.0.46|
|rest-client|humao|0.22.0|
|theme-dracula|dracula-theme|2.18.0|
|vscode-eslint|dbaeumer|1.9.0|
|vscode-html-css|ecmel|0.2.0|
|vscode-icons|vscode-icons-team|9.2.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-language-babel|mgmcdermott|0.0.23|
|vscode-npm-script|eg2|0.3.8|
|vscode-profile-switcher|aaronpowell|0.3.3|
|vscode-typescript-next|ms-vscode|3.6.20190807|
|vscodeintellicode|VisualStudioExptTeam|1.1.8|;

</details>

**Comment by filipw** [comment]
can you post your VS Code `settings.json` and `omnisharp.json` settings if you have any?
Looks like you have a value of 2.5 for something that should be an int - for example indentation size or something like that.

**Comment by cartermp** [comment]
Closing old issue
