### ISSUE TITLE
vsdbg-ui Crash With No Information

### ISSUE THREAD

**Issue by vindicatorr** [OmniSharp/omnisharp-vscode#3255]
Please paste the output from your clipboard: OK, now that is a cool "reporting" feature!
## Issue Description ##
I've been having vsdbg-ui crashing occasionally but with no usable stack trace.
I saw https://github.com/OmniSharp/omnisharp-vscode/wiki/Diagnosting-'Debug-adapter-process-has-terminated-unexpectedly' which doesn't have information for linux, but I know a little about using "coredumpctl".
I've got ~18 entries for vsdbg-ui and the most I get from those is a Signal 11 (SEGV):
```
Process 18473 (vsdbg-ui) of user 1000 dumped core.
                
                Stack trace of thread 19320:
                #0  0x0000000700000000 n/a (n/a)
```
## Steps to Reproduce ##
Even though it supposedly crashed 18 times, I haven't yet noticed what I did when it happened.
I know a bunch of times (didn't seem like 18, but could've), my system would become horribly unresponsive for what seems like 1 minute.
I wouldn't be able to switch windows or minimize or anything.

I was just working on a "Web/Empty" project and also had another instance of vscode open to work on the browser debugging of javascript.
Yes, I know about "serverReadyAction", but there's issues that shouldn't be delved into on top of this issue.

## Logs ##
I'd love to provide some usable logs, but seem to have none, other than what I mention here.
I found the vsdbg-ui command and saw it has parameters:
```
--engineLogging: Log communications to /home/username/vsdbg-ui.log.
--consoleLogging: Log communications console.
```
That file doesn't exist and and I don't know how I would go about setting the parameters when it's already running in vscode.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
I've got "omnisharp.loggingLevel": "trace" set and I don't think you want all of that output.
There is no stack information found in there.

### C# log ###
<details>Post the output from Output-->C# here</details>
There is literally nothing in here.
The option is there, but there is no actual output.

## Environment information ##

**VSCode version**: 1.38.0-insider
**C# Extension**: 1.21.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/3.0.100-preview8-013656/

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.2.105 [/opt/dotnet/sdk]
  3.0.100-preview6-012264 [/opt/dotnet/sdk]
  3.0.100-preview8-013656 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|arm|dan-c-underwood|0.3.0|
|cortex-debug|marus25|0.3.0|
|cortex-debug-dp-stm32f1|marus25|1.0.0|
|cortex-debug-dp-stm32f4|marus25|1.0.0|
|cpptools|ms-vscode|0.24.1|
|csharp|ms-vscode|1.21.1|
|debug|webfreak|0.23.1|
|debugger-for-chrome|msjsdiag|4.11.7|
|Doxygen|bbenoist|1.0.0|
|html-snippets|abusaidm|0.2.1|
|ilspy-vscode|icsharpcode|0.7.5|
|linkerscript|ZixuanWang|1.0.0|
|msbuild-project-tools|tintoy|0.2.55|
|mssql|ms-mssql|1.5.0|
|riscv|zhwu95|0.0.4|
|view-in-browser|qinjia|0.0.5|
|vscode-eslint|dbaeumer|1.9.1|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-solution-explorer|fernandoescolar|0.3.1|
|xml|DotJoshJohnson|2.4.0|;

</details>

**Comment by gregg-miskelly** [comment]
@vindicatorr Thanks for the report! I am actually not sure why a segv would cause system unresponsiveness except maybe if your computer was busy writing out a coredump? So it *might* not be related to that. If you want to email me (greggm at microsoft.com) a private link to the coredump (ex: Drop Box, OneDrive, etc) I can try to poke around and see if there is any better hint as to what the problem might me.

Here are instructions for turning on debugger logs: [logging](https://github.com/OmniSharp/omnisharp-vscode/wiki/Enabling-C%23-debugger-logging)

**Comment by vindicatorr** [comment]
I would agree with coredump making my system busy.
Hopefully you got my email from before.
I tried to get it to crash while using the "Full method", but it just wouldn't.

I went back to the normal "Quick Method" and left it up and running, but never did any actual programming for most of the day.
When I went to shut it all down since I needed memory for something else, it crashed... even though I did nothing (no code changes, no actual use of the web server (no browser calls)) other than shut down the process.

Today, I had gone back to the "Full method" and spent the whole day programming with 3 instances of vscode open (1: CLI, 2: web server, 3: javascript/browser). I made changes in all of them, but there was just no crash.

Oh, also mind you that when I say "crash", vscode remains open even though vsdbg-ui crashes and get a memory dump.

**Comment by vindicatorr** [comment]
Just putting it out there that this issue is still around. I just hadn't been doing any dev work in quite awhile.

The same scenario of no-crashing using the full-method, and sigsegv-11 using the quick-method.

Using the quick-method, I went ahead and started an instance, loaded the page, and copied the output to a notepad.
Then I put a "*****" delimiter/separator so I could easily find the end/start of sections, rebuilt and restarted and reloaded the page and caused a sigsegv:
```
...
<- (E) {"seq":314,"type":"event","event":"output","body":{"category":"stdout","output":"Microsoft.Hosting.Lifetime: Information: Hosting environment: Development\n"}}
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development
<- (E) {"seq":315,"type":"event","event":"output","body":{"category":"stdout","output":"\u001B[40m\u001B[32minfo\u001B[39m\u001B[22m\u001B[49m: Microsoft.Hosting.Lifetime[0]\n"}}
info: Microsoft.Hosting.Lifetime[0]
<- (E) {"seq":316,"type":"event","event":"output","body":{"category":"stdout","output":"      Content root path: /home/<pathTo>/RazorWebApp\n"}}
      Content root path: /home/<pathTo>/RazorWebApp
<- (E) {"seq":317,"type":"event","event":"output","body":{"category":"stdout","output":"Microsoft.Hosting.Lifetime: Information: Content root path: /home/<pathTo>/RazorWebApp\n"}}
Microsoft.Hosting.Lifetime: Information: Content root path: /home/<pathTo>/RazorWebApp
*****
-> (C) {"command":"disconnect","arguments":{"restart":true},"type":"request","seq":17}
<- (E) {"seq":340,"type":"event","event":"output","body":{"category":"console","output":"The program '[3077169] RazorWebApp.dll' has exited with code 0 (0x0).\n"}}
The program '[3077169] RazorWebApp.dll' has exited with code 0 (0x0).
<- (E) {"seq":341,"type":"event","event":"exited","body":{"exitCode":0}}
<- (E) {"seq":342,"type":"event","event":"terminated","body":{}}
<- (E) {"seq":343,"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/DebugCompleted","data":{"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter":0,"VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"arch","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"16.5.20117.1 commit:2a72eb2aadc6bc6a29b05ebcc642a2699007df45"}}}
<- (R) {"seq":344,"type":"response","request_seq":17,"success":true,"command":"disconnect"}
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code - Insiders","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true},"type":"request","seq":1}
-> (C) {"command":"launch","arguments":{"name":".NET Core Launch (web)","type":"coreclr","request":"launch","preLaunchTask":"build webapp","program":"/home/<pathTo>/RazorWebApp/bin/Debug/netcoreapp5.0/RazorWebApp.dll","args":[],"cwd":"/home/<pathTo>/RazorWebApp","stopAtEntry":false,"env":{"ASPNETCORE_ENVIRONMENT":"Development","ASPNETCORE_URLS":"https://localhost:5001;http://localhost:5000"},"sourceFileMap":{"/Views":"/home/<pathTo>/Views"},"logging":{"engineLogging":false},"internalConsoleOptions":"openOnSessionStart","__sessionId":"3e799715-2304-459c-b490-5fcc4b447c93"},"type":"request","seq":2}
<- (E) {"seq":3,"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n"}}
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
<- (R) {"seq":4,"type":"response","request_seq":2,"success":true,"command":"launch"}
...
```
While I don't know what I'd be looking for, I'm not seeing any error/failure/crash standing out in the log.

I DID also notice that it wasn't just sigsegv, but that is BY FAR the most prevalent. There was also signal-6 (sigiot):
```
       Message: Process 3070873 (vsdbg-ui) of user 1000 dumped core.
                
                Stack trace of thread 3070873:
                #0  0x00007beab43e5ce5 raise (libc.so.6 + 0x3bce5)
                #1  0x00007beab43cf857 abort (libc.so.6 + 0x25857)
                #2  0x00007beab44292b0 __libc_message (libc.so.6 + 0x7f2b0)
                #3  0x00007beab443074a malloc_printerr (libc.so.6 + 0x8674a)
                #4  0x00007beab4432662 _int_free (libc.so.6 + 0x88662)
                #5  0x00007beab43e85e3 __run_exit_handlers (libc.so.6 + 0x3e5e3)
                #6  0x00007beab43e86ee exit (libc.so.6 + 0x3e6ee)
                #7  0x00007beab43d102a __libc_start_main (libc.so.6 + 0x2702a)
                #8  0x000000000040194b n/a (/home/username/.vscode-insiders/extensions/ms-dotnettools.csharp-1.21.17/.debugger/vsdbg-ui + 0x194b)
```

I noticed my OP mentioned it happens for web projects and that's still the same this time. I don't recall if it happens when dealing with console projects.

**Comment by vindicatorr** [comment]
I FINALLY caught a coredump (sort of, aborted) using the full-method.
It was probably a fluke and I couldn't tell you the cause. I just started to run my program (which I've done many times before) that I'm working through, and it just hung up (didn't hit any breakpoints).
So I tried to start it again, but all I saw was the small cycling progress bar, but it never ran.
I noticed my system was sluggish, so I looked into the cause for that and saw the coredump happening.
Then I looked at my vsdbg full-method (vsdbg-ui --server), to see if anything was in there (never was before) and I saw:
```
...
>> accepted connection from client
>> client connection closed
>> accepted connection from client
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Ilrun.AbstractObjectSlot.SetField(Slot value, FieldInfo field)
   at Ilrun.MscorlibHooks.System_Array.InternalGetReference(VirtualMachine vm, MethodBase method, CallArgs args)
   at Ilrun.VirtualMachine2.ExecuteHookedMethod(HookedMethod hook, CallArgs args)
   at Ilrun.VirtualMachine2.ForwardLoop()
   at Ilrun.VirtualMachine2.RunForward()
   at Ilrun.VirtualMachine2.ExecuteMethodInternal(MethodBase method, CallArgs args, IVirtualStackFrame inspectionFrame)
   at Ilrun.VirtualMachine2.ExecuteMethod(MethodBase method, CallArgs args)
   at Microsoft.VisualStudio.VIL.VisualStudioHost.VilEvaluationServices.EvaluateToString(DkmInspectionContext inspectionContext, VilEvaluationResult evalResult)
   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmClrValueInspectionCallback_EvaluateToString(IntPtr pvClassInfo, IntPtr ClrValue, IntPtr InspectionContext, IntPtr& Result)
   at Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.NativeDkmClrValue.Proc3AF35B63B30CFA5A1D212BEE27AC26D5(IntPtr pThis, IntPtr InspectionContext, IntPtr& Result)
   at Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrValue.EvaluateToString(DkmInspectionContext InspectionContext)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.Formatter.GetValueString(DkmClrValue value, DkmInspectionContext inspectionContext, ObjectDisplayOptions options, GetValueFlags flags)
   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmClrFormatter_GetValueString(IntPtr pvClassInfo, IntPtr ClrValue, IntPtr InspectionContext, IntPtr FormatSpecifiers, IntPtr& ValueString)
   at Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.NativeDkmClrValue.Proc6C4DE7505B979C71E3E02EB952475CC3(IntPtr pThis, IntPtr InspectionContext, IntPtr FormatSpecifiers, IntPtr& ValueString)
   at Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrValue.GetValueString(DkmInspectionContext InspectionContext, ReadOnlyCollection`1 FormatSpecifiers)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.GetResult(DkmInspectionContext inspectionContext, EvalResult result, DkmClrType declaredType, DkmClrCustomTypeInfo declaredTypeInfo, String displayName, String displayValue, String displayType, Boolean useDebuggerDisplay)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.GetResultAndContinue(EvalResult result, WorkList workList, DkmClrType declaredType, DkmClrCustomTypeInfo declaredTypeInfo, DkmInspectionContext inspectionContext, Boolean useDebuggerDisplay, CompletionRoutine`1 completionRoutine)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.GetRootResultAndContinue(DkmClrValue value, WorkList workList, DkmClrType declaredType, DkmClrCustomTypeInfo declaredTypeInfo, DkmInspectionContext inspectionContext, String name, String fullName, ReadOnlyCollection`1 formatSpecifiers, CompletionRoutine`1 completionRoutine)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.<>c__DisplayClass7_0.<Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmClrResultProvider.GetResult>b__1()
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.WorkList.Execute()
Fatal error. Internal CLR error. (0x80131506)
   at Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.NativeDkmClrValue.Proc3AF35B63B30CFA5A1D212BEE27AC26D5(IntPtr, IntPtr, IntPtr ByRef)
   at Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.NativeDkmClrValue.Proc3AF35B63B30CFA5A1D212BEE27AC26D5(IntPtr, IntPtr, IntPtr ByRef)
   at Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrValue.EvaluateToString(Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.Formatter.GetValueString(Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrValue, Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext, Microsoft.CodeAnalysis.ObjectDisplayOptions, Microsoft.CodeAnalysis.ExpressionEvaluator.GetValueFlags)
   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmClrFormatter_GetValueString(IntPtr, IntPtr, IntPtr, IntPtr, IntPtr ByRef)
   at Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.NativeDkmClrValue.Proc6C4DE7505B979C71E3E02EB952475CC3(IntPtr, IntPtr, IntPtr, IntPtr ByRef)
   at Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.NativeDkmClrValue.Proc6C4DE7505B979C71E3E02EB952475CC3(IntPtr, IntPtr, IntPtr, IntPtr ByRef)
   at Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrValue.GetValueString(Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext, System.Collections.ObjectModel.ReadOnlyCollection`1<System.String>)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.GetResult(Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext, Microsoft.CodeAnalysis.ExpressionEvaluator.EvalResult, Microsoft.VisualStudio.Debugger.Clr.DkmClrType, Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrCustomTypeInfo, System.String, System.String, System.String, Boolean)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.GetResultAndContinue(Microsoft.CodeAnalysis.ExpressionEvaluator.EvalResult, WorkList, Microsoft.VisualStudio.Debugger.Clr.DkmClrType, Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrCustomTypeInfo, Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext, Boolean, Microsoft.CodeAnalysis.ExpressionEvaluator.CompletionRoutine`1<Microsoft.VisualStudio.Debugger.Evaluation.DkmEvaluationResult>)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.GetRootResultAndContinue(Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrValue, WorkList, Microsoft.VisualStudio.Debugger.Clr.DkmClrType, Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrCustomTypeInfo, Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext, System.String, System.String, System.Collections.ObjectModel.ReadOnlyCollection`1<System.String>, Microsoft.CodeAnalysis.ExpressionEvaluator.CompletionRoutine`1<Microsoft.VisualStudio.Debugger.Evaluation.DkmEvaluationResult>)
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider+<>c__DisplayClass7_0.<Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmClrResultProvider.GetResult>b__1()
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider+WorkList.Execute()
   at Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmClrResultProvider.GetResult(Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrValue, Microsoft.VisualStudio.Debugger.DkmWorkList, Microsoft.VisualStudio.Debugger.Clr.DkmClrType, Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrCustomTypeInfo, Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext, System.Collections.ObjectModel.ReadOnlyCollection`1<System.String>, System.String, System.String, Microsoft.VisualStudio.Debugger.DkmCompletionRoutine`1<Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmEvaluationAsyncResult>)
   at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmClrResultProvider_GetResult(IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr, IntPtr)
Aborted (core dumped)
```

I'm just keeping a full-method instance live on a console all of the time now since there's the least number of crashes that way.
This just happened to be the first one I caught this way.
