### ISSUE TITLE
"Initialize from parameter" contextually fails.

### ISSUE THREAD

**Issue by Xarkam** [OmniSharp/omnisharp-vscode#3498]
## Steps to Reproduce ##
Given this constructor
![image](https://user-images.githubusercontent.com/331816/71971640-4dd42800-320b-11ea-9be0-295b1837e0cc.png)
open contextual menu and select initialize field (any of them)
![image](https://user-images.githubusercontent.com/331816/71971688-66dcd900-320b-11ea-8a08-acd462695a70.png)
## Expected Behavior ##
Not fail and perfom the command.
If the contextual menu is opened from constructor line, no failure.
## Actual Behavior ##
See logs after.
## Logs ##
```
[2020-01-08 11:29:09.390] [exthost] [error] Error: Invalid arguments
    at new f (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:362:501)
    at new f (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:359:919)
    at CodeActionProvider.initializeMemberFromCtor (c:\Users\benja\.vscode\extensions\jchannon.csharpextensions-1.3.1\out\src\codeActionProvider.js:139:30)
    at v._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:538:925)
    at v._doExecuteCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:538:100)
    at v.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:538:6)
    at y._executeConvertedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:540:832)
    at v._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:538:925)
    at v.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:539:295)
    at p._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:663:275)
    at p._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:662:971)
    at p._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:661:639)
    at p._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:660:468)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:658:691
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:893)
    at _.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:189:274)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:820:285
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:893)
    at _.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:189:274)
    at t.PersistentProtocol._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:193:629)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:190:824
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:893)
    at p.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:737)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:89
    at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:195:68)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) csharpextensions.initializeMemberFromCtor
```
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
SDK .NET Core (refl�tant tous les global.json)�:
 Version:   3.1.100
 Commit:    cd82f021f4

Environnement d'ex�cution�:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|8.3.0|
|angular2-switcher|infinity1207|0.2.0|
|better-comments|aaron-bond|2.0.5|
|Bookmarks|alefragnani|10.6.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|code-settings-sync|Shan|3.4.3|
|code-spell-checker|streetsidesoftware|1.7.20|
|csharp|ms-vscode|1.21.9|
|csharpextensions|jchannon|1.3.1|
|csharpfixformat|Leopotam|0.0.84|
|debugger-for-chrome|msjsdiag|4.12.4|
|docomment|k--kato|0.1.8|
|docs-article-templates|docsmsft|0.2.7|
|docs-images|docsmsft|0.0.3|
|docs-metadata|docsmsft|1.0.4|
|docs-preview|docsmsft|0.3.36|
|docs-yaml|docsmsft|0.2.4|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.14.4|
|emoji-code|idleberg|0.8.2|
|file-tree-to-text-generator|d-koppenhagen|1.2.1|
|git-graph|mhutchie|1.20.0|
|githistory|donjayamanne|0.4.13|
|gitlens|eamodio|10.2.0|
|html-css-class-completion|Zignd|1.19.0|
|jungle-night|tweakimp|1.3.0|
|language-gettext|mrorz|0.1.1|
|LinkCheckMD|blackmist|0.3.1|
|ng-template|Angular|0.900.3|
|path-intellisense|christian-kohler|1.4.2|
|powershell|ms-vscode|2019.12.0|
|prettier-vscode|esbenp|3.18.0|
|python|ms-python|2020.1.57204|
|remote-wsl|ms-vscode-remote|0.41.7|
|rest-client|humao|0.23.0|
|restructuredtext|lextudio|116.0.0|
|trailing-spaces|shardulm94|0.3.1|
|vetur|octref|0.22.6|
|vscode-angular2-files|alexiv|1.6.2|
|vscode-coverlet|urbanoanderson|1.0.1|
|vscode-edge-devtools|ms-edgedevtools|1.0.6|
|vscode-eslint|dbaeumer|2.0.11|
|vscode-firefox-debug|firefox-devtools|2.6.1|
|vscode-html-css|ecmel|0.2.3|
|vscode-icons|vscode-icons-team|9.7.0|
|vscode-markdownlint|DavidAnson|0.33.0|
|vscode-npm-script|eg2|0.3.10|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-power-mode|hoovercj|2.2.0|
|vscode-reveal|evilz|4.0.3|
|vscode-solution-explorer|fernandoescolar|0.3.7|
|vscode-spotify|shyykoserhiy|3.1.0|
|vscode-sqlite|alexcvzz|0.8.1|
|vscode-taskexplorer|spmeesseman|1.21.0|
|vscode-todo-plus|fabiospampinato|4.14.1|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscode-versionlens|pflannery|0.24.0|
|vscode-wakatime|WakaTime|2.2.1|
|vscode-yaml|redhat|0.6.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.2|
|vsliveshare|ms-vsliveshare|1.0.1404|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by filipw** [comment]
can you post your OmniSharp log? or is the exception at VS Code level only?
does it reproduce every time for you?

**Comment by filipw** [comment]
actually looking at the log, this issue is not from the C# extension but from jchannon.csharpextensions-1.3.1

please uninstall it or open the issue in the repo of that extension 😀

**Comment by Xarkam** [comment]
Thanks.
