### ISSUE TITLE
System.BadImageFormatException after Omnisharp started

### ISSUE THREAD

**Issue by Freakazoid182** [OmniSharp/omnisharp-vscode#3543]
## Issue Description ##

I get a `System.BadImageFormatException` after OmniSharp started. OmniSharp logs don't show any errors. But the "Window" log in Vs Code, logs the exception below.

I can navigate through my code and Code Lens is working. Code completion is not working though.

Apparently the `Microsoft.CodeAnalysis.CSharp.Features` assembly is of a bad image format (wrong bitness?). I noticed this assembly is provided with the OmniSharp extension, so i'm assuming it's trying to access that. I've tried re-installing VS Code, I've removed the `.vscode\extensions` folder. Re-installed OmniSharp and even re-installed Visual Studio.

I'm really just trying to figure out what might be wrong with my setup. I most likely just need to remove and re-install some application, but I cannot figure out what that is. I've tried re-installing everything I could think of already.

## Steps to Reproduce ##

I'm pretty sure it's related to my machine setup. I've asked colleagues with similar setups and they cannot reproduce this issue.

## Expected Behavior ##

No errors and working code completion (Intellisense)

## Actual Behavior ##

Intellisense code completion not working.

## Logs ##

`Window (Log)`:
```
[renderer1] [error] "System.InvalidOperationException: Failed to create instrance of Microsoft.CodeAnalysis.CSharp.UseCompoundAssignment.CSharpUseCompoundAssignmentCodeFixProvider 
  in Microsoft.CodeAnalysis.CSharp.UseCompoundAssignment.CSharpUseCompoundAssignmentCodeFixProvider, Microsoft.CodeAnalysis.CSharp.Features, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
  ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

at Microsoft.CodeAnalysis.CSharp.UseCompoundAssignment.CSharpUseCompoundAssignmentCodeFixProvider..ctor()
--- End of inner exception stack trace ---
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
at OmniSharp.Utilities.ReflectionExtensions.CreateInstance[T](Type type) in D:\a\1\s\src\OmniSharp.Shared\Utilities\ReflectionExtensions.cs:line 122
--- End of inner exception stack trace ---
at OmniSharp.Utilities.ReflectionExtensions.CreateInstance[T](Type type) in D:\a\1\s\src\OmniSharp.Shared\Utilities\ReflectionExtensions.cs:line 120
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
at System.Linq.Buffer1..ctor(IEnumerable1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source)
at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable1 items)
at OmniSharp.Services.AbstractCodeActionProvider..ctor(String providerName, ImmutableArray1 assemblies) in D:\\a\\1\\s\\src\\OmniSharp.Roslyn\\Services\\AbstractCodeActionProvider.cs:line 39
at lambda_method(Closure , LifetimeContext , CompositionOperation )
at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_21.b__4(ExportDescriptor e)
at System.Linq.Enumerable.WhereSelectArrayIterator2.MoveNext()
at System.Linq.Buffer1..ctor(IEnumerable1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source)
at lambda_method(Closure , LifetimeContext , CompositionOperation )
at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
at lambda_method(Closure , LifetimeContext , CompositionOperation )
at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
at System.Composition.Hosting.Providers.Lazy.LazyWithMetadataExportDescriptorProvider.<>c__DisplayClass2_22.<GetLazyDefinitions>b__4()
at System.Lazy1.CreateValue()
at System.Lazy1.LazyInitValue()
at OmniSharp.Endpoint.EndpointHandler2.<>c.b__11_0(Lazy2 export) in D:\\a\\1\\s\\src\\OmniSharp.Host\\Endpoint\\EndpointHandler.cs:line 80
at System.Linq.Enumerable.WhereSelectArrayIterator2.MoveNext()
at System.Linq.Enumerable.d__591.MoveNext()
at System.Linq.Lookup2.Create[TSource](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer1 comparer)
at System.Linq.GroupedEnumerable3.GetEnumerator()
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer1 comparer)
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable1 source, Func2 keySelector, Func2 elementSelector)
at OmniSharp.Endpoint.EndpointHandler2.LoadExportHandlers(IEnumerable1 handlers) in D:\a\1\s\src\OmniSharp.Host\Endpoint\EndpointHandler.cs:line 88
at System.Lazy1.CreateValue()\r\n--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Lazy1.get_Value()
at OmniSharp.Endpoint.EndpointHandler2.<HandleAllRequest>d__21.MoveNext() in D:\\a\\1\\s\\src\\OmniSharp.Host\\Endpoint\\EndpointHandler.cs:line 243
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at OmniSharp.Endpoint.EndpointHandler2.<Process>d__16.MoveNext() in D:\\a\\1\\s\\src\\OmniSharp.Host\\Endpoint\\EndpointHandler.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at OmniSharp.Stdio.Host.d__13.MoveNext() in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 215"
```

### OmniSharp log ###
<details>
Starting OmniSharp server at 31-1-2020 09:10:13
    Target: c:\Projects\MyProject\MySolution.sln

OmniSharp server started.
    Path: c:\Users\ThisIsMe\\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\OmniSharp.exe
    PID: 15272

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Professional 2019 16.4.29728.190 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"
            2: StandAlone 16.3 - "c:\Users\ThisIsMe\\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Professional 2019 16.4.29728.190 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin"

... continues loading projects without errors
</details>

### C# log ###
<details>
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (32146 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (47489 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (50022 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

Finished
</details>

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.9|;

</details>

**Comment by filipw** [comment]
can you try installing latest version from here https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.10?
instructions: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by Freakazoid182** [comment]
> can you try installing latest version from here https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.10?
> instructions: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

Ah, did not try that before. But regrettably I still throws the same exception on that version too

**Comment by Freakazoid182** [comment]
![image](https://user-images.githubusercontent.com/5238563/73529569-34438c00-4417-11ea-8365-bdbed8d221b3.png)

This is the dll information of the assembly it's trying to load. Not sure if that helps in any way

**Comment by filipw** [comment]
thanks, I have not seen this before - can't really reproduce this 😟
@JoeRobich do you have any ideas?

**Comment by filipw** [comment]
could you also try to go to the location of the assembly and right-mouse click it. Then go to the General tab and click “unblock” and see if it helps?

**Comment by Freakazoid182** [comment]
Thanks for that suggestion. I don't see the Unblock button, so I'm assuming the dll is trusted already.

I've also checked the dll in dotPeek to see if there's anything unusual, but I cannot see anything out of the ordinary.

![image](https://user-images.githubusercontent.com/5238563/73747236-514dc700-4757-11ea-953c-d041669f85e3.png)

Does this look ok for you to?

I'm starting to think there's most likely nothing wrong with the assembly. But I'm pretty much out of idea's of what else it may be...

**Comment by cartermp** [comment]
I haven't seen this nor been able to reproduce it with the latest bits. If you see this with the latest version of the plugin, let us know and we can re-open this.

**Comment by Freakazoid182** [comment]
I haven't been able to reproduce it either on any other machine. I'm going to stop trying to look into this this too. I hope it'll magically resolve itself at some point 🤞 . Thanks for the help!

**Comment by koliyo** [comment]
I have started getting this last few days, not sure when
```
ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.2-beta.38
```

```
[fail]: OmniSharp.MSBuild.ProjectManager
        Error occurred while processing project updates: System.BadImageFormatException: type 0x00 not handled in do_mono_metadata_parse_type on image /Users/nils/.vscode/extensions/ms-dotnettools.csharp-1.21.18/.omnisharp/1.35.2-beta.38/omnisharp/Microsoft.CodeAnalysis.CSharp.dll
File name: 'Microsoft.CodeAnalysis.CSharp'
  at Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions.Equals (System.Object obj) [0x00000] in <c2962771cf0648a1b0a500975001be59>:0 
```

**Comment by jmbeach** [comment]
I don't know if this helps at all (and it even seems kind of bizarre to me), but the DLL doesn't seem to be the problem. 

I can resolve this error by building omnsiharp with the following change to `src/OmniSharp.Roslyn/Services/AbstractCodeActionProvider.cs `


```diff
--- a/src/OmniSharp.Roslyn/Services/AbstractCodeActionProvider.cs
+++ b/src/OmniSharp.Roslyn/Services/AbstractCodeActionProvider.cs
@@ -37,13 +37,13 @@ protected AbstractCodeActionProvider(string providerName, ImmutableArray<Assembl
                 .ToImmutableArray();
 
             this.CodeFixProviders = types
-                .Where(t => typeof(CodeFixProvider).IsAssignableFrom(t))
+                .Where(t => typeof(CodeFixProvider).IsAssignableFrom(t) && t.Name != "CSharpUseCompoundAssignmentCodeFixProvider")
                 .Select(type => type.CreateInstance<CodeFixProvider>())
                 .Where(instance => instance != null)
                 .ToImmutableArray();
 
             this.CodeDiagnosticAnalyzerProviders = types
-                .Where(t => typeof(DiagnosticAnalyzer).IsAssignableFrom(t))
+                .Where(t => typeof(DiagnosticAnalyzer).IsAssignableFrom(t) && t.Name != "CSharpUseCompoundAssignmentDiagnosticAnalyzer")
                 .Select(type => type.CreateInstance<DiagnosticAnalyzer>())
                 .Where(instance => instance != null)
                 .ToImmutableArray();
```

To clarify, I was receiving this error from vscode running v1.37.5 originally. Then I cloned the source, checked out v1.37.5 tag and still got the error with the output executable. I was very surprised to find that some types within the DLL Microsoft.CodeAnalysis.CSharp.Features load successfully.

It turns out that the only problem types are "CSharpUseCompoundAssignmentCodeFixProvider" and "CSharpUseCompoundAssignmentDiagnosticAnalyzer". I think I can live without them, so my custom build suits my needs, but I wonder what's special about those classes.
