### ISSUE TITLE
OmniSharp doesn't like View calling Controller method(Razor). Impossible to fold/unfold regions.

### ISSUE THREAD

**Issue by 8m0** [OmniSharp/omnisharp-vscode#3574]
I work with MVC in VS Code. And i can't unfold my regions because of OmniSharp. (IntelJ doesn't work as well, like no modules are being used.). Because one of my View .cshtml file has this string:
`let str = "@Html.Raw(@myController.method())";`

> Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
at OmniSharp.Helpers.LocationExtensions.GetQuickFix(Location location, OmniSharpWorkspace workspace) in D:\a\1\s\src\OmniSharp.Roslyn.CSharp\Helpers\LocationExtensions.cs:line 24
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext() at System.Linq.Enumerable.<DistinctIterator>d__641.MoveNext()
at System.Linq.Buffer1..ctor(IEnumerable1 source)
at System.Linq.OrderedEnumerable`1.d__1.MoveNext()
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
at OmniSharp.Protocol.Packet.ToString() in D:\a\1\s\src\OmniSharp.Host\Protocol\Packet.cs:line 22
at System.IO.TextWriter.WriteLine(Object value)
at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
at OmniSharp.Services.SharedTextWriter.ProcessWriteQueue() in D:\a\1\s\src\OmniSharp.Host\Services\SharedTextWriter.cs:line 48
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

-latest
-Windows 10

Steps to make this bug appear:
1.Open Vs Code with enabled OmniSharp (MVC project).
2.Open .cs file with regions in it (Controller).
3.Then open any .cshtml file (any View, .cshtml should contain `let str = "@Html.Raw(@myController.mymethod())";`).
4.Get back to the .cs file with regions, and unfold possibility is gone.

Does this issue occur when all extensions are disabled?: No (OmniSharp)

![no_unfold](https://user-images.githubusercontent.com/33127649/74430235-cb1f3800-4e5c-11ea-848f-b270e2baac46.png)
How do i fix that? I don't want to remove the string.

**Comment by filipw** [comment]
this is fixed in https://github.com/OmniSharp/omnisharp-roslyn/pull/1707

**Comment by 8m0** [comment]
> this is fixed in [OmniSharp/omnisharp-roslyn#1707](https://github.com/OmniSharp/omnisharp-roslyn/pull/1707)

ok i see, but how do i update it in my VS Code project? It shows me the last update 7 days ago.

**Comment by filipw** [comment]
it should be part of the next release.

**Comment by 8m0** [comment]
> it should be part of the next release.

how long estimated?

**Comment by filipw** [comment]
I don't know - you should check with @JoeRobich he is releasing the C# Extension, we release the OmniSharp server only.

**Comment by 8m0** [comment]
thanks
