### ISSUE TITLE
[fail]: OmniSharp.MSBuild.ProjectManager Attempted to update project that is not loaded

### ISSUE THREAD

**Issue by MilosNj** [OmniSharp/omnisharp-vscode#3635]
## Issue Description ##
When I started working on my C# project, this issue came up.
This is the {projectName}.csproj file:

Project Sdk="Microsoft.NET.Sdk"

PropertyGroup
OutputType>Exe</OutputType
TargetFramework>netcoreapp3.1</TargetFramework
PropertyGroup

Project

## Steps to Reproduce ##
Omnisharp updated itself
## Expected Behavior ##
Normal project loading for Omnisharp
## Actual Behavior ##
Omnisharp won't load and update project
### OmniSharp log ###
Starting OmniSharp server at 3/6/2020, 10:50:49 PM
    Target: c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators

OmniSharp server started.
    Path: c:\Users\Milos\.vscode\extensions\ms-dotnettools.csharp-1.21.13\.omnisharp\1.34.14-beta.8\OmniSharp.exe
    PID: 9556

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.4.29806.167 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.4 - "C:\Users\Milos\.vscode\extensions\ms-dotnettools.csharp-1.21.13\.omnisharp\1.34.14-beta.8\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.4.29806.167 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators\BooleanOperators.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators\BooleanOperators.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators' on host 9168.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators\BooleanOperators.csproj'.
c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators\BooleanOperators.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators\BooleanOperators.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 129
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 72
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 99
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 308

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\Milos\Documents\CodeC#\Chapter03\BooleanOperators\BooleanOperators.csproj

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.42.1
**C# Extension**: 1.21.13

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.13|
|csharpextensions|jchannon|1.3.1|
|docomment|k--kato|0.1.8|
|ilspy-vscode|icsharpcode|0.7.10|
|rest-client|humao|0.23.1|
|sharppad|jmazouri|1.1.0|;

</details>

**Comment by MilosNj** [comment]
Fixed the issue by adding:
{
   "MSBuild": {
       "UseLegacySdkResolver": true
   }
}
to ~/.omnisharp/omnisharp.json

**Comment by poorvasingh04** [comment]
I was also facing the same issue. After going through the logs, I realized the real issue is :
"The SDK 'Microsoft.NET.Sdk' specified could not be found."

I installed latest stable Mono from here (6.8.0):
https://www.mono-project.com/download/stable/

Then opened ~bash_profile and exported framework path of mono:
export FrameworkPathOverride=/Library/Frameworks/Mono.framework/Versions/Current

Works fine for me.
