### ISSUE TITLE
NullReferenceException in Test Manager

### ISSUE THREAD

**Issue by xsoheilalizadeh** [OmniSharp/omnisharp-vscode#3797]
## Issue Description ##
I opened a unit test class file and saw a message with the following exception message.

```c#
Failed to start debugger: "System.NullReferenceException: Object reference not set to an instance of an object.
   at OmniSharp.DotNetTest.TestManager.SendMessage[T](String messageType, T payload) in D:\a\1\s\src\OmniSharp.DotNetTest\TestManager.cs:line 239
   at OmniSharp.DotNetTest.VSTestManager.<DiscoverTestsAsync>d__12.MoveNext() in D:\a\1\s\src\OmniSharp.DotNetTest\VSTestManager.cs:line 278
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.DotNetTest.VSTestManager.<DebugGetStartInfoAsync>d__8.MoveNext() in D:\a\1\s\src\OmniSharp.DotNetTest\VSTestManager.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.DotNetTest.Services.DebugTestClassService.<Handle>d__2.MoveNext() in D:\a\1\s\src\OmniSharp.DotNetTest\Services\DebugTestClassService.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() in D:\a\1\s\src\OmniSharp.Host\Endpoint\EndpointHandler.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in D:\a\1\s\src\OmniSharp.Host\Endpoint\EndpointHandler.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 215"
```

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.46.0-insider
**C# Extension**: 1.21.19

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.3.20216.6
 Commit:    9f62a32109

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.3.20216.6\

Host (useful for support):
  Version: 5.0.0-preview.3.20214.6
  Commit:  b037784658

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.2.108 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.3.20216.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.3.20215.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20214.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.3.20214.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.3.2|
|cake-vscode|cake-build|0.13.0|
|code-spell-checker|streetsidesoftware|1.8.0|
|cpptools|ms-vscode|0.28.0|
|crates|serayuzgur|0.4.9|
|csharp|ms-dotnettools|1.21.19|
|cucumberautocomplete|alexkrechik|2.14.1|
|debugger-for-edge|msjsdiag|1.0.14|
|dotnet-test-explorer|formulahendry|0.7.1|
|gitlens|eamodio|10.2.1|
|jshint|dbaeumer|0.10.21|
|markdown-all-in-one|yzhang|2.8.0|
|mssql|ms-mssql|1.9.0|
|ng-template|Angular|0.901.7|
|npm-intellisense|christian-kohler|1.3.0|
|powershell-preview|ms-vscode|2020.5.0|
|remote-wsl|ms-vscode-remote|0.44.2|
|rust-analyzer|matklad|0.3.173-nightly|
|support|nuke|0.2.2|
|toml|be5invis|0.4.0|
|vscode-docker|ms-azuretools|1.2.0|
|vscode-eslint|dbaeumer|2.1.5|
|vscode-icons|vscode-icons-team|10.1.1|
|vscode-lldb|vadimcn|1.5.0|
|vscode-npm-script|eg2|0.3.11|
|vscode-pull-request-github|GitHub|0.16.0|
|vscode-svg-previewer|vitaliymaz|0.5.2|
|vscode-theme-onelight|akamud|2.2.1|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by cartermp** [comment]
@xsoheilalizadeh do you have a test project that you can share where this reproduces? Thanks!

**Comment by cartermp** [comment]
Closing out as no additional info was given
