### ISSUE TITLE
dotnet project error: The SDK 'Microsoft.NET.Sdk' specified could not be found

### ISSUE THREAD

**Issue by ashishjos** [OmniSharp/omnisharp-vscode#3815]
## Issue Description ##
Creating a simple application from https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code
## Steps to Reproduce ##
The code execution from command line works ok, which is "dotnet run", but when loading this in Visual Studio get errors when omnisharp tries to load this project, indicating exception "Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found" 
## Expected Behavior ##
Project should get loaded in Visual Studio
### OmniSharp log ###
<details>Starting OmniSharp server at 5/30/2020, 6:25:12 PM
    Target: d:\Code Trials\HelloWorld

OmniSharp server started.
    Path: c:\Users\ashishj\.vscode\extensions\ms-dotnettools.csharp-1.22.0\.omnisharp\1.35.2\OmniSharp.exe
    PID: 10088

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.4.29806.167 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: StandAlone 16.4 - "c:\Users\ashishj\.vscode\extensions\ms-dotnettools.csharp-1.22.0\.omnisharp\1.35.2\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.4.29806.167 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\Code Trials\HelloWorld'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'd:\Code Trials\HelloWorld'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\Code Trials\HelloWorld\HelloWorld.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\Code Trials\HelloWorld'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\Code Trials\HelloWorld\HelloWorld.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\Code Trials\HelloWorld' on host 21220.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'd:\Code Trials\HelloWorld\HelloWorld.csproj'.
d:\Code Trials\HelloWorld\HelloWorld.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  d:\Code Trials\HelloWorld\HelloWorld.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 129
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 72
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 104
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 309

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: d:\Code Trials\HelloWorld\HelloWorld.csproj
</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.45.1
**C# Extension**: 1.22.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.202
 Commit:    6ea70c8dca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.202\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.11|
|azure-iot-edge|vsciot-vscode|1.22.0|
|azure-iot-toolkit|vsciot-vscode|2.16.1|
|azure-iot-tools|vsciot-vscode|0.3.0|
|cmake-tools|ms-vscode|1.4.0|
|cpptools|ms-vscode|0.28.1|
|csharp|ms-dotnettools|1.22.0|
|java|redhat|0.62.0|
|python|ms-python|2020.5.80290|
|remote-containers|ms-vscode-remote|0.117.1|
|remote-ssh|ms-vscode-remote|0.51.0|
|remote-ssh-edit|ms-vscode-remote|0.51.0|
|remote-wsl|ms-vscode-remote|0.44.2|
|vscode-arduino|vsciot-vscode|0.3.0|
|vscode-docker|ms-azuretools|1.2.1|
|vscode-iot-device-cube|vsciot-vscode|0.2.0|
|vscode-iot-workbench|vsciot-vscode|0.14.0|
|vscode-java-debug|vscjava|0.26.0|
|vscode-java-dependency|vscjava|0.10.2|
|vscode-java-pack|vscjava|0.9.1|
|vscode-java-test|vscjava|0.22.4|
|vscode-maven|vscjava|0.21.4|
|vscode-remote-extensionpack|ms-vscode-remote|0.20.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.7|;

</details>

**Comment by shametim** [comment]
Possible duplicate of #3541

**Comment by cartermp** [comment]
Closing as duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/3541
