### ISSUE TITLE
No longer able to debug Xunit tests

### ISSUE THREAD

**Issue by franck-schmidlin** [OmniSharp/omnisharp-vscode#3834]
## Issue Description ##
I have just reopened a project I was working on about a week ago, and I am no longer able to debug my unit tests from codelense.
[omnisharplog_doesNOTwork.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4751494/omnisharplog_doesNOTwork.txt)

I have tried against a brand new skeleton xunit project (`dotnet new xunit`) and that still works.

My normal project is not that complicated.
I unfortunately do not program every day, so all I can tell is this works about 10 days ago.
Can't be sure what version I was on at the time, I am on vscode insiders and update everytime an update is available.

Just in case, I have updated my visual studio build tools to the lates version, no effect.

## Steps to Reproduce ##
Starting from an existing Test project, use the 'Debug test' codelense option

## Expected Behavior ##

step into the code
## Actual Behavior ##

Error message: 
```
System.InvalidOperationException: The debugger could not be started
   at OmniSharp.DotNetTest.Services.DebugTestService.Handle(DebugTestGetStartInfoRequest request) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.DotNetTest\\\\Services\\\\DebugTestService.cs:line 42
   at OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 198
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 215\"",

```

### OmniSharp log ###
<details>

See attached omnisharplog_doesNOTwork.txt.
See attached omnisharplog_doesNOTwork.txt for comparison (MUCH simpler project)

</details>

### C# log ###
<details>Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
</details>

## Environment information ##

**VSCode version**: 1.46.0-insider
**C# Extension**: 1.22.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|aws-toolkit-vscode|amazonwebservices|1.10.0|
|binary-viewer|momoto|0.0.1|
|clang-format|xaver|1.9.0|
|cpptools|ms-vscode|0.28.2|
|csharp|ms-dotnettools|1.22.0|
|csharpextensions|kreativ-software|1.3.4|
|csharpfixformat|Leopotam|0.0.84|
|datetime|rid9|2.0.1|
|docomment|k--kato|0.1.11|
|gitlens|eamodio|10.2.1|
|Go|ms-vscode|0.14.3|
|gradle-language|naco-siren|0.2.3|
|java|redhat|0.62.0|
|local-history|xyz|1.8.1|
|markdown-preview-enhanced|shd101wyy|0.5.12|
|msbuild-tools|sterin|0.0.12|
|opa|tsandall|0.6.0|
|open-in-browser|techer|2.0.0|
|php-debug|felixfbecker|1.13.0|
|php-intellisense|felixfbecker|2.3.14|
|php-pack|felixfbecker|1.0.2|
|phpstan|breezelin|1.1.3|
|plantuml|jebbs|2.13.12|
|powershell-preview|ms-vscode|2020.6.1|
|prettier-vscode|esbenp|5.0.0|
|python|ms-python|2020.5.86398|
|remote-containers|ms-vscode-remote|0.122.1|
|remote-wsl|ms-vscode-remote|0.44.2|
|rest-client|humao|0.23.2|
|screen-recorder|wk-j|0.0.2|
|spellright|ban|3.0.50|
|team|ms-vsts|1.161.0|
|terraform|mauve|1.4.0|
|unique-window-colors|stuart|1.0.51|
|vscode-checkstyle|shengchen|1.3.3|
|vscode-docker|ms-azuretools|1.2.1|
|vscode-edit-csv|janisdd|0.2.9|
|vscode-gradle|richardwillis|3.0.8|
|vscode-gradle-extension-pack|richardwillis|0.0.2|
|vscode-java-debug|vscjava|0.26.0|
|vscode-java-dependency|vscjava|0.10.2|
|vscode-java-pack|vscjava|0.9.1|
|vscode-java-test|vscjava|0.23.0|
|vscode-json5|mrmlnc|1.0.0|
|vscode-lombok|GabrielBB|1.0.1|
|vscode-solution-explorer|fernandoescolar|0.3.10|
|vscode-spring-boot|Pivotal|1.18.0|
|vscode-terraform0-12|dhdersch|0.0.1|
|vscode-yaml|redhat|0.8.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.7|
|windbg-debug|reznikdi|0.3.4|
|xml|DotJoshJohnson|2.5.0|;

</details>

[omnisgharplog_works.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4751521/omnisgharplog_works.txt)
[omnisharplog_doesNOTwork.txt](https://github.com/OmniSharp/omnisharp-vscode/files/4751523/omnisharplog_doesNOTwork.txt)

**Comment by franck-schmidlin** [comment]
FYI - still a problem (in case this was an unfortunate glitch in a release) and I've run out of ideas as to where to look.

**Comment by juleedev** [comment]
I'm also getting this error.  Any updates on this / ideas on how to fix?  The details of my issue are all posted here: https://stackoverflow.com/questions/73529888/vs-code-test-explorer-no-longer-showing-any-tests-error-cannot-read-propert

**Comment by JoeRobich** [comment]
@juleedev Sorry, The C# extension does not currently support VS Codes Testing pane. You may have been using another extension for this in the past.
