### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed'

### ISSUE THREAD

**Issue by vladipus** [OmniSharp/omnisharp-vscode#3846]
## Issue Description ##

Everything was fine, but today I got this strange error, while developing with Unity.

## Actual Behavior ##

OmniSharp fails to start.

### OmniSharp log ###
<details>System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Microsoft.AspNetCore.Razor.OmniSharpPlugin.OmniSharpPluginStrongNamedRoslynServiceProvider..ctor() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/OmniSharpPluginStrongNamedRoslynServiceProvider.cs:line 26
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.<>c__DisplayClass3_2`1.<GetImportManyDescriptor>b__4(ExportDescriptor e)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.TypedParts.ActivationFeatures.DisposalFeature.<>c__DisplayClass0_0.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport[TExport](String contractName)
   at OmniSharp.Stdio.Host.Initialize() in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 56
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 51
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 70
   at OmniSharp.HostHelpers.Start(Func`1 action) in D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:line 29</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.46.0
**C# Extension**: 1.22.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular-BeastCode|Mikael|8.1.2|
|autodocstring|njpwerner|0.5.3|
|clang-format|xaver|1.9.0|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.4.0|
|code-settings-sync|Shan|3.4.3|
|code-spell-checker|streetsidesoftware|1.9.0|
|code-spell-checker-russian|streetsidesoftware|0.2.4|
|codedox|wiggin77|1.3.1|
|csharp|ms-dotnettools|1.22.0|
|csharpextensions|jchannon|1.3.1|
|debugger-for-chrome|msjsdiag|4.12.8|
|docomment|k--kato|0.1.11|
|doxdocgen|cschlosser|0.6.0|
|Doxygen|bbenoist|1.0.0|
|electron-debug|kodetech|18.11.1|
|gc-excelviewer|GrapeCity|2.1.35|
|git-easy|bibhasdn|1.11.0|
|git-project-manager|felipecaputo|1.7.1|
|gitblame|waderyan|4.0.1|
|gitconfig|sidneys1|2.0.1|
|githd|huizhou|2.2.4|
|githistory|donjayamanne|0.6.5|
|gitlens|eamodio|10.2.2|
|godot-tools|geequlim|1.1.0|
|haxe-checkstyle|vshaxe|1.6.1|
|haxe-debug|vshaxe|1.2.3|
|haxe-extension-pack|vshaxe|1.3.0|
|haxe-hl|HaxeFoundation|1.0.0|
|html-css-class-completion|Zignd|1.19.0|
|hxcpp-debugger|vshaxe|1.2.4|
|JavaScriptSnippets|xabikos|1.8.0|
|jinja|wholroyd|0.0.8|
|kha|kodetech|20.4.0|
|krafix|kodetech|18.7.1|
|krom|kodetech|20.1.0|
|krom-debug|kodetech|18.11.3|
|MagicPython|magicstack|1.1.0|
|mono-debug|ms-vscode|0.15.8|
|node-module-intellisense|leizongmin|1.5.0|
|nodejs-extension-pack|waderyan|0.1.9|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|2.2.0|
|prettier-vscode|esbenp|5.0.0|
|propertylist|zhouronghui|0.0.2|
|psi-header|psioniq|1.11.1|
|python|ms-python|2020.5.86806|
|remote-wsl|ms-vscode-remote|0.44.2|
|sass-indented|syler|1.8.5|
|search-node-modules|jasonnutter|1.3.0|
|swig-tpl|zhangciwu|0.0.6|
|syntax-project-pbxproj|mariomatheu|0.1.3|
|todo-tree|Gruntfuggly|0.0.176|
|unity-code-snippets|kleber-swf|1.3.0|
|vscode-ceedling-test-adapter|numaru|1.5.1|
|vscode-clangd|llvm-vs-code-extensions|0.1.6|
|vscode-csharp-snippets|jorgeserrano|0.3.1|
|vscode-eslint|dbaeumer|2.1.5|
|vscode-intelephense-client|bmewburn|1.4.1|
|vscode-languagetool|adamvoss|3.8.0|
|vscode-lldb|vadimcn|1.5.3|
|vscode-markdownlint|DavidAnson|0.36.0|
|vscode-npm-script|eg2|0.3.12|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-postgresql|ms-ossdata|0.3.0|
|vscode-test-explorer|hbenl|2.19.1|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vshaxe|nadako|2.20.3|;

</details>
ard

**Comment by vladipus** [comment]
I've managed to fix this by removing the ms-dotnettools folder from C:\Users\{name}\.vscode\extensions folder and reinstalling the extension.
