### ISSUE TITLE
Can't downgrade extension version

### ISSUE THREAD

**Issue by ru-ace** [OmniSharp/omnisharp-vscode#3891]
## Issue Description ##
I am experiencing some problems (input freezing during problems detection) and to be sure that problem in last update i tried to downgrade to previous version. But failed.  
I was try to reproduce this issue on other extensions - all works fine except this one. 

## Steps to Reproduce ##
Right click on "C#" extension in extension list. Select "Install another version ..."

## Expected Behavior ##
Get list of available versions of extension .

## Actual Behavior ##
There is 2 behaviors:
* VS code popup error "Server returned 404"
* Nothing happens

## Environment information ##

**VSCode version**: 1.46.1
**C# Extension**: 1.22.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.10.0</details>
<details><summary>Dotnet Information</summary>
Программы командной строки .NET (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.200/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-comments|aaron-bond|2.0.5|
|code-spell-checker|streetsidesoftware|1.9.0|
|code-spell-checker-russian|streetsidesoftware|0.2.4|
|csharp|ms-dotnettools|1.22.1|
|docomment|k--kato|0.1.13|
|mono-debug|ms-vscode|0.15.8|
|vscode-css-formatter|aeschli|1.0.1|
|vscode-dash|deerawan|2.4.0|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by ru-ace** [comment]
Found error message in logs. It's appears in both variants of behaviors.
```
[2020-07-03 15:59:00.359] [renderer1] [error] Server returned 404: Error: Server returned 404
    at Object.t.asJson (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1873:169)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2070:704
    at async Promise.all (index 11)
```

**Comment by ru-ace** [comment]
seems to be fixed
