### ISSUE TITLE
OmniSharp lists wrong .NET Framework as a dependancy on Windows

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#400]
## Environment data

C# Extension version: 1.1.2
## Steps to reproduce:
1. Get a clean version on Win7
2. Install VS Code + C# extension
3. Try to open the C# extension
4. Get a popup telling you to install .NET Framework 4.5. Follow the advice and install 4.5
5. Try running the extension again
## Expected  behavior

Extension should work
## Actual behavior

OmniSharp fails because I believe it actually depends on 4.6. Here is the output:

[INFO] Starting OmniSharp at 'c:\proj\clicon'...
[INFO] Started OmniSharp from 'C:\Users\greggm.vscode\extensions\ms-vscode.csharp-1.1.2.omnisharp\OmniSharp.exe' with process id 3108...
OmniSharp: -s c:\proj\clicon --hostPID 5004 dnx:enablePackageRestore=false --stdio

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception. ---> System.MissingMethodException: Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
   at Microsoft.Extensions.PlatformAbstractions.Native.NativeMethods.Windows.RtlGetVersion()
   at Microsoft.Extensions.PlatformAbstractions.Native.PlatformApis.GetOSVersion()
   at Microsoft.Extensions.PlatformAbstractions.RuntimeEnvironment..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at OmniSharp.Program.Main(String[] args) in C:\projects\omnisharp-roslyn\src\OmniSharp.Host\Program.cs:line 110
   at Program.Main(String[] args) in C:\projects\omnisharp-roslyn\src\OmniSharp\Program.cs:line 14

**Comment by DustinCampbell** [comment]
This got fixed with https://github.com/OmniSharp/omnisharp-roslyn/pull/669
