### ISSUE TITLE
Omnisharp not using the correct MsBuild

### ISSUE THREAD

**Issue by glenn2223** [OmniSharp/omnisharp-vscode#4089]
*Edit:* originally left out OmniSharp fail

## Issue Description ##
When `OmniSharp.MSBuild.Discovery.MSBuildLocator` finds multiple MSBuild folders it doesn't use the VSCode one but rather, in my case, the Visual Studio Enterprise 2019 one. Using this MSBuild throws a fail as it's trying to find `.NETFramework,Version=v5.0`, which obviously doesn't exist

#### Temp Fix ####
I have to keep renaming the folder to `MSBuild.disabled` and back again as I switch between different projects.

## Steps to Reproduce ##
Install Visual Studio Enterprise and VSCode

## Expected Behavior ##
Use the VSCode MSBuild folder and get no errors

## Actual Behavior ##
Uses the VS Community MSBuild folder and throws the below [fail]
```
OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file
```

### OmniSharp log ###
<details>

    [info]: OmniSharp.Stdio.Host  
        Starting OmniSharp on Windows 6.2.9200.0 (x64)  
    [info]: OmniSharp.Services.DotNetCliService  
        DotNetPath set to dotnet  
    [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator  
        Located 2 MSBuild instance(s)  
            1: Visual Studio Enterprise 2019 16.7.30413.136 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"  
            2: StandAlone 16.8.0 - "c:\Users\graphite.rack\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild\Current\Bin"  
    [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator  
        Registered MSBuild instance: Visual Studio Enterprise 2019 16.7.30413.136 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"

</details>

### C# log ###
<details>NOTHIN IN THE LOG</details>

## Environment information ##

**VSCode version**: 1.49.0
**C# Extension**: 1.23.2

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|cpptools|ms-vscode|1.0.0|
|csharp|ms-dotnettools|1.23.2|
|docomment|k--kato|0.1.18|
|html-css-class-completion|Zignd|1.19.0|
|live-sass|ritwickdey|3.0.0|
|LiveServer|ritwickdey|5.6.1|
|powershell|ms-vscode|2020.6.0|
|vscode-eslint|dbaeumer|2.1.8|
|vscode-icons|vscode-icons-team|10.2.0|
|vscode-nuget-package-manager|jmrog|1.1.6|;

</details>

**Comment by filipw** [comment]
This is by design, Visual Studio MSBuild is given higher precedence by OmniSharp as long as it's newer than 16.3.

**Comment by filipw** [comment]
you can always pin Omnisharp to a specific MSBuild path with this setting https://github.com/OmniSharp/omnisharp-roslyn/pull/1545#issuecomment-510461836

**Comment by glenn2223** [comment]
> you can always pin Omnisharp to a specific MSBuild path with this setting [OmniSharp/omnisharp-roslyn#1545 (comment)](https://github.com/OmniSharp/omnisharp-roslyn/pull/1545#issuecomment-510461836)

Tried it and now I get:
```
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Users\graphite.rack\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild\Current\Bin\Current\Microsoft.Common.props" was not found. Also, tried to find "Current\Microsoft.Common.props" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "c:\Users\graphite.rack\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\OmniSharp.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props
```

I have seen the file in `Current\Microsoft.Common.props` so I'm not sure what the problem is there

<details>
<summary>Full Stack</summary>

```
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Users\graphite.rack\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\.msbuild\Current\Bin\Current\Microsoft.Common.props" was not found. Also, tried to find "Current\Microsoft.Common.props" in the fallback search path(s) for $(MSBuildExtensionsPath) - "C:\Program Files (x86)\MSBuild" . These search paths are defined in "c:\Users\graphite.rack\.vscode\extensions\ms-dotnettools.csharp-1.23.2\.omnisharp\1.37.1\OmniSharp.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ThrowForImportedProjectWithSearchPathsNotFound(ProjectImportPathMatch searchPathMatch, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath, IReadOnlyDictionary`2 projectConfigurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 157
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath, IReadOnlyDictionary`2 configurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 75
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader, Guid sessionId, DotNetInfo dotNetInfo) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 116
   at OmniSharp.MSBuild.ProjectManager.<>c__DisplayClass31_0.<LoadProject>b__0() in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 302
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 313

```

</details>

<details>
<summary>omnisharp.json</summary>

```json
{
    "MSBuild": {
        "MSBuildOverride": {
            "MSBuildPath": "C:\\Users\\graphite.rack\\.vscode\\extensions\\ms-dotnettools.csharp-1.23.2\\.omnisharp\\1.37.1\\.msbuild\\Current\\Bin",
            "Name": "vscode's msbuild"
        }
    }
}
```

</detilas>

**Comment by jmarolf** [comment]
by design
