### ISSUE TITLE
Server initialization failed.

### ISSUE THREAD

**Issue by Carleux** [OmniSharp/omnisharp-vscode#4109]
--------------------------------------------------------------------------------
Razor.VSCode version 6.0.0-alpha.1.20418.9
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

[Error - 7:25:38 PM] Server initialization failed.
  Message: Internal Error - System.UnauthorizedAccessException: Access to the path 'c:\Documents and Settings' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.AspNetCore.Razor.LanguageServer.ProjectConfigurationFileChangeDetector.GetExistingConfigurationFiles(String workspaceDirectory) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs:line 119
   at Microsoft.AspNetCore.Razor.LanguageServer.ProjectConfigurationFileChangeDetector.StartAsync(String workspaceDirectory, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs:line 56
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorFileChangeDetectorManager.InitializedAsync() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetectorManager.cs:line 46
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorLanguageServer.<>c__DisplayClass9_0.<<CreateAsync>b__3>d.MoveNext() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs:line 83
--- End of stack trace from previous location ---
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.MediatR.IRequestHandler<OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams,OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult>.Handle(InitializeParams request, CancellationToken token)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(TDescriptor descriptor, Request request, CancellationToken token)
  Code: -32602

**Comment by gregg-miskelly** [comment]
CC @NTaylorMullen

**Comment by NTaylorMullen** [comment]
@Carleux what does your project look like?

**Comment by pejuborg** [comment]
I'm running into this issue as well with VS Code 1.56.2 and ms-dotnettools.csharp version 1.23.11
When opening a C# file i see this in the Razor log

```
--------------------------------------------------------------------------------
Razor.VSCode version 6.0.0-alpha.1.21201.19
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

[Error - 10:05:59] Server initialization failed.
  Message: Internal Error - System.UnauthorizedAccessException: Access to the path 'c:\Users\<USERNAME>\Application Data' is denied.

```

**Comment by orlfi** [comment]
I have the same log. Has anyone defeated this problem?

**Comment by NTaylorMullen** [comment]
Hmmm, I'd be curious to know what your projects look like / where in the `C:\Users\<USERNAME>` hierarchy they exist. TO get this type of error i'd imagine that your projects were in the root of `C:\Users\<USERNAME>` which definitely seems off

**Comment by spixy** [comment]
I opened VS Code in C:\ "folder" and got same results.
Is VS Code meant to be opened only in folders containing code?

**Comment by NTaylorMullen** [comment]
> I opened VS Code in C:\ "folder" and got same results.
> Is VS Code meant to be opened only in folders containing code?

Oooooo interesting. You can definitely open it wherever, it's just not "as expected" when you open it at that level because all of your extensions & vscode itself will try to make sense of your entire C drive 😄
