### ISSUE TITLE
Razor Service crashing after switching to net5.0

### ISSUE THREAD

**Issue by XmlmXmlmX** [OmniSharp/omnisharp-vscode#4169]
## Steps to Reproduce ##
Open the following project:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1; net5.0</TargetFrameworks>
    <RootNamespace>projectx</RootNamespace>
    <UserSecretsId>aspnet-projectx-0FB5BB25-15E6-4B42-8170-FF4E02860532</UserSecretsId>
    <WebProject_DirectoryAccessLevelKey>0</WebProject_DirectoryAccessLevelKey>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LigerShark.WebOptimizer.Core" Version="3.0.279" />
    <PackageReference Include="LigerShark.WebOptimizer.Sass" Version="3.0.43-beta" />
    <PackageReference Include="Markdig" Version="0.22.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="3.1.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.9" />
    <!--<PackageReference Include="Microsoft.Graph.Beta" Version="0.31.0-preview" />-->
    <PackageReference Include="Microsoft.Identity.Client" Version="4.21.1" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.2.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.5" />
    <PackageReference Include="BlazorInputFile" Version="0.2.0" />
    <PackageReference Include="QRCoder" Version="1.3.9" />
    <PackageReference Include="libphonenumber-csharp" Version="8.12.11" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.4.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="2.1.3" />
    <PackageReference Include="Serilog.Formatting.Elasticsearch" Version="8.4.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="4.7.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
    <PackageReference Include="Microsoft.Identity.Web" Version="1.2.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="1.2.0" />
    <PackageReference Include="Microsoft.Identity.Web.MicrosoftGraphBeta" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup>
    <Watch Include="**\*.scss" Exclude="node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" />
  </ItemGroup>
</Project>
```

Open any Razorpage...

## Expected Behavior ##
Razorpage opens and intellisense is working.

## Actual Behavior ##

Razorpage opens and intellisense is **not** working.

### Razor log ###
<details>
--------------------------------------------------------------------------------
Razor.VSCode version 6.0.0-alpha.1.20479.2
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

[Error - 14:26:54] Request textDocument/codeAction failed.
  Message: Internal Error - OmniSharp.Extensions.JsonRpc.Server.MethodNotSupportedException: Method not found: 'razor/provideCodeActions'.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.Returning[TResponse](CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.CodeActionEndpoint.GetCSharpCodeActionsFromLanguageServerAsync(RazorCodeActionContext context, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs:line 235
   at Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.CodeActionEndpoint.GetCSharpCodeActionsAsync(RazorCodeActionContext context, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs:line 179
   at Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.CodeActionEndpoint.Handle(RazorCodeActionParams request, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs:line 95
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|5_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 
</details>

### OmniSharp log ###
<details>Starting OmniSharp server at 2.11.2020, 14:26:45
    Target: c:\Users\myusername\repos\projectx\Source\projectx.sln

OmniSharp server started.
    Path: c:\Users\myusername\.vscode\extensions\ms-dotnettools.csharp-1.23.4\.omnisharp\1.37.3\OmniSharp.exe
    PID: 25772

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Enterprise 2019 16.7.30517.126 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\myusername\.vscode\extensions\ms-dotnettools.csharp-1.23.4\.omnisharp\1.37.3\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2019 16.7.30517.126 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\myusername\repos\projectx\Source'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\myusername\repos\projectx\Source\projectx.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\myusername\repos\projectx\Source\projectx\projectx.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\myusername\repos\projectx\Source'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\myusername\repos\projectx\Source\projectx\projectx.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\myusername\repos\projectx\Source' on host 13508.
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\Users\myusername\repos\projectx\Source\projectx\Pages\Index.razor__virtual.cs added to workspace
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\myusername\repos\projectx\Source\projectx\projectx.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\myusername\repos\projectx\Source\projectx\projectx.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: projectx
[fail]: OmniSharp.Stdio.Host
        ************  Response ************ 
{
  "Request_seq": 11,
  "Command": "/v2/getcodeactions",
  "Running": true,
  "Success": false,
  "Message": "\"System.ArgumentOutOfRangeException: Das angegebene Argument liegt außerhalb des gültigen Wertebereichs.\\r\\nParametername: index\\r\\n   bei Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)\\r\\n   bei OmniSharp.Extensions.TextExtensions.GetPositionFromLineAndOffset(SourceText text, Int32 lineNumber, Int32 offset) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn\\\\Extensions\\\\TextExtensions.cs:Zeile 26.\\r\\n   bei OmniSharp.Extensions.TextExtensions.GetSpanFromRange(SourceText text, Range range) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn\\\\Extensions\\\\TextExtensions.cs:Zeile 48.\\r\\n   bei OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.BaseCodeActionService`2.GetTextSpan(ICodeActionRequest request, SourceText sourceText) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Refactoring\\\\V2\\\\BaseCodeActionService.cs:Zeile 125.\\r\\n   bei OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.BaseCodeActionService`2.<GetAvailableCodeActions>d__10.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Refactoring\\\\V2\\\\BaseCodeActionService.cs:Zeile 91.\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.GetCodeActionsService.<Handle>d__1.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Roslyn.CSharp\\\\Services\\\\Refactoring\\\\V2\\\\GetCodeActionsService.cs:Zeile 32.\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext()\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:Zeile 230.\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Endpoint\\\\EndpointHandler.cs:Zeile 131.\\r\\n--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---\\r\\n   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   bei OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:Zeile 215.\"",
  "Body": null,
  "Seq": 39,
  "Type": "response"
}
</details>

## Environment information ##

**VSCode version**: 1.50.1
**C# Extension**: 1.23.4

<details><summary>Dotnet Information</summary>
.NET Core SDK (gem�� "global.json"):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  1.1.10 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|addDocComments|stevencl|0.0.8|
|azure-account|ms-vscode|0.9.3|
|azure-iot-toolkit|vsciot-vscode|2.16.4|
|azure-pipelines|ms-azure-devops|1.177.0|
|azurecli|ms-vscode|0.5.0|
|azurerm-vscode-tools|msazurermtools|0.13.0|
|color-highlight|naumovs|2.3.0|
|commit-message-editor|adam-bender|0.14.3|
|csharp|ms-dotnettools|1.23.4|
|csharp-to-typescript|adrianwilczynski|1.12.1|
|csharpextensions|jchannon|1.3.1|
|debugger-for-chrome|msjsdiag|4.12.11|
|debugger-for-edge|msjsdiag|1.0.15|
|dotenv|mikestead|1.0.1|
|emoji|Perkovec|0.0.3|
|emojis4git|benjaminadk|2.1.2|
|file-icons|file-icons|1.0.26|
|file-properties-viewer|brunnerh|0.5.0|
|git-commits|Exelord|3.7.14|
|Handlebars|andrejunges|0.4.1|
|live-sass|ritwickdey|3.0.0|
|live-server-preview|negokaz|0.1.4|
|LiveServer|ritwickdey|5.6.1|
|material-icon-theme|PKief|4.4.0|
|ms-teams-vscode-extension|TeamsDevApp|1.1.1|
|mssql|ms-mssql|1.9.0|
|powershell|ms-vscode|2020.6.0|
|quicktype|quicktype|12.0.46|
|razor-plus|austincummings|0.1.4|
|remote-containers|ms-vscode-remote|0.145.1|
|remote-wsl|ms-vscode-remote|0.50.1|
|rest-client|humao|0.24.3|
|svg|jock|1.4.1|
|tsimporter|pmneo|2.0.1|
|vetur|octref|0.29.0|
|vscode-apimanagement|ms-azuretools|0.1.7|
|vscode-azureappservice|ms-azuretools|0.19.0|
|vscode-azurefunctions|ms-azuretools|1.0.0|
|vscode-azureresourcegroups|ms-azuretools|0.2.0|
|vscode-azurestorage|ms-azuretools|0.10.1|
|vscode-azurevirtualmachines|ms-azuretools|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-cosmosdb|ms-azuretools|0.15.0|
|vscode-csproj|lucasazzola|0.7.0|
|vscode-docker|ms-azuretools|1.7.0|
|vscode-dotnet-runtime|ms-dotnettools|0.1.2|
|vscode-edge-devtools|ms-edgedevtools|1.1.1|
|vscode-eslint|dbaeumer|2.1.13|
|vscode-jest|Orta|3.2.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.2.1|
|vscode-language-babel|mgmcdermott|0.0.30|
|vscode-nginx|shanoor|0.6.0|
|vscode-nginx|william-voyek|0.7.2|
|vscode-node-azure-pack|ms-vscode|0.0.11|
|vscode-npm-script|eg2|0.3.13|
|vscode-nuget-gallery|patcx|0.0.22|
|vscode-open|sandcastle|0.1.0|
|vscode-scss-formatter|sibiraj-s|2.0.2|
|vscode-sort-package-json|unional|1.2.2|
|vscode-sqlite|alexcvzz|0.9.0|
|vscode-styled-components|jpoissonnier|1.2.0|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-yaml|redhat|0.12.0|
|vscode-yarn|gamunu|1.7.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|
|vsliveshare|ms-vsliveshare|1.0.3071|
|vue|jcbuisson|0.1.5|
|xml|DotJoshJohnson|2.5.1|
|zeplin|Zeplin|2.1.0|;

</details>

**Comment by NTaylorMullen** [comment]
> I have the same issue.

@sharpninja that's surprising, would you mind providing your Razor logs? I would have assumed this issue was fixed

**Comment by sharpninja** [comment]
I will gather logs today.
