### ISSUE TITLE
omnisharp crashes upon startup : Cannot read property 'isWindows' of undefined

### ISSUE THREAD

**Issue by tuxinal** [OmniSharp/omnisharp-vscode#4207]
## Environment data
`dotnet --info` output:
```

.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     arch
 OS Version:
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100-rc.2.20479.15/

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  2.1.811 [/usr/share/dotnet/sdk]
  5.0.100-rc.2.20479.15 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 2.1.23 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

VS Code version: 1.51.1
C# Extension version: 1.23.6

i got the log from the extension host logs

```
[2020-11-14 17:45:13.598] [exthost] [error] TypeError: Cannot read property 'isWindows' of undefined
	at /home/user/.vscode-oss/extensions/ms-dotnettools.csharp-1.23.6/dist/extension.js:16:454527
	at /home/user/.vscode-oss/extensions/ms-dotnettools.csharp-1.23.6/dist/extension.js:16:454750
	at Generator.throw (<anonymous>)
	at a (/home/user/.vscode-oss/extensions/ms-dotnettools.csharp-1.23.6/dist/extension.js:16:452119)
```

**Comment by tuxinal** [comment]
i just found out this is a duplicate of #2723

**Comment by tuxinal** [comment]
actually the soloution there didn't fix it still getting the same error in extension host log

**Comment by tuxinal** [comment]
I downgraded electron9 to 9.3.3 seems to work now
