### ISSUE TITLE
Unable to load the project after the SDK was upgraded to .NET 5.0

### ISSUE THREAD

**Issue by wendellestradairely** [OmniSharp/omnisharp-vscode#4234]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100     
 Commit:    5044b93829  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19041
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download```

VS Code version:
C# Extension version:

## OmniSharp log
```OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Projects\i21RESTfulApi\i21RESTfulApi.csproj'.
c:\Projects\i21RESTfulApi\i21RESTfulApi.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.  c:\Projects\i21RESTfulApi\i21RESTfulApi.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath, IReadOnlyDictionary`2 projectConfigurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 157
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath, IReadOnlyDictionary`2 configurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 75
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader, Guid sessionId, DotNetInfo dotNetInfo) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 116
   at OmniSharp.MSBuild.ProjectManager.<>c__DisplayClass31_0.<LoadProject>b__0() in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 302
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 313

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Projects\i21RESTfulApi\i21RESTfulApi.csproj
```
## Steps to reproduce
Install .NET 5.0 SDK and Hosting Bundle

## Expected  behavior
It should load the project/solution

## Actual behavior
Unable to load the project. Intellisense is not working. Formatting is not working. Parsing and error highlighting is not working.

**Comment by caiohamamura** [comment]
I got it here also:

```
OmniSharp.MSBuild.ProjectLoader
        the reference assemblies for.NETFramework,Version=v5.0 were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed.
```

**Comment by filipw** [comment]
please post the full Omnisharp log.
Looks like outdated MSBuild is picked up

**Comment by caiohamamura** [comment]
```
OmniSharp server started.
    Path: c:\Users\caioh\.vscode\extensions\ms-dotnettools.csharp-1.23.7\.omnisharp\1.37.4\OmniSharp.exe
    PID: 15936

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.7.30611.23 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\caioh\.vscode\extensions\ms-dotnettools.csharp-1.23.7\.omnisharp\1.37.4\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.7.30611.23 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\caioh\Desktop\TRABALHO\IFSP\2020\LP1\Async\Aula7\2Switch'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\caioh\Desktop\TRABALHO\IFSP\2020\LP1\Async\Aula7\2Switch'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\caioh\Desktop\TRABALHO\IFSP\2020\LP1\Async\Aula7\2Switch\Switch.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\caioh\Desktop\TRABALHO\IFSP\2020\LP1\Async\Aula7\2Switch'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\caioh\Desktop\TRABALHO\IFSP\2020\LP1\Async\Aula7\2Switch\Switch.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\caioh\Desktop\TRABALHO\IFSP\2020\LP1\Async\Aula7\2Switch' on host 4632.
[fail]: OmniSharp.MSBuild.ProjectLoader
        os assemblies de referência para .NETFramework,Version=v5.0 não foram encontrados. Para resolver isso, instale o Pacote do Desenvolvedor (SDK/Pacote de Direcionamento) dessa versão do Framework ou redirecione seu aplicativo. É possível baixar Pacotes do Desenvolvedor do .NET Framework em https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\caioh\Desktop\TRABALHO\IFSP\2020\LP1\Async\Aula7\2Switch\Switch.csproj'.
c:\Users\caioh\Desktop\TRABALHO\IFSP\2020\LP1\Async\Aula7\2Switch\Switch.csproj
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1177,5): Error: os assemblies de referência para .NETFramework,Version=v5.0 não foram encontrados. Para resolver isso, instale o Pacote do Desenvolvedor (SDK/Pacote de Direcionamento) dessa versão do Framework ou redirecione seu aplicativo. É possível baixar Pacotes do Desenvolvedor do .NET Framework em https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\caioh\Desktop\TRABALHO\IFSP\2020\LP1\Async\Aula7\2Switch\Switch.csproj
```

**Comment by caiohamamura** [comment]
It seems like it is looking for .NET Framework 5.0, but it is not .NET Framework, but the new .NET 5.0 (which would actually be "Core" and not "Framework").

**Comment by filipw** [comment]
the problem is here

> 1: Visual Studio Community 2019 16.7.30611.23 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"

Omnisharp sees that you have Visual Studio installed on your machine and tries to use its MSBuild.

However your Visual Studio installation is not up to date - 16.8 is the lowest version needed to work with .NET 5.0.

You need to update your Visual Studio or uninstall it.

**Comment by wendellestradairely** [comment]
@filipw It did not work when I update my Visual Studio to the latest version. I also updated the latest build tools but to no avail. I was getting an error: `Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.`. However, I tried setting the `omnisharp.path` to `latest` and everything was working fine again.

**Comment by caiohamamura** [comment]
> the problem is here
> 
> > 1: Visual Studio Community 2019 16.7.30611.23 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
> 
> Omnisharp sees that you have Visual Studio installed on your machine and tries to use its MSBuild.
> 
> However your Visual Studio installation is not up to date - 16.8 is the lowest version needed to work with .NET 5.0.
> 
> You need to update your Visual Studio or uninstall it.

Any way to force using `2: StandAlone 16.8.0 - "c:\Users\caioh\.vscode\extensions\ms-dotnettools.csharp-1.23.7\.omnisharp\1.37.4\.msbuild\Current\Bin"?
`

**Comment by caiohamamura** [comment]
> > the problem is here
> > > 1: Visual Studio Community 2019 16.7.30611.23 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
> > 
> > 
> > Omnisharp sees that you have Visual Studio installed on your machine and tries to use its MSBuild.
> > However your Visual Studio installation is not up to date - 16.8 is the lowest version needed to work with .NET 5.0.
> > You need to update your Visual Studio or uninstall it.
> 
> Any way to force using `2: StandAlone 16.8.0 - "c:\Users\caioh\.vscode\extensions\ms-dotnettools.csharp-1.23.7\.omnisharp\1.37.4\.msbuild\Current\Bin"`?
> `

Already found it https://github.com/OmniSharp/omnisharp-roslyn/pull/1545#issuecomment-510461836

**Comment by covamalia** [comment]
"Update Visual Studio" may not always be the best suggestion. There could be situations where this is not possible (for example Visual Studio extension incompatibility or company internal IT procedures) and so updating may not always be quite as straight forward for some as it is for others. Also, an update to Visual Studio is a larger undertaking, so if someone runs into the issue when trying out a quick prototype, then the ease of usability is lost.

If Omnisharp is being told to use "latest", then you would expect it to always pick up the latest version of MSBuild. Out of the two options of 16.7.30611.23 and 16.8.0 then you would expect this would pull out the second one (which is also the one that Omnisharp will happily grab an update for by itself).
