### ISSUE TITLE
Failed compiling offline package

### ISSUE THREAD

**Issue by nanlingyi** [OmniSharp/omnisharp-vscode#4262]
I failed while building a offline package following the steps of this https://github.com/OmniSharp/omnisharp-vscode/issues/2843#issuecomment-461965561
I succeeded long time ago with version 1.21.4, but now i can't build the package of the latest version
My log shows it failed at 'npm run vscode:prepublish'

log of command 'gulp vsix:offline:package':

```
$ gulp vsix:offline:package

> csharp@1.23.6 gulp /home/nanlingyi/Documents/vsix/omnisharp-vscode-master/omnisharp-vscode-v.1.23.6
> gulp "vsix:offline:package"

[16:50:21] Requiring external module ts-node/register
[16:50:27] Using gulpfile ~/Documents/vsix/omnisharp-vscode-master/omnisharp-vscode-v.1.23.6/gulpfile.ts
[16:50:27] Starting 'vsix:offline:package'...
Downloading package 'OmniSharp for Windows (.NET 4.6 / x64)' (36013 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.6 / x64)'

Downloading package '.NET Core Debugger (Windows / x64)' (43209 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (Windows / x64)'

Downloading package 'Razor Language Server (Windows / x64)' (52339 KB).................... Done!
Installing package 'Razor Language Server (Windows / x64)'

starting node /home/nanlingyi/Documents/vsix/omnisharp-vscode-master/omnisharp-vscode-v.1.23.6/node_modules/vsce/out/vsce package -o /home/nanlingyi/Documents/vsix/omnisharp-vscode-master/omnisharp-vscode-v.1.23.6/csharp.1.23.6-win32-x86_64.vsix
Executing prepublish script 'npm run vscode:prepublish'...
 ERROR  Command failed: npm run vscode:prepublish
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! csharp@1.23.6 vscode:prepublish: `tsc -p ./ && webpack --mode production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the csharp@1.23.6 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nanlingyi/.npm/_logs/2020-12-04T08_52_42_013Z-debug.log

[16:52:42] 'vsix:offline:package' errored after 2.23 min
[16:52:42] Error: process exited with code 1
    at ChildProcess.<anonymous> (/home/nanlingyi/Documents/vsix/omnisharp-vscode-master/omnisharp-vscode-v.1.23.6/node_modules/async-child-process/lib/join.js:25:22)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:548:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    at Process.callbackTrampoline (internal/async_hooks.js:129:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! csharp@1.23.6 gulp: `gulp "vsix:offline:package"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the csharp@1.23.6 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nanlingyi/.npm/_logs/2020-12-04T08_52_42_111Z-debug.log
```
log of command 'npm run vscode:prepublish':

```
$ npm run vscode:prepublish

> csharp@1.23.6 vscode:prepublish /home/nanlingyi/Documents/vsix/omnisharp-vscode-master/omnisharp-vscode-v.1.23.6
> tsc -p ./ && webpack --mode production

src/features/completionProvider.ts:63:140 - error TS2554: Expected 0-1 arguments, but got 2.

63         const docs: MarkdownString | undefined = omnisharpCompletion.Documentation ? new MarkdownString(omnisharpCompletion.Documentation, false) : undefined;
                                                                                                                                              ~~~~~

src/features/completionProvider.ts:94:13 - error TS2322: Type '{ label: string; kind: number; detail: string; documentation: MarkdownString; commitCharacters: string[]; preselect: boolean; filterText: string; insertText: string | SnippetString; ... 4 more ...; keepWhitespace: true; }' is not assignable to type 'CompletionItem'.
  Object literal may only specify known properties, and 'tags' does not exist in type 'CompletionItem'.

94             tags: omnisharpCompletion.Tags,
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/features/semanticTokensProvider.ts:154:88 - error TS2694: Namespace '"vscode"' has no exported member 'DocumentSemanticTokensProvider'.

154 export default class SemanticTokensProvider extends AbstractProvider implements vscode.DocumentSemanticTokensProvider, vscode.DocumentRangeSemanticTokensProvider {
                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/features/semanticTokensProvider.ts:154:127 - error TS2694: Namespace '"vscode"' has no exported member 'DocumentRangeSemanticTokensProvider'.

154 export default class SemanticTokensProvider extends AbstractProvider implements vscode.DocumentSemanticTokensProvider, vscode.DocumentRangeSemanticTokensProvider {
                                                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/features/semanticTokensProvider.ts:160:25 - error TS2694: Namespace '"vscode"' has no exported member 'SemanticTokensLegend'.

160     getLegend(): vscode.SemanticTokensLegend {
                            ~~~~~~~~~~~~~~~~~~~~

src/features/semanticTokensProvider.ts:161:27 - error TS2339: Property 'SemanticTokensLegend' does not exist on type 'typeof import("vscode")'.

161         return new vscode.SemanticTokensLegend(tokenTypes, tokenModifiers);
                              ~~~~~~~~~~~~~~~~~~~~

src/features/semanticTokensProvider.ts:164:121 - error TS2694: Namespace '"vscode"' has no exported member 'SemanticTokens'.

164     async provideDocumentSemanticTokens(document: vscode.TextDocument, token: vscode.CancellationToken): Promise<vscode.SemanticTokens | null> {
                                                                                                                            ~~~~~~~~~~~~~~

src/features/semanticTokensProvider.ts:169:147 - error TS2694: Namespace '"vscode"' has no exported member 'SemanticTokens'.

169     async provideDocumentRangeSemanticTokens(document: vscode.TextDocument, range: vscode.Range, token: vscode.CancellationToken): Promise<vscode.SemanticTokens | null> {
                                                                                                                                                      ~~~~~~~~~~~~~~

src/features/semanticTokensProvider.ts:184:140 - error TS2694: Namespace '"vscode"' has no exported member 'SemanticTokens'.

184     async _provideSemanticTokens(document: vscode.TextDocument, range: protocol.V2.Range, token: vscode.CancellationToken): Promise<vscode.SemanticTokens | null> {
                                                                                                                                               ~~~~~~~~~~~~~~

src/features/semanticTokensProvider.ts:209:36 - error TS2339: Property 'SemanticTokensBuilder' does not exist on type 'typeof import("vscode")'.

209         const builder = new vscode.SemanticTokensBuilder();
                                       ~~~~~~~~~~~~~~~~~~~~~

src/main.ts:133:23 - error TS2339: Property 'extensionKind' does not exist on type 'Extension<CSharpExtensionExports>'.

133         if (extension.extensionKind === vscode.ExtensionKind.Workspace) {
                          ~~~~~~~~~~~~~

src/main.ts:133:48 - error TS2339: Property 'ExtensionKind' does not exist on type 'typeof import("vscode")'.

133         if (extension.extensionKind === vscode.ExtensionKind.Workspace) {
                                                   ~~~~~~~~~~~~~

src/omnisharp/extension.ts:117:47 - error TS2339: Property 'registerDocumentSemanticTokensProvider' does not exist on type 'typeof languages'.

117         localDisposables.add(vscode.languages.registerDocumentSemanticTokensProvider(documentSelector, semanticTokensProvider, semanticTokensProvider.getLegend()));
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/omnisharp/extension.ts:118:47 - error TS2339: Property 'registerDocumentRangeSemanticTokensProvider' does not exist on type 'typeof languages'.

118         localDisposables.add(vscode.languages.registerDocumentRangeSemanticTokensProvider(documentSelector, semanticTokensProvider, semanticTokensProvider.getLegend()));
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/statusBarItemAdapter.ts:48:9 - error TS2322: Type 'string | Command' is not assignable to type 'string'.
  Type 'Command' is not assignable to type 'string'.

48         this.statusBarItem.command = value;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~

test/integrationTests/semanticTokensProvider.test.ts:28:28 - error TS2694: Namespace '"vscode"' has no exported member 'SemanticTokensLegend'.

28     const legend = <vscode.SemanticTokensLegend>await vscode.commands.executeCommand("csharp.private.getSemanticTokensLegend");
                              ~~~~~~~~~~~~~~~~~~~~

test/integrationTests/semanticTokensProvider.test.ts:29:28 - error TS2694: Namespace '"vscode"' has no exported member 'SemanticTokens'.

29     const actual = <vscode.SemanticTokens>await vscode.commands.executeCommand("csharp.private.getSemanticTokens", fileUri);
                              ~~~~~~~~~~~~~~

test/integrationTests/semanticTokensProvider.test.ts:43:98 - error TS7006: Parameter '_' implicitly has an 'any' type.

43         const tokenClassifiction = [legend.tokenTypes[typeIdx], ...legend.tokenModifiers.filter((_, i) => modSet & 1 << i)].join('.');
                                                                                                    ~

test/integrationTests/semanticTokensProvider.test.ts:43:101 - error TS7006: Parameter 'i' implicitly has an 'any' type.

43         const tokenClassifiction = [legend.tokenTypes[typeIdx], ...legend.tokenModifiers.filter((_, i) => modSet & 1 << i)].join('.');
                                                                                                       ~


Found 19 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! csharp@1.23.6 vscode:prepublish: `tsc -p ./ && webpack --mode production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the csharp@1.23.6 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-04T08_47_26_574Z-debug.log
```

**Comment by gsmachado** [comment]
Check this out: https://github.com/OmniSharp/omnisharp-vscode/issues/3954#issuecomment-741182273

😄

**Comment by nanlingyi** [comment]
> Check this out: [#3954 (comment)](https://github.com/OmniSharp/omnisharp-vscode/issues/3954#issuecomment-741182273)

Problem solved, thx
