### ISSUE TITLE
IntelliSense and Autocomplete Not Showing for Unity Project

### ISSUE THREAD

**Issue by AzidanoValkran** [OmniSharp/omnisharp-vscode#4421]
## Issue Description ##
As soon as I start up Visual Studio Code, my OmniSharp server starts up, but then says that it is unable to load my csproj file.

## Steps to Reproduce ##
- Start up Unity
- Right-click on the Projects folder
- Click 'Open C# Project'

## Expected Behavior ##
- Autocomplete and IntelliSense would be active as the cs files are being edited.

## Actual Behavior ##
No IntelliSense is showing

### OmniSharp log ###
```Starting OmniSharp server at 04/03/2021, 16:19:55
    Target: c:\Syncthing\Unity\BaseBuilder\Base Building Game\Base Building Game.sln

Razor dev mode active. Suppressing built-in OmniSharp Razor support.

OmniSharp server started.
    Path: c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\OmniSharp.exe
    PID: 13088

[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Cake, Version=1.37.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.DotNetTest, Version=1.37.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Host, Version=1.37.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.MSBuild, Version=1.37.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Roslyn, Version=1.37.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Roslyn.CSharp, Version=1.37.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Script, Version=1.37.0.0, Culture=neutral, PublicKeyToken=null
[dbug]: OmniSharp.CompositionHostBuilder
        Loaded OmniSharp.Shared, Version=1.37.0.0, Culture=neutral, PublicKeyToken=null
[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[dbug]: OmniSharp.CompositionHostBuilder
        .NET SDK requires MSBuild instances version 16.3 or higher
[dbug]: OmniSharp.MSBuild.Discovery.Providers.VisualStudioInstanceProvider
        An exception was thrown while retrieving Visual Studio instances.
System.DllNotFoundException: Unable to load DLL 'Microsoft.VisualStudio.Setup.Configuration.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at OmniSharp.MSBuild.Discovery.Interop.GetSetupConfiguration(ISetupConfiguration& configuration, IntPtr reserved)
   at OmniSharp.MSBuild.Discovery.Interop.GetSetupConfiguration() in D:\a\1\s\src\OmniSharp.Host\MSBuild\Discovery\Interop.cs:line 25
   at OmniSharp.MSBuild.Discovery.Providers.VisualStudioInstanceProvider.GetInstances() in D:\a\1\s\src\OmniSharp.Host\MSBuild\Discovery\Providers\VisualStudioInstanceProvider.cs:line 28
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.9.0 - "c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin"
[dbug]: OmniSharp.CompositionHostBuilder
        MSBuild instance StandAlone 16.9.0 scored at 1
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.Build.Utilities.Core.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.Build.Tasks.Core.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.Build.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.Build.Framework.dll' (name-only).
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.9.0 - "c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild
            MSBuildToolsPath = c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.Build.Utilities.Core.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.Build.Framework.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.Build.dll' (name-only).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.VisualBasic.Workspaces, Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll'.
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.CodeAnalysis.VisualBasic.Features, Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.CodeAnalysis.VisualBasic.Features.dll'.
[dbug]: OmniSharp.WorkspaceInitializer
        Starting with OmniSharp options: {"RoslynExtensionsOptions":{"EnableDecompilationSupport":false,"EnableAnalyzersSupport":true,"EnableImportCompletion":false,"DocumentAnalysisTimeoutMs":10000,"LocationPaths":null},"FormattingOptions":{"OrganizeImports":false,"EnableEditorConfigSupport":true,"NewLine":"\n","UseTabs":false,"TabSize":4,"IndentationSize":4,"SpacingAfterMethodDeclarationName":false,"SpaceWithinMethodDeclarationParenthesis":false,"SpaceBetweenEmptyMethodDeclarationParentheses":false,"SpaceAfterMethodCallName":false,"SpaceWithinMethodCallParentheses":false,"SpaceBetweenEmptyMethodCallParentheses":false,"SpaceAfterControlFlowStatementKeyword":true,"SpaceWithinExpressionParentheses":false,"SpaceWithinCastParentheses":false,"SpaceWithinOtherParentheses":false,"SpaceAfterCast":false,"SpacesIgnoreAroundVariableDeclaration":false,"SpaceBeforeOpenSquareBracket":false,"SpaceBetweenEmptySquareBrackets":false,"SpaceWithinSquareBrackets":false,"SpaceAfterColonInBaseTypeDeclaration":true,"SpaceAfterComma":true,"SpaceAfterDot":false,"SpaceAfterSemicolonsInForStatement":true,"SpaceBeforeColonInBaseTypeDeclaration":true,"SpaceBeforeComma":false,"SpaceBeforeDot":false,"SpaceBeforeSemicolonsInForStatement":false,"SpacingAroundBinaryOperator":"single","IndentBraces":false,"IndentBlock":true,"IndentSwitchSection":true,"IndentSwitchCaseSection":true,"IndentSwitchCaseSectionWhenBlock":true,"LabelPositioning":"oneLess","WrappingPreserveSingleLine":true,"WrappingKeepStatementsOnSingleLine":true,"NewLinesForBracesInTypes":true,"NewLinesForBracesInMethods":true,"NewLinesForBracesInProperties":true,"NewLinesForBracesInAccessors":true,"NewLinesForBracesInAnonymousMethods":true,"NewLinesForBracesInControlBlocks":true,"NewLinesForBracesInAnonymousTypes":true,"NewLinesForBracesInObjectCollectionArrayInitializers":true,"NewLinesForBracesInLambdaExpressionBody":true,"NewLineForElse":true,"NewLineForCatch":true,"NewLineForFinally":true,"NewLineForMembersInObjectInit":true,"NewLineForMembersInAnonymousTypes":true,"NewLineForClausesInQuery":true},"FileOptions":{"SystemExcludeSearchPatterns":["**/node_modules/**/*","**/bin/**/*","**/obj/**/*","**/.git/**/*","**/.git","**/.svn","**/.hg","**/CVS","**/.DS_Store"],"ExcludeSearchPatterns":[]},"RenameOptions":{"RenameOverloads":false,"RenameInStrings":false,"RenameInComments":false},"ImplementTypeOptions":{"InsertionBehavior":null,"PropertyGenerationBehavior":null},"Plugins":{"LocationPaths":null}}
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Syncthing\Unity\BaseBuilder\Base Building Game'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.Build'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        SUCCESS: Resolved to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.Build.dll' (name-only).
[dbug]: OmniSharp.MSBuild.ProjectSystem
        MSBuild environment: 
Mode: Standalone
RunningTests: False
RunningInVisualStudio: False
MSBuildToolsDirectory32: c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin
MSBuildToolsDirectory64: c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin
MSBuildSDKsPath: c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Sdks
CurrentMSBuildConfigurationFile: c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\MSBuild.exe.config
CurrentMSBuildExePath: c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\MSBuild.exe
CurrentMSBuildToolsDirectory: c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin
VisualStudioInstallRootDirectory: 
MSBuildExtensionsPath: c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin

[dbug]: OmniSharp.MSBuild.ProjectLoader
        'MSBuildExtensionsPath' set to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild'
[dbug]: OmniSharp.MSBuild.ProjectLoader
        'CscToolPath' set to 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Roslyn'
[dbug]: OmniSharp.MSBuild.ProjectLoader
        'CscToolExe' set to 'csc.exe'
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Syncthing\Unity\BaseBuilder\Base Building Game\Base Building Game.sln'.
[dbug]: OmniSharp.MSBuild.ProjectSystem
        Parsing ProjectConfigurationPlatforms of 'c:\Syncthing\Unity\BaseBuilder\Base Building Game\Base Building Game.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Syncthing\Unity\BaseBuilder\Base Building Game\Assembly-CSharp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Syncthing\Unity\BaseBuilder\Base Building Game'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Syncthing\Unity\BaseBuilder\Base Building Game' on host 10820.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Syncthing\Unity\BaseBuilder\Base Building Game\Assembly-CSharp.csproj
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 8,
  "Command": "/projects"
}
[dbug]: OmniSharp.Stdio.Host
        ************ Request ************
{
  "Type": "request",
  "Seq": 9,
  "Command": "/projects"
}
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.Build.resources, Version=15.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.Build.resources.dll'.
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'Microsoft.Build.resources, Version=15.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\Microsoft.Build.resources.dll'.
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'System.Threading.Tasks.Dataflow, Version=4.6.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Found 'c:\Users\fahme\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.7\.msbuild\Current\Bin\System.Threading.Tasks.Dataflow.dll' but name, 'System.Threading.Tasks.Dataflow, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a', did not match.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Syncthing\Unity\BaseBuilder\Base Building Game\Assembly-CSharp.csproj'.
c:\Syncthing\Unity\BaseBuilder\Base Building Game\Assembly-CSharp.csproj(0,0)
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=4.6.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks.Dataflow, Version=4.6.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Build.BackEnd.Logging.LoggingService.ProcessLoggingEvent(Object buildEvent, Boolean allowThrottling)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LogProjectEvaluationStarted(BuildEventContext projectEvaluationEventContext, String projectFile)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath, IReadOnlyDictionary`2 projectConfigurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 157
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath, IReadOnlyDictionary`2 configurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 75
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader, Guid sessionId, DotNetInfo dotNetInfo) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 116
   at OmniSharp.MSBuild.ProjectManager.<>c__DisplayClass31_0.<LoadProject>b__0() in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 304
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 315

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Syncthing\Unity\BaseBuilder\Base Building Game\Assembly-CSharp.csproj
[dbug]: OmniSharp.Stdio.Host
```
### C# log ###
```Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.37.7...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.37.7' (38312 KB).................... Done!
Installing package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.37.7'

Finished

Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
```
## Environment information ##

**VSCode version**: 1.53.2
**C# Extension**: 1.23.9

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.9|;

</details>

**Comment by JoeRobich** [comment]
@AzidanoValkran Thanks for logging this issue. It looks like a recent update to the included build tools may have a version mismatch.

For Unity development on Windows I recommend installing the Visual Studio Build Tools. Be sure when you install that you include the .NET Framework 4.7.1 Targeting pack component. Download from https://visualstudio.microsoft.com/downloads/
![image](https://user-images.githubusercontent.com/611219/110016120-82d9ee80-7cd9-11eb-9e6a-1a7f54ef925b.png)

**Comment by AzidanoValkran** [comment]
Hey @JoeRobich ,

Thank you so much for the timely response. I have followed the instructions above and have now got my IntelliSense and AutoComplete, hurrah!

However, my Unity scripts are now littered with 'Info' problems (blue squiggly lines). This is happening even for the default functions when you create a script in Unity.

Is this the same issue? Or should I close this issue and raise this as another one?

![image](https://user-images.githubusercontent.com/78864939/110036452-f0ffcf00-7d34-11eb-9bb5-7ec2247e9830.png)

**Comment by JoeRobich** [comment]
@AzidanoValkran Glad things are working for you! These are simply code suggestions. You can stop showing Info suggestions in the Problems pane from the filter.
![image](https://user-images.githubusercontent.com/611219/110037837-d0635500-7cf3-11eb-8162-84989812bd46.png)

If you want more control over which suggestions you see, you can add an .editorconfig file next to your .sln file. See https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options

The following .editorconfig would disable the unused member analysis.
```ini
[*.cs]
dotnet_diagnostic.IDE0051.severity = silent
```

**Comment by AzidanoValkran** [comment]
Oh mate... you are my hero. I owe you a beer!

This has opened up an entire world of IDE configuration that I never thought was even possible! I would even go as far as to say that it made the frustration and hair-pulling phase worth it. Today I Learned something new!

And with this all my issues are resolved, so I'll close this issue with this final comment.

I cannot even begin to express my heartfelt gratitude to your timely and informative responses!
