### ISSUE TITLE
Error when loading - "System.FormatException: Could not parse the JSON file"

### ISSUE THREAD

**Issue by cvionnet** [OmniSharp/omnisharp-vscode#4502]
## Issue Description ##
Hi,

The following error occurs when I try to open any C# project with VSCode (Console app, Godot).

At this point I try to :
- install Mono
- add "omnisharp.useGlobalMono": "always"  in settings.json
- uninstall / reinstall extensions

Last time I was able to open a project was with version 1.23.9 and before this Windows Update (https://support.microsoft.com/en-us/topic/april-13-2021-kb5001330-os-builds-19041-928-and-19042-928-cead30cd-f284-4115-a42f-d67fec538490)

Thanks for your help :)

## Steps to Reproduce ##
From the Explorer, right-click on a C# project directory > Open with code

### OmniSharp log ###
OmniSharp server started.
    Path: c:\Users\xxx\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\OmniSharp.exe
    PID: 17756

System.FormatException: Could not parse the JSON file. ---> System.Text.Json.JsonReaderException: '}' is invalid after a single JSON value. Expected end of data. LineNumber: 11 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 54
   at OmniSharp.HostHelpers.Start(Func`1 action) in D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:line 29
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.55.2
**C# Extension**: 1.23.11

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|asp-net-core-snippet-pack|adrianwilczynski|1.51.0|
|better-comments|aaron-bond|2.1.0|
|Bookmarks|alefragnani|13.0.4|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|csharp|ms-dotnettools|1.23.11|
|defold-vsc-snippets|selimanac|1.2.178|
|docomment|k--kato|0.1.20|
|gitlens|eamodio|11.4.1|
|godot-tools|geequlim|1.1.2|
|html-css-class-completion|Zignd|1.20.0|
|LiveServer|ritwickdey|5.6.1|
|lua|sumneko|1.20.4|
|lua-debug|actboy168|1.36.6|
|mono-debug|ms-vscode|0.16.2|
|monogame-pipeline-vscode|abcdef|0.0.2|
|pixelbyte-love2d|pixelbyte-studios|0.1.22|
|rainbow-csv|mechatroner|1.8.1|
|remote-wsl|ms-vscode-remote|0.54.6|
|shader|slevesque|1.1.5|
|synthwave-vscode|RobbOwen|0.1.8|
|theme-dracula|dracula-theme|2.22.3|
|vscode-autohide|sirmspencer|1.0.7|
|vscode-counter|uctakeoff|2.2.2|
|vscode-css-formatter|aeschli|1.0.1|
|vscode-drawio|hediet|1.4.0|
|vscode-fix-checksums|lehni|1.1.0|
|vscode-icons|vscode-icons-team|11.4.0|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-random|jrebocho|1.9.0|
|vscode-todo-highlight|wayou|1.0.4|;

</details>

**Comment by filipw** [comment]
do you use a custom omnisharp.json file? it sounds like it has invalid structure

**Comment by cvionnet** [comment]
Hi @filipw ,
Thanks for your help !

As long as I know, this is the default file. But by searching "omnisharp.json", I found that the file in "C:\Users\xxx\.omnisharp" has an extra "}" . After removing it, it works.

Thanks again !

**Comment by filipw** [comment]
great to hear, thanks for confirming.
sounds like something must have created this file for you (perhaps another extension) - Omnisharp itself doesn't have a default config file and also does not create a default file if it's not there
