### ISSUE TITLE
C# extension bug "Attempted to update project that is not loaded"

### ISSUE THREAD

**Issue by Matt2111** [OmniSharp/omnisharp-vscode#4690]
OmniSharp server started.
    Path: c:\Users\Matt's PC\.vscode\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.15-beta.2\OmniSharp.exe
    PID: 14888

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "c:\Users\Matt's PC\.vscode\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.15-beta.2\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\Matt's PC\.vscode\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.15-beta.2\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "c:\Users\Matt's PC\.vscode\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.15-beta.2\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\Matt's PC\.vscode\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.15-beta.2\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\Matt's PC\.vscode\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.15-beta.2\.msbuild
            MSBuildToolsPath = c:\Users\Matt's PC\.vscode\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.15-beta.2\.msbuild\Current\Bin
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Matt's PC\gradebook\src\GradeBook'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Matt's PC\gradebook\src\GradeBook'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Matt's PC\gradebook\src\GradeBook\GradeBook.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Matt's PC\gradebook\src\GradeBook'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Matt's PC\gradebook\src\GradeBook' on host 13456.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Matt's PC\gradebook\src\GradeBook\GradeBook.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Matt's PC\gradebook\src\GradeBook\GradeBook.csproj'.
c:\Users\Matt's PC\gradebook\src\GradeBook\GradeBook.csproj(0,0)
Microsoft.Build.Exceptions.InvalidProjectFileException: An unexpected token "s" was found at character position 85 in condition "'$(ImportByWildcardBeforeMicrosoftCommonProps)' == 'true' and exists('c:\Users\Matt's PC\.vscode\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.15-beta.2\.msbuild\$(MSBuildToolsVersion)\Imports\Microsoft.Common.props\ImportBefore')".  c:\Users\Matt's PC\.vscode\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.15-beta.2\.msbuild\Current\Microsoft.Common.props
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Parser.Factor(String expression)
   at Microsoft.Build.Evaluation.Parser.RelationalExpr(String expression)
   at Microsoft.Build.Evaluation.Parser.BooleanTermPrime(String expression, GenericExpressionNode lhs)
   at Microsoft.Build.Evaluation.Parser.BooleanTerm(String expression)
   at Microsoft.Build.Evaluation.Parser.Expr(String expression)
   at Microsoft.Build.Evaluation.Parser.Parse(String expression, ParserOptions optionSettings, ElementLocation elementLocation)
   at Microsoft.Build.Evaluation.ConditionEvaluator.EvaluateConditionCollectingConditionedProperties[P,I](String condition, ParserOptions options, Expander`2 expander, ExpanderOptions expanderOptions, Dictionary`2 conditionedPropertiesTable, String evaluationDirectory, ElementLocation elementLocation, ILoggingService loggingServices, BuildEventContext buildEventContext, IFileSystem fileSystem, ProjectRootElementCacheBase projectRootElementCache)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateConditionCollectingConditionedProperties(ProjectElement element, String condition, ExpanderOptions expanderOptions, ParserOptions parserOptions, ProjectRootElementCacheBase projectRootElementCache)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportGroupElement(String directoryOfImportingFile, ProjectImportGroupElement importGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath, IReadOnlyDictionary`2 projectConfigurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 157
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath, IReadOnlyDictionary`2 configurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 75
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader, Guid sessionId, DotNetInfo dotNetInfo) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 117
   at OmniSharp.MSBuild.ProjectManager.<>c__DisplayClass31_0.<LoadProject>b__0() in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 304
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 315

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\Matt's PC\gradebook\src\GradeBook\GradeBook.csproj

I've tried setting "omnisharp.path": "" to ""omnisharp.path": "latest"" and it still doesn't work.

**Comment by JoeRobich** [comment]
I believe that the GradeBook.csproj may be malformed as reported in this project load failure:

```
[warn]: OmniSharp.MSBuild.ProjectManager
Failed to load project file 'c:\Users\Matt's PC\gradebook\src\GradeBook\GradeBook.csproj'.
c:\Users\Matt's PC\gradebook\src\GradeBook\GradeBook.csproj(0,0)
Microsoft.Build.Exceptions.InvalidProjectFileException: An unexpected token "s" was found at character position 85 in condition "'$(ImportByWildcardBeforeMicrosoftCommonProps)' == 'true' and exists('c:\Users\Matt's PC.vscode\extensions\ms-dotnettools.csharp-1.23.14.omnisharp\1.37.15-beta.2.msbuild$(MSBuildToolsVersion)\Imports\Microsoft.Common.props\ImportBefore')". c:\Users\Matt's PC.vscode\extensions\ms-dotnettools.csharp-1.23.14.omnisharp\1.37.15-beta.2.msbuild\Current\Microsoft.Common.props
```

**Comment by Matt2111** [comment]
> I believe that the GradeBook.csproj may be malformed as reported in this project load failure:
> 
> 
> 
> ```
> 
> [warn]: OmniSharp.MSBuild.ProjectManager
> 
> Failed to load project file 'c:\Users\Matt's PC\gradebook\src\GradeBook\GradeBook.csproj'.
> 
> c:\Users\Matt's PC\gradebook\src\GradeBook\GradeBook.csproj(0,0)
> 
> Microsoft.Build.Exceptions.InvalidProjectFileException: An unexpected token "s" was found at character position 85 in condition "'$(ImportByWildcardBeforeMicrosoftCommonProps)' == 'true' and exists('c:\Users\Matt's PC.vscode\extensions\ms-dotnettools.csharp-1.23.14.omnisharp\1.37.15-beta.2.msbuild$(MSBuildToolsVersion)\Imports\Microsoft.Common.props\ImportBefore')". c:\Users\Matt's PC.vscode\extensions\ms-dotnettools.csharp-1.23.14.omnisharp\1.37.15-beta.2.msbuild\Current\Microsoft.Common.props
> 
> ```

You're right the quote in my system username is messing it up. Any ideas on how to fix this without going through the hassle of changing my system user name?

**Comment by JoeRobich** [comment]
@Matt2111 You can use escape characters to replace the special characters. See https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-special-characters?view=vs-2019

**Comment by Matt2111** [comment]
> @Matt2111 You can use escape characters to replace the special characters. See https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-special-characters?view=vs-2019  Single quotes can be replaced with `%27`.

Thank you so much for your help it's all fixed now. I was stuck on this all day I really should just read error messages more closely.

**Comment by JoeRobich** [comment]
@Matt2111 No problem. Happy coding!
