### ISSUE TITLE
Blazor unsupported?

### ISSUE THREAD

**Issue by akkgr** [OmniSharp/omnisharp-vscode#4997]
Working with a Blazor project is practical immpossible, 
- Formatting not working or worse corrupts file
- Syntax highlight not working
- Autocomplete suggestion not working 
- Errors, Warnings e.t.c not working

After  clean and build project  and restart vscode  all might work until a file save then again nothing works.
Really does anyone is working blazor projects with vscode ?

**Comment by JoeRobich** [comment]
@akkgr Can you please share the OmniSharp Log from the VS Code Output pane?

**Comment by akkgr** [comment]
> @akkgr Can you please share the OmniSharp Log from the VS Code Output pane?

Starting OmniSharp server at 12/1/2022, 10:45:19 π.μ.
    Target: d:\work\github\myEstia\myEstia.sln

OmniSharp server started.
    Path: c:\Users\tasos\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\OmniSharp.exe
    PID: 5640

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2022 17.0.32014.148 17.0.0 - "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
            2: StandAlone 17.0.0 - "c:\Users\tasos\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2022 17.0.32014.148 17.0.0 - "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'd:\work\github\myEstia'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'd:\work\github\myEstia\myEstia.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\work\github\myEstia\Server\Estia.Server.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\work\github\myEstia\Shared\Estia.Shared.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'd:\work\github\myEstia\Client\Estia.Client.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'd:\work\github\myEstia'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'd:\work\github\myEstia' on host 5900.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\work\github\myEstia\Server\Estia.Server.csproj
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: d:\work\github\myEstia\Client\Pages\Buildings\ApartmentEdit.razor__virtual.cs added to workspace
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\work\github\myEstia\Server\Estia.Server.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\work\github\myEstia\Server\Estia.Server.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\work\github\myEstia\Shared\Estia.Shared.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\work\github\myEstia\Shared\Estia.Shared.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\work\github\myEstia\Shared\Estia.Shared.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: d:\work\github\myEstia\Client\Estia.Client.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'd:\work\github\myEstia\Client\Estia.Client.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'd:\work\github\myEstia\Client\Estia.Client.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Estia.Server
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Estia.Shared
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Estia.Client
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 188.

**Comment by JoeRobich** [comment]
Well this is a good sign that the Razor support is recognizing the project.

```
info: OmniSharp.OmniSharpWorkspace
Miscellaneous file: d:\work\github\myEstia\Client\Pages\Buildings\ApartmentEdit.razor__virtual.cs added to workspace
```

Do you see these same errors with a new Blazor project? If so, what is the workflow that gets it into the broken state?

CC: @ryanbrandenburg in case you have questions.

**Comment by ryanbrandenburg** [comment]
@akkgr the log you pasted doesn't indicate anything out of the ordinary that I noticed, and I wasn't able to repro what you describe. What kind of errors are you seeing when they're "red indicating errors"? Could you copy-paste or screenshot those errors? Do you still see problems on a "basic" app like what you would get from "dotnet new blazorserver" or do they seem to be specific to your more detailed repo?

**Comment by travisnielsen** [comment]
I can reproduce this error with a multi-root workspace in VS Code. [I created a sample here](https://github.com/travisnielsen/omnitest), which is based on two projects initialized using `dotnet new`. This is what I see:

![image](https://user-images.githubusercontent.com/3196834/150647161-c99a1c18-d6f6-407d-896a-3c89d0d3391a.png)

The log doesn't say anything unusual but I'm attaching it here for the environment details:

```
Starting OmniSharp server at 1/22/2022, 10:31:52 AM
    Target: /Users/travisnielsen/repos/omnitest/blazordemo

OmniSharp server started with .NET 6.0.101
.
    Path: /Users/travisnielsen/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0-net6.0/OmniSharp.dll
    PID: 16972

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 6.0.101 17.0.0 - "/usr/local/share/dotnet/sdk/6.0.101/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.101 17.0.0 - "/usr/local/share/dotnet/sdk/6.0.101/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/travisnielsen/repos/omnitest/blazordemo'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/travisnielsen/repos/omnitest/blazordemo/blazordemo.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/travisnielsen/repos/omnitest/blazordemo'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/travisnielsen/repos/omnitest/blazordemo' on host 16613.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/travisnielsen/repos/omnitest/blazordemo/blazordemo.csproj
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: /Users/travisnielsen/repos/omnitest/blazordemo/App.razor__virtual.cs added to workspace
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/travisnielsen/repos/omnitest/blazordemo/blazordemo.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/travisnielsen/repos/omnitest/blazordemo/blazordemo.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: blazordemo
```

**Comment by travisnielsen** [comment]
This issue appears to be very similar to: https://github.com/dotnet/razor-tooling/issues/5517

**Comment by tthiery** [comment]
@mikadumont @dibarbet Is anyone working on this? Blazor is such an amazing platform (as SPA, as SSR, and soonish especially as Hybrid App) but the VS Code razor file editing experience is is up until today a mess. And AFAIR it was better with O#.

I am currently editing a blazor app and I am basically back in the old school experience of vi on text screen how it was back when I learned programming in the 90s.

**Comment by tthiery** [comment]
Current Stack Trace for me. These range errors are all over the place when editing razor files.

````
Error - 10:55:07 AM] [LanguageServerHost] System.ArgumentException: Range={ Start={ Line=140, Character=0 }, End={ Line=1043, Character=0 } }. text.Length=39. text.Lines.Count=3
 ---> System.ArgumentOutOfRangeException: The requested line number 140 must be less than the number of lines 3. (Parameter 'Line')
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 67
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetTextSpan(LinePositionSpan span) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 78
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.RangeToTextSpan(Range range, SourceText text) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 300
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.RangeToTextSpan(Range range, SourceText text) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 300
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.ComputeSemanticTokensDataAsync(ClientCapabilities capabilities, Document document, Range[] ranges, ClassificationOptions options, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs:line 104
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.HandleRequestHelperAsync(IGlobalOptionService globalOptions, SemanticTokensRefreshQueue semanticTokensRefreshQueue, Range[] ranges, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs:line 64
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensRangeHandler.HandleRequestAsync(SemanticTokensRangeParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRangeHandler.cs:line 47
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 176
[Error - 10:55:07 AM] Request textDocument/semanticTokens/range failed.
  Message: Range={ Start={ Line=140, Character=0 }, End={ Line=1043, Character=0 } }. text.Length=39. text.Lines.Count=3
  Code: -32000 
[object Object]
[Error - 10:55:07 AM] [LanguageServerHost] System.ArgumentException: Range={ Start={ Line=988, Character=33 }, End={ Line=988, Character=33 } }. text.Length=39. text.Lines.Count=3
 ---> System.ArgumentOutOfRangeException: The requested line number 988 must be less than the number of lines 3. (Parameter 'Line')
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 67
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetTextSpan(LinePositionSpan span) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 78
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.RangeToTextSpan(Range range, SourceText text) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 300
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.RangeToTextSpan(Range range, SourceText text) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 300
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActions.CodeActionHelpers.GetActionSetsAsync(Document document, CodeActionOptionsProvider fallbackOptions, ICodeFixService codeFixService, ICodeRefactoringService codeRefactoringService, Range selection, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs:line 417
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActions.CodeActionHelpers.GetVSCodeActionsAsync(CodeActionParams request, Document document, CodeActionOptionsProvider fallbackOptions, ICodeFixService codeFixService, ICodeRefactoringService codeRefactoringService, Boolean hasVsLspCapability, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs:line 93
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActionsHandler.HandleRequestAsync(CodeActionParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionsHandler.cs:line 67
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 176
[Error - 10:55:07 AM] [LanguageServerHost] System.ArgumentException: Range={ Start={ Line=140, Character=0 }, End={ Line=1043, Character=0 } }. text.Length=74. text.Lines.Count=4
 ---> System.ArgumentOutOfRangeException: The requested line number 140 must be less than the number of lines 4. (Parameter 'Line')
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 67
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetTextSpan(LinePositionSpan span) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 78
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.RangeToTextSpan(Range range, SourceText text) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 300
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.RangeToTextSpan(Range range, SourceText text) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 300
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.ComputeSemanticTokensDataAsync(ClientCapabilities capabilities, Document document, Range[] ranges, ClassificationOptions options, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs:line 104
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.HandleRequestHelperAsync(IGlobalOptionService globalOptions, SemanticTokensRefreshQueue semanticTokensRefreshQueue, Range[] ranges, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs:line 64
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensRangeHandler.HandleRequestAsync(SemanticTokensRangeParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRangeHandler.cs:line 47
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 176
[Error - 10:55:07 AM] Request textDocument/semanticTokens/range failed.
  Message: Range={ Start={ Line=140, Character=0 }, End={ Line=1043, Character=0 } }. text.Length=74. text.Lines.Count=4
  Code: -32000 
[object Object]
[Error - 10:55:07 AM] [LanguageServerHost] System.ArgumentException: Range={ Start={ Line=988, Character=34 }, End={ Line=988, Character=34 } }. text.Length=74. text.Lines.Count=4
 ---> System.ArgumentOutOfRangeException: The requested line number 988 must be less than the number of lines 4. (Parameter 'Line')
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 67
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetTextSpan(LinePositionSpan span) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 78
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.RangeToTextSpan(Range range, SourceText text) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 300
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.RangeToTextSpan(Range range, SourceText text) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 300
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActions.CodeActionHelpers.GetActionSetsAsync(Document document, CodeActionOptionsProvider fallbackOptions, ICodeFixService codeFixService, ICodeRefactoringService codeRefactoringService, Range selection, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs:line 417
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActions.CodeActionHelpers.GetVSCodeActionsAsync(CodeActionParams request, Document document, CodeActionOptionsProvider fallbackOptions, ICodeFixService codeFixService, ICodeRefactoringService codeRefactoringService, Boolean hasVsLspCapability, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs:line 93
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActionsHandler.HandleRequestAsync(CodeActionParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionsHandler.cs:line 67
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 176
[Error - 10:55:13 AM] [LanguageServerHost] System.ArgumentException: Range={ Start={ Line=395, Character=33 }, End={ Line=1043, Character=0 } }. text.Length=74. text.Lines.Count=4
 ---> System.ArgumentOutOfRangeException: The requested line number 395 must be less than the number of lines 4. (Parameter 'Line')
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 67
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetTextSpan(LinePositionSpan span) in /_/src/Compilers/Core/Portable/Text/TextLineCollection.cs:line 78
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.RangeToTextSpan(Range range, SourceText text) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 300
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.RangeToTextSpan(Range range, SourceText text) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 300
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.ComputeSemanticTokensDataAsync(ClientCapabilities capabilities, Document document, Range[] ranges, ClassificationOptions options, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs:line 104
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensHelpers.HandleRequestHelperAsync(IGlobalOptionService globalOptions, SemanticTokensRefreshQueue semanticTokensRefreshQueue, Range[] ranges, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensHelpers.cs:line 64
   at Microsoft.CodeAnalysis.LanguageServer.Handler.SemanticTokens.SemanticTokensRangeHandler.HandleRequestAsync(SemanticTokensRangeParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensRangeHandler.cs:line 47
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 176
[Error - 10:55:13 AM] Request textDocument/semanticTokens/range failed.
  Message: Range={ Start={ Line=395, Character=33 }, End={ Line=1043, Character=0 } }. text.Length=74. text.Lines.Count=4
  Code: -32000 
````

**Comment by dibarbet** [comment]
@tthiery that issue is tracked here on the Razor side - https://github.com/dotnet/razor/issues/9637
cc @davidwengier

**Comment by tthiery** [comment]
Sounds good to have found the right place. Does this other issue also cover the bad formatting and the other issues of the original issue here?

**Comment by dibarbet** [comment]
@tthiery please file new issues with details for specific problems - this issue is fairly old and applies to O# (not necessarily the new version).
