### ISSUE TITLE
Error "Couldn't start client Razor Language Server" when omnisharp.useModernNet=true on MacOS with arm64

### ISSUE THREAD

**Issue by marcinci** [OmniSharp/omnisharp-vscode#5093]
## Issue Description ##
"Couldn't start client Razor Language Server" popup window appears with error in Razor Log.
Error shows up in Razor Log, so it might not be directly related with C# extension. Nevertheless, it seems like the component is used by C# extension.

## Steps to Reproduce ##
1) Change omnisharp.useModernNet to true
2) Create a Blazor project with command: dotnet new blazorserver -f net6.0
3) Open new Blazor project.

## Expected Behavior ##
No error appears.

## Actual Behavior ##
"Couldn't start client Razor Language Server" popup window appears with error in Razor Log.
<img width="863" alt="error_message" src="https://user-images.githubusercontent.com/9963164/156922383-94476ee8-df62-47c0-b7af-d25a72108b78.png">

### OmniSharp log ###

Starting OmniSharp server at 3/6/2022, 12:59:29 PM
    Target: /Users/myusername/IdeaProjects/BlazorApp

OmniSharp server started with .NET 6.0.102
.
    Path: /Users/myusername/.vscode/extensions/ms-dotnettools.csharp-1.24.1/.omnisharp/1.38.1-net6.0/OmniSharp.dll
    PID: 6523

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: .NET Core SDK 6.0.102 17.0.0 - "/usr/local/share/dotnet/sdk/6.0.102/"
            2: .NET Core SDK 6.0.101 17.0.0 - "/usr/local/share/dotnet/sdk/6.0.101/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.102 17.0.0 - "/usr/local/share/dotnet/sdk/6.0.102/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/myusername/IdeaProjects/BlazorApp'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/myusername/IdeaProjects/BlazorApp/BlazorApp.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/myusername/IdeaProjects/BlazorApp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/myusername/IdeaProjects/BlazorApp' on host 6492.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/myusername/IdeaProjects/BlazorApp/BlazorApp.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/myusername/IdeaProjects/BlazorApp/BlazorApp.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/myusername/IdeaProjects/BlazorApp/BlazorApp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: BlazorApp

### Razor log ###

--------------------------------------------------------------------------------
Razor.VSCode version 6.0.0-preview.5.21358.6
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

[Error - 12:59:29 PM] Starting client failed
Error: spawn Unknown system error -86
	at ChildProcess.spawn (internal/child_process.js:403:11)
	at Object.spawn (child_process.js:570:9)
	at /Users/myusername/.vscode/extensions/ms-dotnettools.csharp-1.24.1/dist/extension.js:2:1060499

### C# log ###
Empty

## Environment information ##

**VSCode version**: 1.65.0
**C# Extension**: 1.24.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    02d5242ed7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.2
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.102/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.24.1|;

</details>

**Comment by timanderson** [comment]
I get the same error.

**Comment by Enver-Yilmaz** [comment]
I get the same error, this may have happened when rosetta is not installed.

**Comment by tverboon** [comment]
@JoeRobich Any idea when the Razor LSP for ARM64 is included in Omnisharp? Thanks!
