### ISSUE TITLE
Microsoft.CodeAnalysis.Elfie.dll as part of .omnisharp folder of extension marked as infected

### ISSUE THREAD

**Issue by Aelrath** [OmniSharp/omnisharp-vscode#5112]
## Issue Description ##
Microsoft.CodeAnalysis.Elfie.dll being marked as infected with trojan by BitDefender.
![image](https://user-images.githubusercontent.com/7330765/158764233-043d34e0-0611-486f-9a4e-c97d8af100f1.png)
Been using BitDefender as my antivirus for years while also using VSCode with Omnisharp for development. First time it has marked that dll as being infected. Now this could either be on bitdefenders end where they updated the signature for that trojan that is now causing a false positive on that dll or that file might have been updated in a nuget package and some malicious code made its way into it. 

Edit: Just as note to test I deleted the extension folder from \.vscode\extensions and reinstalled it through vscode and once downloaded and installed by vscode the file was once again marked infected (installed fresh as seen from C# log)

## Steps to Reproduce ##
Load VSCode

## Expected Behavior ##
Not having the Microsoft.CodeAnalysis.Elfie.dll part of .omnisharp folder of VSCode extension marked as infected.

## Actual Behavior ##
Microsoft.CodeAnalysis.Elfie.dll should not be infected (*possibly?)

### OmniSharp log ###
<details>
OmniSharp server started with .NET 6.0.201
.
    Path: c:\Users\<user>\.vscode\extensions\ms-dotnettools.csharp-1.24.1\.omnisharp\1.38.2-beta.40-net6.0\OmniSharp.dll
    PID: 18892

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.19044.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: .NET Core SDK 6.0.201 17.1.0 - "C:\Program Files\dotnet\sdk\6.0.201\"
            2: .NET Core SDK 6.0.103 17.0.0 - "C:\Program Files\dotnet\sdk\6.0.103\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.201 17.1.0 - "C:\Program Files\dotnet\sdk\6.0.201\"
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at OmniSharp.OmniSharpWorkspace..ctor(HostServicesAggregator aggregator, ILoggerFactory loggerFactory, IFileSystemWatcher fileSystemWatcher) in D:\a\1\s\src\OmniSharp.Roslyn\OmniSharpWorkspace.cs:line 53
   at lambda_method16(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.TypedParts.ActivationFeatures.DisposalFeature.<>c__DisplayClass0_0.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature.<>c__DisplayClass1_0.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport[TExport](String contractName)
   at System.Composition.CompositionContext.GetExport[TExport]()
   at OmniSharp.Stdio.Host.Initialize() in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 58
   at OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) in D:\a\1\s\src\OmniSharp.Stdio\Host.cs:line 52
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 70
   at OmniSharp.CommandLineApplication.<>c__DisplayClass12_0.<OnExecute>b__0() in D:\a\1\s\src\OmniSharp.Host\CommandLineApplication.cs:line 92
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at OmniSharp.CommandLineApplication.Execute(String[] args) in D:\a\1\s\src\OmniSharp.Host\CommandLineApplication.cs:line 65
   at OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_0.<Main>b__0() in D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:line 84
   at OmniSharp.HostHelpers.Start(Func`1 action) in D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:line 30
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.CodeAnalysis.Elfie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</details>

### C# log ###
<details>Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 6 / x64)' (39061 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 6 / x64)'

Finished

Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.38.2-beta.40...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 6 / x64), Version = 1.38.2-beta.40' (40264 KB).................... Done!
Installing package 'OmniSharp for Windows (.NET 6 / x64), Version = 1.38.2-beta.40'

Finished

</details>

## Environment information ##

**VSCode version**: 1.65.2
**C# Extension**: 1.24.1

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.103 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|angular-schematics|cyrilletuzi|5.1.2|
|Angular2|johnpapa|13.0.0|
|angular2-inline|natewallace|0.0.17|
|auto-close-tag|formulahendry|0.5.14|
|auto-rename-tag|formulahendry|0.1.10|
|azure-account|ms-vscode|0.10.1|
|csharp|ms-dotnettools|1.24.1|
|data-workspace-vscode|ms-mssql|0.1.1|
|githistory|donjayamanne|0.6.19|
|gitlens|eamodio|12.0.4|
|html-css-class-completion|Zignd|1.20.0|
|material-icon-theme|PKief|4.14.1|
|mssql|ms-mssql|1.13.0|
|ng-template|Angular|13.3.0|
|prettier-vscode|esbenp|9.3.0|
|remote-containers|ms-vscode-remote|0.224.2|
|sql-database-projects-vscode|ms-mssql|0.14.1|
|vs-keybindings|ms-vscode|0.2.1|
|vscode-autoprefixer|mrmlnc|3.0.1|
|vscode-azureappservice|ms-azuretools|0.23.1|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-cosmosdb|ms-azuretools|0.18.1|
|vscode-csharp-snippets|jorgeserrano|1.1.0|
|vscode-css-peek|pranaygp|4.2.0|
|vscode-docker|ms-azuretools|1.20.0|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-mjml|DanielKnights|2.4.10|
|vscode-npm-script|eg2|0.3.24|
|vscode-peacock|johnpapa|4.0.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.17|;

</details>

**Comment by fabio-s-franco** [comment]
Github project page disappeared too and the package became unlisted.

**Comment by filipw** [comment]
Thanks I will close it here as it is related to the server. https://github.com/OmniSharp/omnisharp-roslyn/issues/2369
