### ISSUE TITLE
OmniSharp.Extensions.JsonRpc.Server.MethodNotSupportedException: Method not found: 'razor/serverReady'.

### ISSUE THREAD

**Issue by random-pixels** [OmniSharp/omnisharp-vscode#5342]
## Environment data
`dotnet --info` output:
.NET SDK (reflecting any global.json):
 Version:   6.0.108
 Commit:    4e3a463d2b

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  21
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.108 [/usr/lib/dotnet/dotnet6-6.0.108/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.NETCore.App]

VS Code version: 1.70.1
C# Extension version: 1.25.0

## OmniSharp log
```
--------------------------------------------------------------------------------
Razor.VSCode version 6.0.0-preview.5.21358.6
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

Cannot get required symbol EVP_MD_size from libssl
[Info  - 7:15:17 a.m.] Connection to server got closed. Server will restart.
[Error - 7:15:17 a.m.] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:994214)
	at Object.dispose (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1050936)
	at x.handleConnectionClosed (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1051111)
	at x.handleConnectionClosed (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1070276)
	at t (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1049310)
	at n.invoke (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at $ (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:986274)
	at n.invoke (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at l.fireClose (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997133)
	at Socket.<anonymous> (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997895)
	at Socket.emit (node:events:402:35)
	at Socket.emit (node:domain:475:12)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 7:15:17 a.m.] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:994214)
	at Object.dispose (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1050936)
	at x.handleConnectionClosed (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1051111)
	at x.handleConnectionClosed (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1070276)
	at t (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1049310)
	at n.invoke (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at $ (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:986274)
	at n.invoke (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at l.fireClose (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997133)
	at Socket.<anonymous> (/home/user/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997895)
	at Socket.emit (node:events:402:35)
	at Socket.emit (node:domain:475:12)
	at Pipe.<anonymous> (node:net:687:12)
Unhandled exception. OmniSharp.Extensions.JsonRpc.Server.MethodNotSupportedException: Method not found: 'razor/serverReady'.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.Returning[TResponse](CancellationToken cancellationToken) in OmniSharp.Extensions.JsonRpc.dll:token 0x6000b4d+0x16f
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.ReturningVoid(CancellationToken cancellationToken) in OmniSharp.Extensions.JsonRpc.dll:token 0x6000b4e+0x71
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorServerReadyPublisher.ProjectSnapshotManager_Changed(Object sender, ProjectChangeEventArgs args) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorServerReadyPublisher.cs:line 62
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state) in System.Private.CoreLib.dll:token 0x6002db8+0x0
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in System.Private.CoreLib.dll:token 0x6002ae1+0x14
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in System.Private.CoreLib.dll:token 0x6002abb+0x0
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in System.Private.CoreLib.dll:token 0x6002bb5+0x67
   at System.Threading.Thread.StartCallback() in System.Private.CoreLib.dll:token 0x6002734+0xe
[Info  - 7:15:20 a.m.] Connection to server got closed. Server will restart.
Unhandled exception. OmniSharp.Extensions.JsonRpc.Server.MethodNotSupportedException: Method not found: 'razor/serverReady'.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.Returning[TResponse](CancellationToken cancellationToken) in OmniSharp.Extensions.JsonRpc.dll:token 0x6000b4d+0x16f
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.ReturningVoid(CancellationToken cancellationToken) in OmniSharp.Extensions.JsonRpc.dll:token 0x6000b4e+0x71
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorServerReadyPublisher.ProjectSnapshotManager_Changed(Object sender, ProjectChangeEventArgs args) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorServerReadyPublisher.cs:line 62
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state) in System.Private.CoreLib.dll:token 0x6002db8+0x0
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in System.Private.CoreLib.dll:token 0x6002ae1+0x14
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in System.Private.CoreLib.dll:token 0x6002abb+0x0
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in System.Private.CoreLib.dll:token 0x6002bb5+0x67
   at System.Threading.Thread.StartCallback() in System.Private.CoreLib.dll:token 0x6002734+0xe
[Info  - 7:15:23 a.m.] Connection to server got closed. Server will restart.
Unhandled exception. OmniSharp.Extensions.JsonRpc.Server.MethodNotSupportedException: Method not found: 'razor/serverReady'.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.Returning[TResponse](CancellationToken cancellationToken) in OmniSharp.Extensions.JsonRpc.dll:token 0x6000b4d+0x16f
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.ReturningVoid(CancellationToken cancellationToken) in OmniSharp.Extensions.JsonRpc.dll:token 0x6000b4e+0x71
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorServerReadyPublisher.ProjectSnapshotManager_Changed(Object sender, ProjectChangeEventArgs args) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorServerReadyPublisher.cs:line 62
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state) in System.Private.CoreLib.dll:token 0x6002db8+0x0
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in System.Private.CoreLib.dll:token 0x6002ae1+0x14
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in System.Private.CoreLib.dll:token 0x6002abb+0x0
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in System.Private.CoreLib.dll:token 0x6002bb5+0x67
   at System.Threading.Thread.StartCallback() in System.Private.CoreLib.dll:token 0x6002734+0xe
[Info  - 7:15:27 a.m.] Connection to server got closed. Server will restart.
Unhandled exception. OmniSharp.Extensions.JsonRpc.Server.MethodNotSupportedException: Method not found: 'razor/serverReady'.
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.Returning[TResponse](CancellationToken cancellationToken) in OmniSharp.Extensions.JsonRpc.dll:token 0x6000b4d+0x16f
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.ReturningVoid(CancellationToken cancellationToken) in OmniSharp.Extensions.JsonRpc.dll:token 0x6000b4e+0x71
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorServerReadyPublisher.ProjectSnapshotManager_Changed(Object sender, ProjectChangeEventArgs args) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorServerReadyPublisher.cs:line 62
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state) in System.Private.CoreLib.dll:token 0x6002db8+0x0
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in System.Private.CoreLib.dll:token 0x6002ae1+0x14
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in System.Private.CoreLib.dll:token 0x6002abb+0x0
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in System.Private.CoreLib.dll:token 0x6002bb5+0x67
   at System.Threading.Thread.StartCallback() in System.Private.CoreLib.dll:token 0x6002734+0xe
[Error - 7:15:30 a.m.] Connection to server got closed. Server will not be restarted.
```

## Steps to reproduce
Seems to happen when editing .cshtml (Razor) views. No error pops up, but I notice the issue because Razor Intellisense stops working.
If I check the logs, I see "Connection to server got closed. Server will not be restarted"

## Expected  behavior
Razor to be happy

## Actual behavior
Razor crashes repeatedly, Intellisense stops working

## Additional context
Sometimes (but not always) restarting Omnisharp temporarily fixes the issue.
This error also happened on Linux Mint 20.3 before I updated to 21, and also in several previous versions of VSCode (i.e. not limited to my current version).

**Comment by WatchDogsDev** [comment]
It's because of openssl version.

A workaround is setting this environment variable before running vscode:

```
export CLR_OPENSSL_VERSION_OVERRIDE=1.1
```

But is there anyway to support the openssl 3 and fix it ?

**Comment by allisonchou** [comment]
Hi all! We released a new version of the C# extension earlier today (v1.25.4) which should address this problem.

@dibarbet Could you please close out this issue?
