### ISSUE TITLE
Razor pages server crashing in vscode

### ISSUE THREAD

**Issue by muchirajunior** [OmniSharp/omnisharp-vscode#5347]
when i open vscode Razor pages i get this error
**The Razor Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.**
`--------------------------------------------------------------------------------
Razor.VSCode version 6.0.0-preview.5.21358.6
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

Cannot get required symbol EVP_MD_size from libssl
[Info  - 2:39:23 AM] Connection to server got closed. Server will restart.
[Error - 2:39:23 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:994214)
	at Object.dispose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1050936)
	at x.handleConnectionClosed (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1051111)
	at x.handleConnectionClosed (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1070276)
	at t (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1049310)
	at n.invoke (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at $ (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:986274)
	at n.invoke (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at t.StreamMessageWriter.fireClose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:999879)
	at Socket.<anonymous> (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1000249)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)
Cannot get required symbol EVP_MD_size from libssl
[Info  - 2:39:28 AM] Connection to server got closed. Server will restart.
[Error - 2:39:28 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:994214)
	at Object.dispose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1050936)
	at x.handleConnectionClosed (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1051111)
	at x.handleConnectionClosed (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1070276)
	at t (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1049310)
	at n.invoke (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at $ (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:986274)
	at n.invoke (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at l.fireClose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997133)
	at Socket.<anonymous> (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997895)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
Cannot get required symbol EVP_MD_size from libssl
[Info  - 2:39:33 AM] Connection to server got closed. Server will restart.
[Error - 2:39:33 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:994214)
	at Object.dispose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1050936)
	at x.handleConnectionClosed (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1051111)
	at x.handleConnectionClosed (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1070276)
	at t (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1049310)
	at n.invoke (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at $ (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:986274)
	at n.invoke (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at l.fireClose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997133)
	at Socket.<anonymous> (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997895)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
Cannot get required symbol EVP_MD_size from libssl
[Info  - 2:39:39 AM] Connection to server got closed. Server will restart.
[Error - 2:39:39 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:994214)
	at Object.dispose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1050936)
	at x.handleConnectionClosed (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1051111)
	at x.handleConnectionClosed (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1070276)
	at t (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1049310)
	at n.invoke (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at $ (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:986274)
	at n.invoke (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at l.fireClose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997133)
	at Socket.<anonymous> (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997895)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
Cannot get required symbol EVP_MD_size from libssl
[Error - 2:39:46 AM] Connection to server got closed. Server will not be restarted.
[Error - 2:39:46 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:994214)
	at Object.dispose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1050936)
	at x.handleConnectionClosed (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1051111)
	at x.handleConnectionClosed (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1070276)
	at t (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1049310)
	at n.invoke (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at $ (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:986274)
	at n.invoke (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at l.fireClose (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997133)
	at Socket.<anonymous> (/home/muchirajunior/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997895)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)`

**Comment by jsheely** [comment]
Same problem. Nothing more to add to far

I've had several issues with libssl3 on ubuntu with the latest update. This feels like another issue on the stack

>Cannot get required symbol EVP_MD_size from libssl

**Comment by muchirajunior** [comment]
i hope the team help us so that dotnet 6 runs stable on vscode just like dotnet 5.

**Comment by GeorgeKnight** [comment]
Hi everyone,

I'm facing the same issue.

**Environent data**
```
.NET SDK (reflecting any global.json):
 Version:   6.0.109
 Commit:    58a93139d8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/dotnet6-6.0.109/sdk/6.0.109/

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.109 [/usr/lib/dotnet/dotnet6-6.0.109/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [/usr/lib/dotnet/dotnet6-6.0.109/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/lib/dotnet/dotnet6-6.0.109/shared/Microsoft.NETCore.App]
```

**VS Code**
```
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-47-generic snap
Sandboxed: No
```
**C# Extension version:**
`1.25.0`

**Razor Log**
```
--------------------------------------------------------------------------------
Razor.VSCode version 6.0.0-preview.5.21358.6
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

Cannot get required symbol EVP_MD_size from libssl
[Info  - 10:59:36 PM] Connection to server got closed. Server will restart.
[Error - 10:59:36 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:994214)
	at Object.dispose (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1050936)
	at x.handleConnectionClosed (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1051111)
	at x.handleConnectionClosed (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1070276)
	at t (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1049310)
	at n.invoke (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at $ (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:986274)
	at n.invoke (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at l.fireClose (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997133)
	at Socket.<anonymous> (/home/gknight/.vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:997895)
	at Socket.emit (node:events:538:35)
	at Pipe.<anonymous> (node:net:687:12)
```

**Comment by muchirajunior** [comment]
@OmniSharp should help us solve this issue i think https://github.com/OmniSharp/omnisharp-vscode

**Comment by mtaron** [comment]
## Logs

#### OmniSharp
```
Client - 11:42:59 AM] -- Starting Issue Data Collection-- 
[Client - 11:43:05 AM] Notifying document '/home/mtaron/repos/docugami/admin/Shared/NavMenu.razor' changed 'opened'
OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter: Finding descriptors for textDocument/didOpen | Method='textDocument/didOpen'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Created attribute aspnetcorerazor::file:///home/mtaron/repos/docugami/admin/Shared/NavMenu.razor | Attribute='aspnetcorerazor::file:///home/mtaron/repos/docugami/admin/Shared/NavMenu.razor'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Looking for handler for descriptors textDocument/didOpen | Method='textDocument/didOpen'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Checking handler textDocument/didOpen:Microsoft.AspNetCore.Razor.LanguageServer.RazorDocumentSynchronizationEndpoint | Method='textDocument/didOpen' Handler='Microsoft.AspNetCore.Razor.LanguageServer.RazorDocumentSynchronizationEndpoint'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Registration options OmniSharp.Extensions.LanguageServer.Protocol.Models.TextDocumentRegistrationOptions | OptionsName='OmniSharp.Extensions.LanguageServer.Protocol.Models.TextDocumentRegistrationOptions'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Document Selector [**/*.{cshtml,razor}] | DocumentSelector='[**/*.{cshtml,razor}]'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Handler Selected: Microsoft.AspNetCore.Razor.LanguageServer.RazorDocumentSynchronizationEndpoint  via [**/*.{cshtml,razor}] (targeting OmniSharp.Extensions.JsonRpc.IJsonRpcNotificationHandler`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.DidOpenTextDocumentParams, OmniSharp.Extensions.LanguageProtocol, Version=0.18.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]) | Handler='Microsoft.AspNetCore.Razor.LanguageServer.RazorDocumentSynchronizationEndpoint' Id='' DocumentSelector='[**/*.{cshtml,razor}]' HandlerInterface='OmniSharp.Extensions.JsonRpc.IJsonRpcNotificationHandler`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.DidOpenTextDocumentParams, OmniSharp.Extensions.LanguageProtocol, Version=0.18.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]'
OmniSharp.Extensions.JsonRpc.ProcessScheduler: Swapping from Parallel to Serial | From='Parallel' To='Serial'
OmniSharp.Extensions.JsonRpc.ProcessScheduler: Completing existing request process type Parallel | Type='Parallel'
OmniSharp.Extensions.JsonRpc.ProcessScheduler: Queueing Serial:textDocument/didOpen request for processing | Type='Serial' Name='textDocument/didOpen'
OmniSharp.Extensions.JsonRpc.InputHandler: Starting: Processing notification textDocument/didOpen | Method='textDocument/didOpen'
OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter: Starting: Routing Notification textDocument/didOpen | Method='textDocument/didOpen'
OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter: Converting params for Notification textDocument/didOpen to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidOpenTextDocumentParams | Method='textDocument/didOpen' Type='OmniSharp.Extensions.LanguageServer.Protocol.Models.DidOpenTextDocumentParams'
OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter: Finding descriptors for textDocument/codeAction | Method='textDocument/codeAction'
[Info  - 11:43:05 AM] Microsoft.AspNetCore.Razor.LanguageServer.ProjectSystem.DefaultRazorProjectService: Opening document '/home/mtaron/repos/docugami/admin/Shared/NavMenu.razor' in project '/home/mtaron/repos/docugami/admin/Admin.csproj'. | 
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Found attributes 1, razor::file:///home/mtaron/repos/docugami/admin/Shared/NavMenu.razor | Count='1' Attributes='razor::file:///home/mtaron/repos/docugami/admin/Shared/NavMenu.razor'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Looking for handler for descriptors textDocument/codeAction | Method='textDocument/codeAction'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Checking handler textDocument/codeAction:Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.CodeActionEndpoint | Method='textDocument/codeAction' Handler='Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.CodeActionEndpoint'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Registration options OmniSharp.Extensions.LanguageServer.Protocol.Models.CodeActionRegistrationOptions | OptionsName='OmniSharp.Extensions.LanguageServer.Protocol.Models.CodeActionRegistrationOptions'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Document Selector [**/*.{cshtml,razor}] | DocumentSelector='[**/*.{cshtml,razor}]'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Handler Selected: Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.CodeActionEndpoint  via [**/*.{cshtml,razor}] (targeting OmniSharp.Extensions.JsonRpc.IJsonRpcRequestHandler`2[[Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.Models.RazorCodeActionParams, Microsoft.AspNetCore.Razor.LanguageServer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[OmniSharp.Extensions.LanguageServer.Protocol.Models.CommandOrCodeActionContainer, OmniSharp.Extensions.LanguageProtocol, Version=0.18.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]) | Handler='Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.CodeActionEndpoint' Id='' DocumentSelector='[**/*.{cshtml,razor}]' HandlerInterface='OmniSharp.Extensions.JsonRpc.IJsonRpcRequestHandler`2[[Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.Models.RazorCodeActionParams, Microsoft.AspNetCore.Razor.LanguageServer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[OmniSharp.Extensions.LanguageServer.Protocol.Models.CommandOrCodeActionContainer, OmniSharp.Extensions.LanguageProtocol, Version=0.18.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]'
OmniSharp.Extensions.JsonRpc.ProcessScheduler: Swapping from Serial to Parallel | From='Serial' To='Parallel'
OmniSharp.Extensions.JsonRpc.ProcessScheduler: Completing existing request process type Serial | Type='Serial'
OmniSharp.Extensions.JsonRpc.ProcessScheduler: Queueing Parallel:textDocument/codeAction:2 request for processing | Type='Parallel' Name='textDocument/codeAction:2'
OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter: Finding descriptors for textDocument/semanticTokens | Method='textDocument/semanticTokens'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Found attributes 1, razor::file:///home/mtaron/repos/docugami/admin/Shared/NavMenu.razor | Count='1' Attributes='razor::file:///home/mtaron/repos/docugami/admin/Shared/NavMenu.razor'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Looking for handler for descriptors textDocument/semanticTokens | Method='textDocument/semanticTokens'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Checking handler textDocument/semanticTokens:Microsoft.AspNetCore.Razor.LanguageServer.Semantic.RazorSemanticTokensEndpoint | Method='textDocument/semanticTokens' Handler='Microsoft.AspNetCore.Razor.LanguageServer.Semantic.RazorSemanticTokensEndpoint'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Registration options OmniSharp.Extensions.LanguageServer.Protocol.Models.Proposals.SemanticTokensRegistrationOptions | OptionsName='OmniSharp.Extensions.LanguageServer.Protocol.Models.Proposals.SemanticTokensRegistrationOptions'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Document Selector [**/*.{cshtml,razor}] | DocumentSelector='[**/*.{cshtml,razor}]'
OmniSharp.Extensions.LanguageServer.Server.Matchers.TextDocumentMatcher: Handler Selected: Microsoft.AspNetCore.Razor.LanguageServer.Semantic.RazorSemanticTokensEndpoint  via [**/*.{cshtml,razor}] (targeting OmniSharp.Extensions.JsonRpc.IJsonRpcRequestHandler`2[[OmniSharp.Extensions.LanguageServer.Protocol.Models.Proposals.SemanticTokensParams, OmniSharp.Extensions.LanguageProtocol, Version=0.18.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022],[OmniSharp.Extensions.LanguageServer.Protocol.Models.Proposals.SemanticTokens, OmniSharp.Extensions.LanguageProtocol, Version=0.18.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]) | Handler='Microsoft.AspNetCore.Razor.LanguageServer.Semantic.RazorSemanticTokensEndpoint' Id='' DocumentSelector='[**/*.{cshtml,razor}]' HandlerInterface='OmniSharp.Extensions.JsonRpc.IJsonRpcRequestHandler`2[[OmniSharp.Extensions.LanguageServer.Protocol.Models.Proposals.SemanticTokensParams, OmniSharp.Extensions.LanguageProtocol, Version=0.18.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022],[OmniSharp.Extensions.LanguageServer.Protocol.Models.Proposals.SemanticTokens, OmniSharp.Extensions.LanguageProtocol, Version=0.18.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]'
OmniSharp.Extensions.JsonRpc.ProcessScheduler: Queueing Parallel:textDocument/semanticTokens:3 request for processing | Type='Parallel' Name='textDocument/semanticTokens:3'
Cannot get required symbol EVP_MD_size from libssl
[Info  - 11:43:05 AM] Connection to server got closed. Server will restart.
[Error - 11:43:05 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:994214)
	at Object.dispose (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1050936)
	at x.handleConnectionClosed (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1051111)
	at x.handleConnectionClosed (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1070276)
	at t (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1049310)
	at n.invoke (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at $ (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:986274)
	at n.invoke (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979052)
	at r.fire (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:979782)
	at t.StreamMessageWriter.fireClose (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:999879)
	at Socket.<anonymous> (/home/mtaron/.config/vscode/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/dist/extension.js:2:1000249)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)
```

## Workspace information

#### Razor document:
<details><summary>Expand</summary>
<p>

```Razor
<MudNavMenu>
    <MudNavLink Href="" Match="NavLinkMatch.All" Icon="@Icons.Material.Filled.Home">Home</MudNavLink>
</MudNavMenu>

```

</p>
</details>

#### Projected CSharp document:
<details><summary>Expand</summary>
<p>

```C#
////////////////////// Projected CSharp as seen by extension ///////////////////////



////////////////////// Projected CSharp as seen by VSCode ///////////////////////

// 0
```

</p>
</details>

#### Projected Html document:
<details><summary>Expand</summary>
<p>

```Html
////////////////////// Projected Html as seen by extension ///////////////////////



////////////////////// Projected Html as seen by VSCode ///////////////////////

// 0
```

</p>
</details>

## Machine information


**VSCode version**: 1.71.2
**Razor.VSCode version**: 1.25.0
#### `dotnet --info`

<details><summary>Expand</summary>
<p>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.401/

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

```

</p>
</details>

#### Extensions
<details><summary>Expand</summary>
<p>


|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.11.1|
|bash-ide-vscode|mads-hartmann|1.14.0|
|blazorwasm-companion|ms-dotnettools|1.1.0|
|csharp|ms-dotnettools|1.25.0|
|github-vscode-theme|GitHub|6.3.2|
|gitlens|eamodio|12.2.2|
|jupyter|ms-toolsai|2022.8.1002431955|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.9|
|python|ms-python|2022.14.0|
|shellcheck|timonwong|0.22.0|
|vscode-aks-tools|ms-kubernetes-tools|1.3.4|
|vscode-azurefunctions|ms-azuretools|1.7.4|
|vscode-azureresourcegroups|ms-azuretools|0.5.6|
|vscode-docker|ms-azuretools|1.22.1|
|vscode-dotnet-runtime|ms-dotnettools|1.5.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.10|
|vscode-pylance|ms-python|2022.9.20|
|vscode-yaml|redhat|1.10.1|;


</p>
</details>

**Comment by mtaron** [comment]
Sadly that does not resolve the issue for me. :\

**Comment by muchirajunior** [comment]
also doesn't work for me too

**Comment by GeorgeKnight** [comment]
Hi @elestedt. Same here :(. The workaround doesn't work

**Comment by Dicusar94** [comment]
Hi, I have the same problem, and it's really annoying. :(

**Comment by elestedt** [comment]
Probably the workaround I found solves a different, but related, issue. Too bad.

**Comment by aaronduty** [comment]
This workaround likely works because you have OpenSSL 1.1 installed alongside OpenSSL 3. Most Linux distros have removed nearly old traces of 1.1, including the compat libraries, so that's not going to work in this case.

I have compiled 1.1 on Fedora 26 for a Ruby install but I don't know what environment variable this would look to for that path. Any ideas for that?

Based on what else I've read about this issue, the Razor Language Server packaged with the extension needs to be upgraded. It might do to point people to where they can get a newer version of it and point out the extension setting for its path. As it is, I'm still searching.

**Comment by muchirajunior** [comment]
The VSCode team claims its a C++ issue, couldn't figure out how. [here](https://github.com/microsoft/vscode/issues/164426)

**Comment by vcsjones** [comment]
As noted in the linked issue, this should be resolved in the 1.25.4 version of the extension.

**Comment by douglas-wiliam** [comment]
I updated the C# extension to version 1.25.4 and problema apparently was solved.

**Comment by muchirajunior** [comment]
the issue is fixed :tada:

**Comment by muchirajunior** [comment]
bug report
