### ISSUE TITLE
Cannot install C# extension on Ubuntu 22.04

### ISSUE THREAD

**Issue by rickrain** [OmniSharp/omnisharp-vscode#5591]
Have a fresh install of Ubuntu 22.04 and VS Code. I am able to install many other extensions for other languages just fine. But, when I try to install the C# extension I get the following error:

```
2023-02-21 20:58:49.290 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'commentsResolvedState' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-02-21 20:58:53.211 [info] [perf] Render performance baseline is 95ms
2023-02-21 20:59:20.637 [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {"name":"Canceled"}
2023-02-21 21:02:01.014 [error] Download: XHR failed
    at yt.download (vscode-file://vscode-app/snap/code/119/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17345)
    at async $.h (vscode-file://vscode-app/snap/code/119/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
2023-02-21 21:02:01.049 [error] XHR failed: Download: XHR failed
    at yt.download (vscode-file://vscode-app/snap/code/119/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17345)
    at async $.h (vscode-file://vscode-app/snap/code/119/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
2023-02-21 21:07:56.485 [error] Download: XHR failed
    at yt.download (vscode-file://vscode-app/snap/code/119/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17345)
    at async $.h (vscode-file://vscode-app/snap/code/119/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
2023-02-21 21:07:56.520 [error] XHR failed: Download: XHR failed
    at yt.download (vscode-file://vscode-app/snap/code/119/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17345)
    at async $.h (vscode-file://vscode-app/snap/code/119/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
```

## Environment data
`dotnet --info` output:

```
.NET SDK:
 Version:   7.0.200
 Commit:    534117727b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.200/

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  7.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

VS Code version:
C# Extension version: `1.75.1`

## Steps to reproduce

1. Go to VS Code extensions.
2. Search for C# extension.
3. Click install. Wait.....
4. See errors in logs

## Expected  behavior
The C# extension should install.

## Actual behavior
Extension does not install. See details above.

**Comment by rickrain** [comment]
I was able to work around this by downloading the extension and installing it manually. However, I still find it odd that this is the only extension (so far) that I've not been able to install from the VS Code extension view (UI).

```bash
code --install-extension ms-dotnettools.csharp-1.25.4@linux-x64.vsix
```

**Comment by ss108** [comment]
I am having the same issue, and in fact can't even install it manually:

```code --install-extension ms-dotnettools.csdevkit-0.4.10@linux-x64.vsix                                           
Installing extensions...
(node:950823) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Download: Unable to write file '/home/ss108/.config/Code/CachedExtensionVSIXs/.039e14ad-861a-4327-8341-c2e0add9b3d9' (Error: aborted)
    at p.download (/snap/code/138/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:49:7143)
    at async B.x (/snap/code/138/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:50:19746)
    at async B.h (/snap/code/138/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:50:17790) {
  code: 'Download'
}
Failed Installing Extensions: file:///home/ss108/Downloads/ms-dotnettools.csdevkit-0.4.10%40linux-x64.vsix
```
