### ISSUE TITLE
Request textDocument/formatting failed.

### ISSUE THREAD

**Issue by Captain-Tom-CL** [OmniSharp/omnisharp-vscode#5663]
whenever i tried to format code in razor files or .cshtml files. it always showed me that:

![image](https://user-images.githubusercontent.com/54521529/234870802-8eb4a779-d06e-476e-97f2-4f271c011e34.png)

**Comment by jhalmu** [comment]
Same here

**Comment by tkoenig89** [comment]
Have a look at this, might be the same: #5561. A fix is on the way.

**Comment by LuckyKang79** [comment]
This issue is also reproduced in the following configuration：


**VS Code version**:1.81.1
**C# Extension version**: v2.0.376

**dotnet --info output:**
```
.NET SDK (reflecting any global.json):
 Version:   6.0.317
 Commit:    98282dc4ea

Runtime Environment:
 OS Name:     ol
 OS Version:  9.2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.317/

global.json file:
  Not found

Host:
  Version:      6.0.22
  Architecture: x64
  Commit:       ad40cc35b5

.NET SDKs installed:
  6.0.317 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```
 **Actual behavior**
![image](https://github.com/dotnet/vscode-csharp/assets/93763301/7608958b-5ede-4a1d-8e32-a9f5548ac7fd)
**Output Log:**
```
--------------------------------------------------------------------------------
Razor.VSCode version 7.0.0-preview.23410.1
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
- To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
- To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

 

[Info  - 2:27:39 AM] Returned 30 semantic tokens for range Microsoft.VisualStudio.LanguageServer.Protocol.Range in file:///home/aapt/BlazorClient/Client/Pages/Index.razor.
[Info  - 2:27:40 AM] Language query request for (8, 5) = Html at (8, 5)
[Error - 2:27:42 AM] System.ArgumentNullException: Value cannot be null. (Parameter 'DocumentContext')
   at Microsoft.AspNetCore.Razor.LanguageServer.EndpointContracts.RazorRequestContext.GetRequiredDocumentContext() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorRequestContext.cs:line 47
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorMapToDocumentRangesEndpoint.HandleRequestAsync(RazorMapToDocumentRangesParams request, RazorRequestContext requestContext, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorMapToDocumentRangesEndpoint.cs:line 37
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
[Error - 2:27:43 AM] System.ArgumentNullException: Value cannot be null. (Parameter 'DocumentContext')
   at Microsoft.AspNetCore.Razor.LanguageServer.EndpointContracts.RazorRequestContext.GetRequiredDocumentContext() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorRequestContext.cs:line 47
   at Microsoft.AspNetCore.Razor.LanguageServer.DocumentSynchronization.DocumentDidChangeEndpoint.HandleNotificationAsync(DidChangeTextDocumentParams request, RazorRequestContext requestContext, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentSynchronization/DocumentDidChangeEndpoint.cs:line 56
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
[Error - 2:27:43 AM] System.ArgumentNullException: Value cannot be null. (Parameter 'DocumentContext')
   at Microsoft.AspNetCore.Razor.LanguageServer.EndpointContracts.RazorRequestContext.GetRequiredDocumentContext() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorRequestContext.cs:line 47
   at Microsoft.AspNetCore.Razor.LanguageServer.DocumentSynchronization.DocumentDidChangeEndpoint.HandleNotificationAsync(DidChangeTextDocumentParams request, RazorRequestContext requestContext, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentSynchronization/DocumentDidChangeEndpoint.cs:line 56
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.ProcessQueueAsync()
[Info  - 2:27:43 AM] Error processing queue, shutting down
[Error - 2:27:43 AM] Request textDocument/completion failed.
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Info  - 2:27:43 AM] Connection to server got closed. Server will restart.
true
[Error - 2:27:44 AM] System.ArgumentNullException: Value cannot be null. (Parameter 'DocumentContext')
   at Microsoft.AspNetCore.Razor.LanguageServer.EndpointContracts.RazorRequestContext.GetRequiredDocumentContext() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorRequestContext.cs:line 47
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorLanguageQueryEndpoint.HandleRequestAsync(RazorLanguageQueryParams request, RazorRequestContext requestContext, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageQueryEndpoint.cs:line 35
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
[Error - 2:27:44 AM] System.ArgumentNullException: Value cannot be null. (Parameter 'DocumentContext')
   at Microsoft.AspNetCore.Razor.LanguageServer.EndpointContracts.RazorRequestContext.GetRequiredDocumentContext() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorRequestContext.cs:line 47
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorMapToDocumentRangesEndpoint.HandleRequestAsync(RazorMapToDocumentRangesParams request, RazorRequestContext requestContext, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorMapToDocumentRangesEndpoint.cs:line 37
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
[Client - 2:27:44 AM] (Warning) provideCodeLens failed with Error: Value cannot be null. (Parameter 'DocumentContext')
Resolved 32 completion items.
[Info  - 2:27:45 AM] Returned 32 semantic tokens for range Microsoft.VisualStudio.LanguageServer.Protocol.Range in file:///home/aapt/BlazorClient/Client/Pages/Index.razor.
[Info  - 2:27:45 AM] Language query request for (9, 4) = Html at (9, 4)
[Info  - 2:27:54 AM] Applying TextChange: { [159..160), "" }
[Info  - 2:27:54 AM] Language query request for (9, 3) = Html at (9, 3)
Resolved 39 completion items.
[Info  - 2:27:54 AM] Returned 32 semantic tokens for range Microsoft.VisualStudio.LanguageServer.Protocol.Range in file:///home/aapt/BlazorClient/Client/Pages/Index.razor.
[Info  - 2:27:57 AM] Applying TextChange: { [157..159), "Counter" }
[Info  - 2:27:57 AM] Returned 32 semantic tokens for range Microsoft.VisualStudio.LanguageServer.Protocol.Range in file:///home/aapt/BlazorClient/Client/Pages/Index.razor.
[Info  - 2:27:59 AM] Applying TextChange: { [164..164), ">" }
[Info  - 2:27:59 AM] Language query request for (9, 8) = Html at (9, 8)
[Info  - 2:27:59 AM] Applying TextChange: { [165..165), "</Counter>" }
[Info  - 2:27:59 AM] Returned 37 semantic tokens for range Microsoft.VisualStudio.LanguageServer.Protocol.Range in file:///home/aapt/BlazorClient/Client/Pages/Index.razor.
[Info  - 2:28:00 AM] Saved Document /home/aapt/BlazorClient/Client/Pages/Index.razor
```
