### ISSUE TITLE
NWF: Microsoft.VisualStudio.VIL.DebuggerHost.FusionHelper.CheckByPreviousBinds

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#612]
From telemetry with have 324 hits of an non-fatal Watson with the following stack:

    at System.IO.PathInternal.CheckInvalidPathChars(String path)
    at System.IO.Path.GetDirectoryName(String path)
    at Microsoft.VisualStudio.VIL.DebuggerHost.FusionHelper.CheckByPreviousBinds(AssemblyResolver resolver, AssemblyName name)
    at Microsoft.VisualStudio.VIL.DebuggerHost.FusionHelper.GuessPathFromAssemblyName(AssemblyResolver resolver, AssemblyName name)
    at Microsoft.VisualStudio.VIL.DebuggerHost.FusionHelper.LoadAssemblyByName(AssemblyResolver resolver, AssemblyName assemblyName, Boolean fThrowOnError, IList`1 specialCasedAssemblies)
    at Microsoft.VisualStudio.VIL.DebuggerHost.AssemblyResolver.ResolveAssembly(AssemblyName name, Boolean fThrowOnError)
    at Ilrun.CachedTypeUniverse.AssemblyResolutionCache.LookupAndAddCachedResolution(String typeName) 
    at Ilrun.CachedTypeUniverse.ResolveAssembly(Module scope, Token tokenAssemblyRef, String typeName)
    at Microsoft.MetadataReader.MetadataOnlyModule.ResolveTypeRef(ITypeReference typeReference)
    at Ilrun.ModuleEntry.ResolveTy...

"vs.diagnostics.debugger.nonfatalerror.exceptiontype":"System.ArgumentException"

All hits are on Windows

**Comment by wesrupert** [comment]
Fix should be available in the next release.
