### ISSUE TITLE
NFW: Microsoft.VisualStudio.VIL.VisualStudioHost.VSGlobalContext.GetSourceLocations

### ISSUE THREAD

**Issue by gregg-miskelly** [OmniSharp/omnisharp-vscode#613]
From telemetry, we can see the following non-fatal Watson being reported --

    at XapiExceptionProcessing.ThrowHR(Int32 code)
    at Microsoft.VisualStudio.Debugger.Symbols.DkmInstructionSymbol.GetSourcePositionCallback(DkmWorkList WorkList, DkmSourcePositionFlags Flags, DkmInspectionSession InspectionSession, DkmCompletionRoutine`1 CompletionRoutine)
    at Microsoft.VisualStudio.VIL.VisualStudioHost.VSGlobalContext.GetSourceLocations(ExceptionStackFrame[] frames)
    at Ilrun.ExceptionStackTrace.EnsureStringCalculated(DefaultHost host)
    at Ilrun.MscorlibHooks.System_Exception.GetStackTraceImpl(VirtualMachine vm, MethodBase method, CallArgs args)
    at Ilrun.DefaultHost.TryExecuteMethod(VirtualMachine virtualMachine, MethodBase method, CallArgs args)
    at Ilrun.VirtualMachine.ExecuteMethodInternal(MethodBase method, CallArgs args, Boolean fAllowHooks, IVirtualStackFrame inspectionFrame)
    at Ilrun.Stuff.ExecuteCall(VirtualState vs, Type tConstrainedPrefix, ILOpCode opCode, Int32 token, String& arg)
    at Ilrun.Stuff.ExecuteInlineToken(VirtualState vs, String& instruction,

exceptiontype: System.NotImplementedException

This would happen if the DkmSymbol is an ClrRemoteSymbolStore or ClrRemotePortableSymbolStore.

**Comment by gregg-miskelly** [comment]
This will be fixed in the next version of clrdbg.
