### ISSUE TITLE
Unable to load DLL System.Native Unity project

### ISSUE THREAD

**Issue by raldred** [OmniSharp/omnisharp-vscode#786]
I read that it was recommened to switch to using the C# extension instead of legacy C# for Unity now However it seems omnisharp is unable to load my project.

csproj file:
https://gist.github.com/raldred/d75792fd7e719d8fe718a5e45839576d
## Environment data

`dotnet --info` output:

```
C:\Users\robaldred>dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
Version:            1.0.0-preview2-003121
Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.14393
OS Platform: Windows
RID:         win10-x64
```

VS Code version: `1.5.3`
C# Extension version: `1.4.1`
## Steps to reproduce

Open my project in VCCode via the Unity VScode plugin from dotbunny.
## Expected  behavior

Project should load in VScode, Intellisense should work.
## Actual behavior

Intellisense does not work.
& Omnisharp reports errors loading project

```
Starting OmniSharp server at 27/09/2016, 10:29:52
    Target: c:\Users\robaldred\Documents\Games\EnawsGame\EnawsGame.sln

OmniSharp server started
    Path: C:\Users\robaldred\.vscode\extensions\ms-vscode.csharp-1.4.1\out\.omnisharp-mono\OmniSharp.exe
    PID: 13616

OmniSharp: -s c:\Users\robaldred\Documents\Games\EnawsGame\EnawsGame.sln --hostPID 9272 DotNet:enablePackageRestore=false --encoding utf-8 --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location 'c:\Users\robaldred\Documents\Games\EnawsGame' on host 9272.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in c:\Users\robaldred\Documents\Games\EnawsGame
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] Detecting projects in 'c:\Users\robaldred\Documents\Games\EnawsGame\EnawsGame.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from 'c:\Users\robaldred\Documents\Games\EnawsGame\Assembly-CSharp-firstpass.csproj'.
[INFORMATION:OmniSharp#ProjectFileInfo] Using toolset 2.0 for c:\Users\robaldred\Documents\Games\EnawsGame\Assembly-CSharp-firstpass.csproj
[WARNING:OmniSharp#MSBuild] Failed to process project file 'c:\Users\robaldred\Documents\Games\EnawsGame\Assembly-CSharp-firstpass.csproj'.
c:\Users\robaldred\Documents\Games\EnawsGame\Assembly-CSharp-firstpass.csproj(1,1)
System.DllNotFoundException: Unable to load DLL 'System.Native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
at Interop.Sys.GetUnixNamePrivate()
at System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform osPlatform)
at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(MSBuildOptions options, ILogger logger, String solutionDirectory, String projectFilePath, ICollection`1 diagnostics)
at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProject(String projectFilePath)
```

**Comment by DustinCampbell** [comment]
Could you try the latest release? This issue should be fixed now.

**Comment by DustinCampbell** [comment]
And by latest release, I mean the latest release of the C# extension. We just release 1.5.2 here: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp.

**Comment by raldred** [comment]
Thanks Dustin, great stuff I'll try first thing in the morning.

**Comment by raldred** [comment]
Confirmed working thanks @DustinCampbell

**Comment by DustinCampbell** [comment]
Thanks for confirming!
