### ISSUE TITLE
[ERROR] Error: Failed to start OmniSharp

### ISSUE THREAD

**Issue by jrieken** [OmniSharp/omnisharp-vscode#83]
_From @egenita on March 10, 2016 6:28_

[INFO] Starting OmniSharp at 'd:\dev\aspnet vnext\MovieAngularJsApp'...
[INFO] Started OmniSharp from 'C:\Users\EGenita\.vscode\extensions\ms-vscode.csharp-0.3.3\bin\omnisharp.cmd' with process id 3228...
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<WithAssemblies>b__0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at OmniSharp.OmnisharpWorkspace..ctor(HostServicesBuilder builder)
   at lambda_method(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.TypedParts.ActivationFeatures.DisposalFeature.<>c__DisplayClass1.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature.<>c__DisplayClass2.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport[TExport](String contractName)
   at OmniSharp.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, ILibraryManager manager, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOptions`1 optionsAccessor)
[ERROR] Error: Failed to start OmniSharp

_Copied from original issue: Microsoft/vscode#3949_

**Comment by DustinCampbell** [comment]
@egenita, is this still an issue?

**Comment by hickford** [comment]
I have a similar problem "Error starting OmniSharp"

	[INFO] Starting OmniSharp at 'c:\Users\User\Documents\Visual Studio 2015\Projects\ConsoleApplication4\ConsoleApplication4.sln'...
	[INFO] Started OmniSharp from 'C:\Users\User\.vscode\extensions\ms-vscode.csharp-0.3.7\bin\omnisharp.cmd' with process id 12956...
	System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
	   ICSharpCode.NRefactory 6.0.0-alpha3
	   Kestrel 1.0.0-beta4
	   Microsoft.AspNet.Diagnostics 1.0.0-beta4
	   Microsoft.AspNet.Diagnostics.Interfaces 1.0.0-beta4
	   Microsoft.AspNet.FeatureModel 1.0.0-beta4
	   Microsoft.AspNet.FileProviders 1.0.0-beta4
	   Microsoft.AspNet.FileProviders.Interfaces 1.0.0-beta4
	   Microsoft.AspNet.Hosting 1.0.0-beta4
	   Microsoft.AspNet.Hosting.Interfaces 1.0.0-beta4
	   Microsoft.AspNet.Http 1.0.0-beta4
	   Microsoft.AspNet.Http.Core 1.0.0-beta4
	   Microsoft.AspNet.Http.Extensions 1.0.0-beta4
	   Microsoft.AspNet.Http.Interfaces 1.0.0-beta4
	   Microsoft.AspNet.Server.Kestrel 1.0.0-beta4
	   Microsoft.AspNet.WebUtilities 1.0.0-beta4
	   Microsoft.CodeAnalysis 1.0.0-rc2
	   Microsoft.CodeAnalysis.Analyzers 1.0.0-rc2
	   Microsoft.CodeAnalysis.Common 1.0.0-rc2
	   Microsoft.CodeAnalysis.CSharp 1.0.0-rc2
	   Microsoft.CodeAnalysis.CSharp.Features 1.0.0-rc2
	   Microsoft.CodeAnalysis.CSharp.Workspaces 1.0.0-rc2
	   Microsoft.CodeAnalysis.VisualBasic 1.0.0-rc2
	   Microsoft.CodeAnalysis.VisualBasic.Workspaces 1.0.0-rc2
	   Microsoft.CodeAnalysis.Workspaces.Common 1.0.0-rc2
	   Microsoft.Composition 1.0.30
	   Microsoft.Framework.Caching.Interfaces 1.0.0-beta4
	   Microsoft.Framework.Caching.Memory 1.0.0-beta4
	   Microsoft.Framework.ConfigurationModel 1.0.0-beta4
	   Microsoft.Framework.ConfigurationModel.Interfaces 1.0.0-beta4
	   Microsoft.Framework.ConfigurationModel.Json 1.0.0-beta4
	   Microsoft.Framework.DependencyInjection 1.0.0-beta4
	   Microsoft.Framework.DependencyInjection.Interfaces 1.0.0-beta4
	   Microsoft.Framework.FileSystemGlobbing 1.0.0-beta4
	   Microsoft.Framework.Logging 1.0.0-beta4
	   Microsoft.Framework.Logging.Console 1.0.0-beta4
	   Microsoft.Framework.Logging.Interfaces 1.0.0-beta4
	   Microsoft.Framework.OptionsModel 1.0.0-beta4
	   Microsoft.Framework.Runtime.Interfaces 1.0.0-beta4
	   Microsoft.Framework.WebEncoders.Core 1.0.0-beta4
	   Microsoft.Net.Http.Headers 1.0.0-beta4
	   Microsoft.Web.Xdt 2.1.1
	   Newtonsoft.Json 7.0.1
	   NuGet.Configuration 3.1.0

	Searched Locations:
	  C:\Users\User\.vscode\extensions\ms-vscode.csharp-0.3.7\bin\packages\OmniSharp\1.0.0\{name}\project.json
	  C:\Users\User\.vscode\extensions\ms-vscode.csharp-0.3.7\bin\src\{name}\project.json
	  C:\Users\User\.vscode\extensions\ms-vscode.csharp-0.3.7\bin\packages\{name}\{version}\{name}.nuspec
	  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\{name}.dll
	  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\{name}.dll
	  C:\Windows\Microsoft.NET\assembly\GAC_32\{name}\{version}\{name}.dll
	  C:\Windows\Microsoft.NET\assembly\GAC_64\{name}\{version}\{name}.dll
	  C:\Windows\Microsoft.NET\assembly\GAC_MSIL\{name}\{version}\{name}.dll

	Try running 'dnu restore'.

	   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
	   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
	   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)

**Comment by DustinCampbell** [comment]
This is pretty stale at this point, especially given that DNX, DNU, DNVM and all of that are going and .NET Core is here to stay. I'm going to close this issue, but please let me know if it's still a problem.
